### ISSUE TITLE
[8193.13] Toolset "Adjust Location Tool" Not Showing All Parameters Fully

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#101]
Reported to me by a friend of mine.

**To Reproduce**

 - Place a placeable in the toolset.
 - Right click on it and select "Adjust Location" 
 - This is what you see...

![adjust_tool](https://user-images.githubusercontent.com/58920224/85792191-1e55a100-b701-11ea-8cf9-afea3a9ee207.jpg)

This is his CPU Specs

![Capturecomp](https://user-images.githubusercontent.com/58920224/85792298-3f1df680-b701-11ea-8d78-9f161b61e343.jpg)

This is his GPU specs. He uses the highlighted GPU. I told him to try switching to the Nvidia card.

![GPU](https://user-images.githubusercontent.com/58920224/85792372-5f4db580-b701-11ea-8beb-14cd400ed25e.jpg)

**Specifics**

 - Game build 8193.13

**Comment by virusman** [comment]
@pstemarie Are you using UI scaling?

**Comment by pstemarie** [comment]
The computer is a laptop. Not sure if its HiDPI or not. He isn't using scaling.

**Comment by virusman** [comment]
@pstemarie How does it look when opened with a static placeable selected?

**Comment by pstemarie** [comment]
Victor, at this point I'd just close this one out as a non issue. I've sent the guy three messages asking him what you asked me and haven't gotten a response. Thus, I'd say his issue is solved.
