### ISSUE TITLE
EffectDamageResistance causes weird interaction if used with multiple damage types

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#106]
**To Reproduce**

 - Load attached save. [000875 - effectdamageresistances.zip](https://github.com/Beamdog/nwn-issues/files/4861809/000875.-.effectdamageresistances.zip)
 - Use Floor level 1 (adds this effect to the player EffectDamageResistance(DAMAGE_TYPE_FIRE | DAMAGE_TYPE_COLD | DAMAGE_TYPE_ACID | DAMAGE_TYPE_ELECTRICAL, 20, 30);
 - Use the ballista which will fire hellball, check combat log. Notice it resists only 15 and it resists sonic.
 - Use Floor Level 2 (adds this effect to the player EffectDamageResistance(DAMAGE_TYPE_FIRE | DAMAGE_TYPE_COLD | DAMAGE_TYPE_ACID | DAMAGE_TYPE_ELECTRICAL | DAMAGE_TYPE_SONIC, 20, 30);
 - Use the ballista again, check combat log. Notice it doesn't mention any limit. Use ballista second time to verify the effect has no limit.

**Specifics**

 - OS: any
 - Game build: any
 - Distro platform: any
 - Content overrides? doesn't matter

**If needed, describe the bug**

Well, this is more a feature request than bug fix but I will try it anyway :).

Most of the functions that uses DAMAGE_TYPE_* parameter allows their chaining. The function EffectDamageResistance looks like it also allows this but when it is done it has this bugged interaction. What the example effect above wants to achieve is a damage resistance that blocks 20 points of damage of cold and fire and acid and electricity and sonic damage, but maximally 30 damage resisted total of any of those types before collapsing.

**Comment by Finaldeath** [comment]
I'm pretty sure the use case you specify isn't the intent of EffectDamageResistance. As per Endure Elements:

```c
...
    int nDuration = GetCasterLevel(OBJECT_SELF);
    int nAmount = 20;
    int nResistance = 10;
    int nMetaMagic = GetMetaMagicFeat();
    effect eCold = EffectDamageResistance(DAMAGE_TYPE_COLD, nResistance, nAmount);
    effect eFire = EffectDamageResistance(DAMAGE_TYPE_FIRE, nResistance, nAmount);
    effect eAcid = EffectDamageResistance(DAMAGE_TYPE_ACID, nResistance, nAmount);
    effect eSonic = EffectDamageResistance(DAMAGE_TYPE_SONIC, nResistance, nAmount);
    effect eElec = EffectDamageResistance(DAMAGE_TYPE_ELECTRICAL, nResistance, nAmount);
    effect eDur = EffectVisualEffect(VFX_DUR_PROTECTION_ELEMENTS);
    effect eVis = EffectVisualEffect(VFX_IMP_ELEMENTAL_PROTECTION);
    effect eDur2 = EffectVisualEffect(VFX_DUR_CESSATE_POSITIVE);

    //Fire cast spell at event for the specified target
    SignalEvent(oTarget, EventSpellCastAt(OBJECT_SELF, SPELL_ENDURE_ELEMENTS, FALSE));

    //Link Effects
    effect eLink = EffectLinkEffects(eCold, eFire);
    eLink = EffectLinkEffects(eLink, eAcid);
    eLink = EffectLinkEffects(eLink, eSonic);
    eLink = EffectLinkEffects(eLink, eElec);
    eLink = EffectLinkEffects(eLink, eDur);
    eLink = EffectLinkEffects(eLink, eDur2);
...
```

The leixcon also comments that you need to link the effects into one: https://nwnlexicon.com/index.php?title=EffectDamageResistance

I'm not sure EffectDamageResistance ever had support for multiple damage types in one call and linking are the way to do it. Maybe your script does but I can't see it, post the mod file then people can test it?

**Comment by pF-arQon** [comment]
> I'm pretty sure the use case you specify isn't the intent of EffectDamageResistance.

I can't speak to the INTENT, but note that the various Ele Resist spells have fundamentally different behavior than "just" DR: they're there to be exhausted in their entiretly when any PART of the effect is exhausted, which may explain why they need to be defined as distinct effects that are linked rather than a single compound effect.

That said, I did find this lurking in our code:
```
    // note: this version should work, but doesn't
    //e = EffectLinkEffects( e, EffectDamageImmunityIncrease( DAMAGE_TYPE_BLUDGEONING | DAMAGE_TYPE_PIERCING | DAMAGE_TYPE_SLASHING, nPower ) );
```
which has been replaced with individual effects, as you suggest.

I don't remember why, but a comment in there suggests it's because of this:
```
    // ugh: 1.69's fix for weapons with compound damage types (scythe, morningstar, etc)
    // actually makes them BYPASS damage immunity if applied like this
```
I'm not entirely confident that's what actually broke it - it's just too long ago for my memory, and we didn't have the code in git at the time - but it makes sense to me and might help anyone who feels like digging into it further.

**Comment by Finaldeath** [comment]
It would be useful functionality, I need to test compounded damage flags but I don't have great hopes and Bioware code never uses them

**Comment by Shad000w** [comment]
> 
> 
> It would be useful functionality, I need to test compounded damage flags but I don't have great hopes and Bioware code never uses them

As I wrote before: Most of the functions that uses DAMAGE_TYPE_* parameter allows their chaining.

With that I meant componding.

You can use it with EffectDamageIncrease, EffectDamageShield, EffectDamage. At least with the physical damages - slashing piercing bludgeoning it works and I am using it for years.

**Comment by Finaldeath** [comment]
You can't for EffectDamage, I tested it recently; https://nwnlexicon.com/index.php?title=EffectDamage

I've not tested some of the others.

As I noted there doing: EffectDamage(10, DAMAGE_TYPE_BLUDGEONING | DAMAGE_TYPE_PIERCING); doesn't apply more than one (it does the highest numeric DAMAGE_TYPE_* value if you wondered, in this case DAMAGE_TYPE_PIERCING).

I could do with some test code where you show it actually does work as you imply.

**Comment by Finaldeath** [comment]
Okay I've found the source of the issue after some testing, anything with an integer value of over 2048 for the nDamageType value gets changed back to DAMAGE_TYPE_MAGICAL. I can't replicate anything else here however about sonic magically being resisted even though it's not specified.

**Comment by Finaldeath** [comment]
Notes here: https://nwnlexicon.com/index.php?title=EffectDamageResistance

**Comment by Finaldeath** [comment]
Fixed in 36, up to the max value of damage which is reset to magical so just don't use the last value and you are fine.
