### ISSUE TITLE
[8193.14 dacbed80 - 3 Jul 2020] Toolset Rendering Issues & Crashes

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#108]
**To Reproduce**

 - Open the toolset.
 - Open any area.
 - Transparent parts of textures are rendering as "chrome"

 - Open the toolset.
 - Open any area.
 - Click on anything in the Placeables or Creatures Standard Palettes.
 - Toolset crashes with this error:

![Crash](https://user-images.githubusercontent.com/58920224/86531421-044d5880-be8f-11ea-9808-0c127055b388.jpg)

**Specifics**

 - Game Build 8193.14 dacbed80 - 3 Jul 2020

**Comment by pstemarie** [comment]
The NWNEE channel on the Vault Discord server has numerous other reports of these issues from nVidia, AMD, and Linux users. There are also some other screenshot from other people.

**Comment by FrogsOfDoom** [comment]
I can confirm this. NVIDIA GEFORCE GTX 960M video card.
