### ISSUE TITLE
Water is opaque for creatures and placeables in it, and items appear on top (unlike 1.69)

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#111]
**To Reproduce**

- Load an area with knee-height water (easiest is the Forest tileset with some streams/rivers added, which are deep enough to notice this)
- Walk into it and see your legs disappear, items appear on the water and placeables appearing below it and invisible.

**Specifics**

 - OS Windows
 - Game build 80.9193.14 [2025cd2f]
 - Distro platform Steam
 - Content overrides? None

You can see my legs are cut off in the first screenshot:

![image](https://user-images.githubusercontent.com/6137144/86973930-49160f80-c16d-11ea-91c4-b104f16f703d.png)

Items are placed *on top* of the water for some reason when dropped (in 1.69 they are properly placed at the creatures feet):

![image](https://user-images.githubusercontent.com/6137144/86973958-57fcc200-c16d-11ea-8163-04d79d33b51c.png)

Placeables (such as "remains") are created in their proper location but are invisible except using Tab and carefully clicking:

![image](https://user-images.githubusercontent.com/6137144/86973987-6814a180-c16d-11ea-8c1f-0e6fc6bdfa86.png)

Example of what should happen in 1.69:

![image](https://user-images.githubusercontent.com/6137144/86974074-92fef580-c16d-11ea-87e1-e7d918a0f260.png)

Same area in EE (but not the same preview build) with the player emoting "sit":

![image](https://user-images.githubusercontent.com/6137144/86974120-a5792f00-c16d-11ea-9f18-7ca349d62191.png)

**Comment by niv** [comment]
Are you sure items dropped underneath the water line back in 1.69?

**Comment by Finaldeath** [comment]
Example of water dropped items (Shiny/not shiny water), torch is hard to see since I'm not holding tab (Bottom of image):

![image](https://user-images.githubusercontent.com/6137144/88674790-262ea980-d0e2-11ea-9403-1724b240a006.png)

![image](https://user-images.githubusercontent.com/6137144/88674809-2c248a80-d0e2-11ea-89ed-0d56a2a1a26e.png)

EE latest preview where item still on water (but you can see feet now, score!):

![image](https://user-images.githubusercontent.com/6137144/88675113-80c80580-d0e2-11ea-88f1-dcf5a3be269f.png)

Placeables from, eg, remains work correctly in both 1.69 and EE (both go on the bed of the stream).
