### ISSUE TITLE
Module crashes when merging updated content

### ISSUE THREAD

**Issue by Choad77** [Beamdog/nwn-issues#112]
![image](https://user-images.githubusercontent.com/68121842/87178811-c051bd80-c2ab-11ea-9c6d-2d17dc8b20e4.png)

**Comment by Choad77** [comment]
Anyone help here?  I create content in windows 7, then we import the updated content into the linux server. When doing so the error report above happens and it crashes.

**Comment by niv** [comment]
This is a nwnx issue. Report with them.

**Comment by niv** [comment]
-> https://github.com/nwnxee/unified/issues
