### ISSUE TITLE
SetTextureOverride delay when used in OnActivate script

### ISSUE THREAD

**Issue by Batrachophreno** [Beamdog/nwn-issues#114]
**To Reproduce**

(Module to reproduce: https://www.dropbox.com/s/kusqosapv1p41k7/SetTextureOverride_Issue.mod?dl=0 )
 - Launch SetTextureOverride_Issue.mod (as player or DM):
 - Pick up TextureSwap item on ground and use it. (any Unique Power Self-Only will work though)
 - Texture should switch out instantly, but most of the time there will be a long delay where no texture displays.
 - Opening a menu (inventory screen, character screen) will cause the new texture to load (I think).

**Specifics**

 - Windows 10 Pro
 - 8193.13 [3ba0f825]
 - Steam
 - No content overrides, haks, etc.

**Description/Example**

The expected behavior (which occurred twice while testing the repro module) would be that the texture switches seamlessly. The other three times, the new texture did not appear after the old texture 'unloaded/disappeared/whatever.' Opening a UI menu seems to cause the new texture to appear.

Video: https://imgur.com/a/fZMIN53

**Comment by Finaldeath** [comment]
For later reference: [SetTextureOverride_Issue.zip](https://github.com/Beamdog/nwn-issues/files/11996302/SetTextureOverride_Issue.zip)

This appears to have been fixed since 2020, there were several bugs with texture overrides of various kinds. If it is still an issue let us know.
