### ISSUE TITLE
[8193.14 - 9 July] dungeon lava tile with misaligned lava tde01_a08_01

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#117]
**Description**

There is a seam related to tile tde01_08_01 's lava texture with neighboring tiles.  It's not super-obvious in game, unless looking for it; I noted it when cloning the lava terrain to make something else. 

Screenies:

BW Lava terrain, tile tde01_a08_01
![image](https://user-images.githubusercontent.com/38797333/87276634-5ea97300-c4a6-11ea-8c4d-53338caf1a0b.png)

Reskinned lava to use forest water texture (no wok, so I can walk on it):
![image](https://user-images.githubusercontent.com/38797333/87276757-9c0e0080-c4a6-11ea-9625-d6942e4df4dc.png)

**To Reproduce**

 - Lay out a big swath of lava in the toolset in the dungeon (tde01) tileset.  It's easier to spot the issue zooming in in the tileset than in game, tbh, as you can get closer.

**Specifics**

 - Game build (e.g. 8193.14 previewpreview July 9, or commit hash)
 - OS (Windows)
 - Distro platform (Steam, previewpreview)
 - Content overrides?  None - I'm just cloning lava for other stuff

**Local fix**
I fixed it with minor edits in a text editor to this node (updated the z-coord for verts and position):

```
node trimesh TDmesh361
  parent tde01_A08_01a
  #part-number 3
  ambient 1 1 1
  diffuse 1 1 1
  specular 0 0 0
  shininess 1
  shadow 0
  rotatetexture 1
  bitmap tde01_lava01
  verts 4
    -5 5 0
    -5 -5 0
    5 5 0
    5 -5 0
  tverts 4
    -3.57628005e-006 -14 0
    -4.05311994e-006 -16 0
    2 -14 0
    2 -16 0
  faces 2
    0 1 2 1 0 1 2 1
    3 2 1 1 3 2 1 1
  position 0 0 -1
  orientation 0 0 0 0
  alpha 1
  scale 1
  selfillumcolor 1 1 1
endnode
```

**Comment by Bill-Harper** [comment]
The vertices were off by 0.382 cm on all sides. This doesn't sound like much, but even 0.01cm can show a buzz-line or full seam under certain conditions.

**Comment by shadguy** [comment]
Closed with the July 24, 2020 preview build.
-Dave
