### ISSUE TITLE
Area music stops playing when opening a modal window

### ISSUE THREAD

**Issue by Daztek** [Beamdog/nwn-issues#12]
**To Reproduce**

 - Open an area and enable its music
 - Open the script editor or a creature/placeable properties window
 - The music stops playing

**Specifics**

- OS: Windows 10
- Game build: 8193.9

The area's ambient sound and placed sound object do keep playing.

*Sometimes* the music keeps playing in the script editor until you close it or open another script in a different tab.

**Comment by virusman** [comment]
@Daztek Is this a regression? How was it in 1.69?

**Comment by Daztek** [comment]
I believe it also kept playing in some of the early builds of EE. I would double check but unfortunately Steam only lets me go back to 8186 and later builds. 

In 1.69 the music just keeps playing regardless of opening a modal window.

**Comment by Daztek** [comment]
Fixed in 8193.36-1!
