### ISSUE TITLE
Preview DM possession is drastically different to previous stable

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#120]
**To Reproduce**

 - Load attached module for easier debugging: [Test_DM_Mode.zip](https://github.com/Beamdog/nwn-issues/files/4915491/Test_DM_Mode.zip)
 - Watch the debug (the creatures can, like previous stable, not detect the DM in the list of objects in the area/nearest creature/nearest PC - my note about "may/should include DMs" is wrong :) ) - if you're a PC you will show up in nearest PC etc. however.
 - Possess a creature (doesn't matter if full or partial) (if PC, sudo up to DM mode)
 - Watch debug output - see below for what happens in previous stable versus what happens now. The creature in preview essentially disappears from area object lists and is marked as a DM object (with GetIsDM being true), and in the DM faction it seems (neutral to all creatures). Old stable and all previous versions of the game the creature was possessed retaining it's faction, it isn't marked as a full DM and appears properly in object lists.

This essentially means a DM can't fight as a NPC, and while it might be a nice as an optional mode in some circumstances (allowing you to halt the NPC being fought, by pretty much everything AI based since they "disappear") it's 100% different to previous behaviour.

**Specifics**

 - OS Windows
 - Game build 80.8193.14 (74ec17e7)
 - Distro platform Steam preview 
 - Content overrides? Not relevant

**If needed, describe the bug**

Previous stable shows this which correctly still identifies the "defender" creature as being an enemy, present, and nearest creature/in the area creature list (as well as it being DM possessed but NOT "is a DM" fully):

![oldstable](https://user-images.githubusercontent.com/6137144/87359257-595c2f00-c55f-11ea-8b45-6015554a503f.PNG)

New preview (which happens if DM possess as a sudo'ed PC, or a usual DM) is massively different, the creature now disappears (even if it is still "seen") from the relevant area object list and nearest creature checks, and GetIsDM() now returns TRUE and the faction is neutral (most likely is the DM's faction).

![preview](https://user-images.githubusercontent.com/6137144/87359790-75ac9b80-c560-11ea-9aad-f25f57e909c3.PNG)

NOTE: the creature can still be attacked and damaged, so isn't automatically set as plot, and it still is findable by GetObjectByTag().

I added in a HB script for the player, in case anytime you want to test it with 2 DMs or players sudoing to DM mode.

**Comment by niv** [comment]
Thanks for the excellent bug report! Repro'ed.
