### ISSUE TITLE
[8193.14 - 9 July] dungeon bridge door tile texture mismatch tde01_h07_01

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#122]
**Description**

A texture under the bridge does not match other bridge tiles, and is jarring when noticed.  Issue is inherited from v1.69/Bioware.

Picture from toolset:

![image](https://user-images.githubusercontent.com/38797333/87503080-e4edc280-c628-11ea-989b-7c3347c5a286.png)

Note that I also crash when trying to place this tile in NWNEE toolset.  To confirm the issue in EE still exists, I have to build in v1.69 then load in EE, or use nwnexplorer.

**To Reproduce**

- Make a dungeon area [tde01]
- Make lava
- Place a Feature\Bridge Door in the lava
- look at your bridge door tile from the side

**Specifics**

 - Game build (e.g. 8193.14, July 9 preview preview)
 - OS (Windows)
 - Distro platform (Steam)
 - New naked module no overrides

**Comment by shadguy** [comment]
Note: the subsequent July 15 previewpreview .14 build has fixed my toolset crash when selecting the BridgeDoor tile.

-Dave

**Comment by Bill-Harper** [comment]
![lava_bridge_wall_spout](https://user-images.githubusercontent.com/53191846/88194129-71d9e280-cc0c-11ea-9f10-75afd4fd8a5e.png)

A texture reassignment as well as some basic UV work. While there I added a lava spout on either side for added effect.

**Comment by shadguy** [comment]
Lookin' good!

**Comment by shadguy** [comment]
Closed both the art issue and the toolset crash with the July 24, 2020 preview build.
-Dave
