### ISSUE TITLE
[Preview - 3e2b9d99] SqlDestroyDatabase(GetModule()); irrevocably destroys the module database.

### ISSUE THREAD

**Issue by Daztek** [Beamdog/nwn-issues#123]
**To Reproduce**

 - Call `SqlDestroyDatabase(GetModule());` to reset the module database.
 - Try to create a new table `sqlquery sqlQuery = SqlPrepareQueryObject(GetModule(), "CREATE TABLE test (foo TEXT)");` `SqlStep(sqlQuery);`
 - `SqlGetError(sqlQuery)` returns `no such database (code=1, db=, script=Chunk, query=)`

**Specifics**

 - OS: Windows
 - Game build: Preview [3e2b9d99]
 - Distro platform: Steam
 - Content overrides? None

**If needed, describe the bug**

It does recreate the database when using a player.

**Comment by niv** [comment]
Oopsie.
