### ISSUE TITLE
Pathfinding stacking creatures in combat [8193.10+ including current preview]

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#124]
**To Reproduce**

 - Load a blank module in DM mode (or any module with some space for larger creatures)
 - Spawn in a Purple Dragon Blade who is then made immortal (Defender faction, our "Human test subject")
 - Spawn in dozens of Adult Blue Dragons (black ones cast darkness which is annoying) (Hostile faction, they attack our test subject)
 - See the AI monsters illegally swamp the poor dragon knight like the pictures below. Usually about 4, maybe 5 max should without overlaps. Instead you can get dozens of them to overlap attacking them.

Testing the same scenario in 8193.9 seems to function correctly. This was the last patch before new pathfinding was added - coincidence? I think not! Disabling "new pathfinding" config on .10 doesn't seem to fix it however...

**Specifics**

 - OS Windows
 - Game build 8193.14 [5358bc89] and 8193.13 [3ba0f825] stable are the same (broken) as 8193.10 which it seems to first occur in. Tested 8193.7.9 it worked as it should.
 - Distro platform Steam
 - Content overrides? None in use

**If needed, describe the bug**

Screenshots speak a thousand words. 8193.9 (no new pathfinder setting available) correct behaviour. They're all mostly standing there...menacingly waiting their turn! 4 are attacking the purple human (Sometimes a 5th squeezes in).

![image](https://user-images.githubusercontent.com/6137144/87832656-6be7a880-c87e-11ea-9326-e018f247cdab.png)

8193.10 with enhanced pathfinding explicitly disabled it started to occur:

![image](https://user-images.githubusercontent.com/6137144/87832507-11e6e300-c87e-11ea-9e42-9839e9b247dc.png)

8193.14 [5358bc89] with enhanced pathfinding is the same, there's like 30 dragons here, all taking a shot at the poor purple human.

![image](https://user-images.githubusercontent.com/6137144/87831597-dfd48180-c87b-11ea-81c7-f2715c4eb7c3.png)

I can try testing some more versions of the game but it's probably not worthwhile since it's easy to find it working in .9 and not working in .10, .13 or .14.

A test module can be setup with a ton of defender dragons and a single hostile (but immortal) blank AI human in the middle, so the player isn't affected, but it's easier to do this in DM mode tbh.

**Later edit:** This is likely due to some kind of "in melee combat, now ignore our personal space size" or something, since of course creatures do get blocked as usual by other normal means (eg; placeables, doors, other creatures in the way when trying to move into melee range, or out of combat just any kind of mess when pathfinding and something blocks you). personal space column in appearance.2da being ignored in that situation perhaps? ie: turned off when in melee?

**Comment by eveferon** [comment]
Issue is confirmed. Both creatures and players appear to have something that resembles EffectCutsceneGhost(). With that, neither the player, nor creatures can be trapped as their sizes are not respected as they should. Here, how it looks with 30 Giants attacking a player at the same time.
![Mob intersection](https://user-images.githubusercontent.com/4124903/87833503-48c1f680-c888-11ea-9057-b5ed47aa9510.png)

**Comment by eveferon** [comment]
That does not affect every creature. It can be the case only with creatures of a larger sizes. 
<img width="739" alt="Screenshot 2020-07-18 at 00 14 27" src="https://user-images.githubusercontent.com/4124903/87834827-ab68c180-c88b-11ea-9a0f-321ef7c5621e.png">

**Comment by Soren217** [comment]
Found the cause. Thanks for being thorough!

**Comment by Finaldeath** [comment]
Thank you Soren, really helpful getting this fixed, was an odd one (and rare - huge monsters are not commonly used in packs of 20) for sure.
