### ISSUE TITLE
[8193.14] Toolset disallows legit weaponry from being equiped by some creature models

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#129]
**To Reproduce**

 - Create a new module in the toolset
 - Instantiate a Formian Warrior
 - Use the Level-up Wizard to give the Warrior 1 Fighter level (for weapon proficiency feats)
 - Edit the Formian and try to equip a Shortbow; this works no problem
 - Now try to equip a longbow; the Toolset blocks this update.  It should not.

**Specifics**

 - Game build (e.g. 8193.14, 24 July 2020 build).  The bug is inherited from v1.69/Bioware.

**If needed, describe the bug**

We should be able to use the toolset to equip a longbow for a Formian with the appropriate feats, per above.  Formians are correctly set as SizeCateogry 3 (medium), in appearance.2da.  Longbows are WeaponSize 4 (Large) in baseitems.2da, so they should be useable 2-handed by Formians with the appropriate feats.

I've attached  a module with three formians pre-placed.  

- The first has a shortbow, equipped no problem.  It uses the bow in game if you run the mod and attack.
- The second has a longbow in inventory, but cannot equip it.  It punches in game, rather than equip the bow (default ai).
- The third was hacked to equip the longbow.  It uses the bow in game if you run the mod and attack

[Formian Equipment Test.zip](https://github.com/Beamdog/nwn-issues/files/4986494/Formian.Equipment.Test.zip)
 

**Conclusion**: toolset logic for allowable equip-able items, when editing a creature blueprint, is not aligned with the game for this case.  

-Dave

**Comment by Finaldeath** [comment]
If the second example isn't working it might also be a bug with EquipMostDamagingRanged() unless Bioware AI decides to only do melee on them for some reason.

**Comment by Finaldeath** [comment]
Toolset only issue it seems. I tried the mod and reproduced it with the default AI but a simple HB script to call ActionEquipMostDamagingRanged() works as it should, meaning the item Longbow is equipped. I also added an unequipped shortbow variant (Who also melee attacks using the default AI, how dumb! ;) ).

100% weird in the toolset for some reason!

![image](https://user-images.githubusercontent.com/6137144/88680139-0f8b5100-d0e8-11ea-9a2b-952814dc5aa2.png)

Attached an updated version:

[Formian Equipment Test.zip](https://github.com/Beamdog/nwn-issues/files/4988960/Formian.Equipment.Test.zip)

**Comment by shadguy** [comment]
Jasperre - agreed.  That is why I filed the issue specifically against the toolset.  I showed my builder how to hack the thing to get what he wanted, but people shouldn't have to workaround or script around the issue. 

I'm told there's a similar issue sometimes with shields, though specifics are not available to our aging grey matter.  I'll post any shield-related details if they come up, but my build guy thinks it's the same issue under the hood, essentially.

-Dave

**Comment by virusman** [comment]
There is a check specifically for creatures with model type = Limited (there are part-based, full and limited models).
When equipping an item into the right hand, and if the left hand is free, it doesn't allow weapons larger than 'medium'.

**Comment by virusman** [comment]
I'm not exactly sure why, but it might have something to do with animations or 'Limited' creatures not being able to use large weapons. Just my guess.

**Comment by Finaldeath** [comment]
Weird because in game this works fine, whereas some creatures (eg; Giants, Trolls) can wield (and be equipped in the toolset) longbows but 100% do not fire them right. I might try formians with two handed swords sometime...

It might be worth matching the toolset functionality to the game functionality, but of course I'm happy to point to my Fancy New AI(TM) to fix the AI not equipping them :D

**Comment by shadguy** [comment]
I poked through some of the Limited models - some giants, formians, stinger, driders - and the list of animations available varies.  I guess the toolset needs to make some sort of assumption about what is available in common somewhere.  Victor, if you want to close this and mark it "Will Not Fix", I think that's fine.  Thanks for taking a look!

For posterity: a toolset workaround is to change the creature appearance to human (for example), equip the bow, and then back to formian (or whatever you're building).

-Dave

**Comment by Finaldeath** [comment]
NIce workaround I'll add it to the nwn.wiki, and also GFF editing works.

Really weird Bioware code, hah.

**Comment by shadguy** [comment]
Closing.  We have a workaround, and there are more interesting things for Victor to spend time on.

-Dave
