### ISSUE TITLE
Doors on area edges in Mines & Caverns tileset don't work

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#13]
The Door tile, when placed against the edge of an area created with the Mines and Caverns tileset, doesn't work. People can transition to that area transition but if they click on it to transition back, nothing happens. This seems to only occur in the Mines and Caverns tileset (or one of its CEP variants when using haks) using the "Area Transition (No Visible Door)" "door".

To recreate, do the following:
1) Create a new area using Mines and Caverns tileset
2) Place a Door (Paint Terrain -> Terrain -> Door) against the edge of the area
3) Add an Area Transition (No Visible Door) to that door frame
4) Set up an area transition with any other transition

It was first reported on our Persistent World and I recreated it using a blank new module with no scripts or custom content. I've attached my test module to this issue and here's the link to the post where players reported it on our forums:
https://www.nwnravenloft.com/forum/index.php?topic=53827.0

[Broken Area Transitions.zip](https://github.com/Beamdog/nwn-issues/files/4378214/Broken.Area.Transitions.zip)

OS: Client: Windows, Server: Linux
Game build: 8193.9
Distro platform: Steam

**Comment by niv** [comment]
Thanks for the report, will be in .10

**Comment by FrogsOfDoom** [comment]
This also affects the Barrows tileset.

**Comment by niv** [comment]
Yep, it's the generic door/crosser model, tn_gdoor....
