### ISSUE TITLE
[8193.13] Mines and Caverns Tileset - Platform 2 2x2 - Animation Loop 1 Check Box Does Not Inactivate Animation

### ISSUE THREAD

**Issue by Clockwerkd** [Beamdog/nwn-issues#131]
**To Reproduce:**

1. Create a new area using the Mines and Caverns Tileset and place the starting location in this area.
2. Place the Platform 2 2x2 group feature.
3. Select the feature and access the tile feature properties.
4. Deselect the Animation Loop 1 check box.
5. Save the module and enter a game using Build Module.
6. The group feature animation still plays.

**Specifics:**

- Windows 10 Pro 2004
- Game version 8193.13

**Comment by Bill-Harper** [comment]
![mining_platform2_animloop01](https://user-images.githubusercontent.com/53191846/91057692-8d624f80-e5f5-11ea-99ab-ac431976e35d.png)
tdm01_t11_01 had an animloop01, but it was never set up right. Had keys, but they matched the default value at frame 0. This caused the behavior you noted.

I now have both of the animated tiles so they can be turned off at will. tdm_s10_01 never had an animloop01, but does now. While there I added a little extra glow and dim to the lava meshes. They had self-illum already set, but was a constant value--now it fluctuates a little (subtle).

**Comment by Clockwerkd** [comment]
Thanks, Bill! This is wonderful news. Really appreciate you addressing this issue!

**Comment by Clockwerkd** [comment]
Hi, Bill. I just updated to .16 and am finding that the new toggles do work to turn the animations on. Thank you for that! However, when unselecting the animation loop box, the animations continue and do not turn off. This is within the toolset. I haven't checked to see if the animations still appear while in game.

**Comment by Bill-Harper** [comment]
Thanks for letting me know. I've found that many don't update in the toolset once re-checked, but work fine in game. If you find it still doesn't work in-game, please let me know and I'll re-apply the wrench. :)

**Comment by Clockwerkd** [comment]
Looks like it does work in game. Thanks, Bill.
