### ISSUE TITLE
GetResRef returns a case sensitive results in EE compared to lower case only in 1.69 when using CreateObject()

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#132]
**To Reproduce**

- Run attached module and talk to the dwarf [GetResRef Error.zip](https://github.com/Beamdog/nwn-issues/files/5012303/GetResRef.Error.zip)
- Create nw_chicken - this in 1.69 returns "nw_chicken" as the resref, and in EE returns "nw_chicken"
- Create nW_chicken - this in 1.69 returns "nw_chicken" as the resref, and in EE returns "nW_chicken"

The behaviour of GetResRef was in 1.69 to return the lower case version (matching the template filename, which appears to be the intent, since toolset hardcodes resref names to lowercase usually) while in EE it returns whatever was input into CreateObject(), which can cause errors if it is expected GetResRef is always lowercase.

I did not test having a template file which had upper case letters in it, since I am guessing upper case letters in .utc files isn't recommended anyway (even if supported somewhat).

**Specifics**

 - OS Windows (Siala and Daz tested it on Linux too however)
 - Game build 1.69 and 8193.14 [126f327c]
 - Distro platform 1.69 - GOG, EE - Steam
 - Content overrides? None

**If needed, describe the bug**

Screenshot of 1.69:

![image](https://user-images.githubusercontent.com/6137144/89125347-b2bbdc00-d4d5-11ea-8879-dbbdbfb05fa9.png)

![image](https://user-images.githubusercontent.com/6137144/89125372-d67f2200-d4d5-11ea-913a-0219bf1a689f.png)

**Comment by jd28** [comment]
Just to add on to this: According to the original bioware docs, viz Gff & Erf: "(C)ResRef is the name of the file with no null terminator and in lower case. A ResRef can only contain alphanumeric characters or underscores."  So no upper/mixed-case resref should ever exist.  Side note: the latter invariant of alphanums and underscore also seems to have been changed, there are files in nwn_base.key that do not adhere to that convention.

**Comment by eveferon** [comment]
Clippy made some important comments to redress vs. vile names. I will add them here.

> Do not think of GetResRef() as returning the filename. It is returning whatever you specified with CreateObject, possibly forced to lowercase. There is a concept of resman aliases. So the filename and 'whatever you asked' can be different. [...] Because this has nothing to do with files. When you CreateObject(), it finds the file correctly, but then it will also store the template/resref you used in a field. And when you ask for it, it will give you the value you specified, not the name of the file it loaded it from.

According to him, it appears nothing to be changed from 1.69 to EE that would cause that. He added 

> Bigger issue is what changed since 1.69. Because it's not this (some changes in case handling). It's something different that has a weird side effect. There is no ToLower() or similar call in 1.69 that was removed.

**Comment by Finaldeath** [comment]
I'd strongly suggest GetResRef is reverted to 1.69 and "logical" lowercase regardless, just in case any mod relies on it and breaks (which is how someone noticed it in the first place :) ).

**Comment by niv** [comment]
Nothing so nefarious.  My guess, this is just a regression from making resman directories work on case-sensitive file systems. It'll probably be a trivial fix.
