### ISSUE TITLE
Walkable invisible ramp on Ship Floating 2x2, Rural

### ISSUE THREAD

**Issue by b5635** [Beamdog/nwn-issues#133]
**Description**

There appears to be a walkmesh that shouldn't be there to the right side of a Ship Floating 2x2 in Rural. Does not happen with City Exterior, Ship Floating 1x2.

![walktheplank](https://user-images.githubusercontent.com/15935426/89333846-6e058180-d64a-11ea-8a13-972a54152eeb.png)

**To Reproduce**

 - Create a 4x4 Rural Area.
 - Fill it with water and place Ship Floating 2x2.
 - Test module.
 - Walk into where a ramp may be, on the right side of the ship. See screenshot.

**Specifics**

 - 8193.13
 - Windows
 - Steam
 - None

**Comment by mtijanic** [comment]
I always though this was so you could add plank placeables and make the ship boardable. I'm l expect someone is already making use if it as a feature.

**Comment by tinygiant98** [comment]
Expected behavior.
