### ISSUE TITLE
Setting "Hide Secondary Story Tiles = TRUE" resets to FALSE in each new game session

### ISSUE THREAD

**Issue by eveferon** [Beamdog/nwn-issues#137]
**To Reproduce**

- Enter any module
- Select Game Options -> Hide Secondary Story Tiles = Always
- Quit game
- Enter any module (the setting is reseted yet **Always** is shown requiring the setting to be reapplied.

**Specifics**

 - Windows and Mac (Probably OS independent)
 - Game build 8193.13
 - Steam and GOG
 - No

**If needed, describe the bug**

The screenshot shows how it looks like. The second story should be hidden after reentering the game but is displayed although the setting Always is active.

<img width="1311" alt="Screenshot 2020-08-07 at 17 17 11" src="https://user-images.githubusercontent.com/4124903/89660636-e5991200-d8d1-11ea-9e53-4db077970bcf.png">

**Comment by niv** [comment]
This shouldn't be an issue anymore on the latest dev patch. Feel free to reopen if you find it still manifests when testing against that.
