### ISSUE TITLE
Toolset "Area Statistics" access violation error in areas with water [Development 8193.14]

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#139]
**To Reproduce**

 - Create a module, with a new area using tileset "Castle Exterior, Rural" or "Rural" (or any tileset with water?)
 - Place down some sea cliff water on castle exterior, or on usual rural, some water.
 - Build -> Area Statistics menu option
 - Access violation occurs

**Specifics**

 - Game build both 8193.13 (3ba0f825) and 8193.14 [0caab8c0]. Didn't test any older versions.
 - Regression? None - this happens in 1.69 as well with the same tileset.

**If needed, describe the bug**

What should happen:

![image](https://user-images.githubusercontent.com/6137144/89742424-b92bf400-da91-11ea-92f2-0fa842c3e803.png)

Violation:

![image](https://user-images.githubusercontent.com/6137144/89742433-d365d200-da91-11ea-9388-a8ec0fcefba6.png)

PS: This little used feature so not exactly the world it's broken. I am guessing it just shows "what estimated memory an area will take up when run in-game" currently, would be cool to expand a little to be more useful (if the toolset loaded the highest quality textures/replicated shaders as per game and could show other "this amount of stuff is crazy" amounts hehe).

**Comment by virusman** [comment]
Thanks for the report @Finaldeath! I've reproduced the crash and prepared a fix.
