### ISSUE TITLE
VFX are applied again, and again, and again when going in and out of perception range stacking a lot

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#140]
**To Reproduce**

 - Load module: 
[Jasperre Test VFX.zip](https://github.com/Beamdog/nwn-issues/files/5063430/Jasperre.Test.VFX.zip)
 - VFX of Bigbys hands will apply to all barrels
 - Walk the length of the barrels and back again
 - VFX start to apply again, and again, and again...

**Specifics**

 - OS Windows
 - Game build 80.8193.14 [0caab8c0]
 - Distro platform Steam
 - Content overrides? None
 - Regression? None - seems to be a bug from 1.69 days

**If needed, describe the bug**

Screenshot of it in action - top one has been seen twice (two overlapping hands) middle 3 times (a cluster of hands) bottom one only once (intended amount of hands).

![image](https://user-images.githubusercontent.com/6137144/90028657-ddfeb200-dcb1-11ea-8a6c-3b3060ea1176.png)

Yes of course this causes a drop in FPS and doing it too often probably would grind your game to a crawl :)

**Comment by merricksdad** [comment]
Same here

Bug also affects visual effects applied to objects outside of visual range. When you get to the object one is applied to, sometimes it has two copies. Sometimes it does not. This appears to occur about 25% of the time in my testing.

Bug also disallows removing visual effect appearance on client. If effects on the object are all removed, and then counted, the count will say 0, but the visual is still applied.

[Bugged VFX onEnter.zip](https://github.com/Beamdog/nwn-issues/files/7672276/Bugged.VFX.onEnter.zip)
