### ISSUE TITLE
[8193.14 Development] Sea ship tileset ERROR

### ISSUE THREAD

**Issue by LiarisFreeze** [Beamdog/nwn-issues#142]
Create module with tileset Sea ship
Ship ---> Castel ---> None ---> Boat1 and draw in area ---- > ERROR!

OS: Windows 7
Steam
Content overrides? (No)

![er1](https://user-images.githubusercontent.com/46865150/90222463-c3911980-de14-11ea-8f13-de921a42bc7c.jpg)

**Comment by Bill-Harper** [comment]
Thanks for the report! I found the issue not only in this group but in Boat 6 (none) and lifeboat2---across all 4 waters. Something happened in the animmesh settings; replacing them with settings from a valid wavy water fixed them up for me.
