### ISSUE TITLE
Missing Bodyparts on Creatures (Graphics/rendering issue, reproducable)

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#145]
**To Reproduce**

 - Load attached module: 
[Jasperre Test Bodypart Swaps.zip](https://github.com/Beamdog/nwn-issues/files/5092339/Jasperre.Test.Bodypart.Swaps.zip)

 - Spawn hundreds of dwarfs (may need 500+) each pull of the lever spawns around 100 at once
 - See some of the dwarfs start to not load in body parts. This is likely to happen on the last spawned ones.

**Specifics**

 - OS Windows 10 (16GB RAM, GeForce 960M, i7 processor, latest drivers)
 - Game build 80.8193.14 [0caab8c0]
 - Distro platform Steam
 - Content overrides? None
 - Regression? This would happen on 1.69 too most likely

**If needed, describe the bug**

While this bug does randomly happen in the game regardless of creature spawn count, this is at least a reproducable way of it happening. 500+ models is not normal but it does at least prove the model can be in memory fine for other creatures. 

![image](https://user-images.githubusercontent.com/6137144/90554542-f4af7800-e18d-11ea-8964-051594e33184.png)

Note that you can check the description to see the settings used (if blank it's because it's not run on spawn yet be patient) and therefore you can see if it matches existing ones.

![image](https://user-images.githubusercontent.com/6137144/90554720-2f191500-e18e-11ea-80cc-7ebbd9c4deba.png)

I can provide a mod version which does the same for the other races (thanks to BunnyMoreau), but works on Dwarfs so why not.

**Comment by Finaldeath** [comment]
a PS on this, it can sometimes fail to load the entire model. Bird on nwnx channel suggests the core model not loading may cause this. It's easier (if using the module above) to be in DM mode so you can walk through things. Or apply cutscene ghost. You can find spots a creature may not load as a blank one, zoom in and press tab to see the ID of them.

![image](https://user-images.githubusercontent.com/6137144/91881032-cbf0ad80-ec78-11ea-8402-aeb3ee739da4.png)

**Comment by Finaldeath** [comment]
Made a version with Orcs spawning and it has a good example of not loading the entire model which people randomly report:

[Jasperre Test Bodypart Swaps 2.zip](https://github.com/Beamdog/nwn-issues/files/5157677/Jasperre.Test.Bodypart.Swaps.2.zip)

![image](https://user-images.githubusercontent.com/6137144/91881949-30f8d300-ec7a-11ea-99e1-cda8af5c4937.png)

This is on the latest preview - ae524e6b.

At least I can reproduce the entire model going (But the client knowing about it via. the tab -> nameplate).

**Comment by eveferon** [comment]
Confirming the issue. In our case, the entire models disappearance (like in two last screenshots) is a more common issue.

**Comment by Lokey7** [comment]
Repro mod with fewer changes and much lower number of spawns that is hopefully easier to diagnose. Created mod fresh in EE 8193.13, cleaned out a lot of things for this version (I'm .16 steam, no workshop, nothing in override to affect appearances, models or textures of what's here). Two areas of mostly bare tiles, a chat script, a creature to spawn with a spawn in script and an area enter script to tell you what to do.

Can repro 100% within a few tries with player, have gotten versions to disappear on dm too but did not try here. Any pc is fine, true seeing items will disable blind fix (blind for one sec to force reload of visuals). Suspect change to creature equip might fix if it's a visible thing, didn't try that here.

Chat commands are /dwarf to spawn some dwarves that display either part fail to load or whole model doesn't load based on random chance of creature part change (nothing to select, tab will show name or clothes but no head/arms and name will change to show what was done to npc). /clear gets rid of npcs with tag dwarf. /blind applies EffectBlindness() to pc chatting for 1 sec.

Any clarification needed, I'm sure Jasparre will tell me.

![Screenshot_20201016_113007](https://user-images.githubusercontent.com/66321574/96281546-7ada1600-0fa7-11eb-8bad-e46d7d40e99e.png)

[DisappearRepro1.zip](https://github.com/Beamdog/nwn-issues/files/5392890/DisappearRepro1.zip)

**Comment by eveferon** [comment]
Also noticed on iOS mobile version that models of items disappear especially when server restarted and client is reloging without reopening the application. I am not sure how much it is connected but just in case.
