### ISSUE TITLE
Seemingly random VFX or tileset tiles appearing on creature death

### ISSUE THREAD

**Issue by summonFox** [Beamdog/nwn-issues#146]
**To Reproduce**

 - Load the Neverwinter Nights Prelude module
 - Spawn creatures from the standard palette. I used Commoner, Male.
 - Kill said creatures
 - Repeat ad-infinitum until seemingly random VFX or even tileset tiles that persist begin appearing when the creatures die.

**Specifics**

 - OS (Windows, Mac, Linux)
 Windows 10 64bit
 - Game build (e.g. 8193.8, or commit hash)
 1.81.8193.15 f9fcfcb0
 - Distro platform (BDC, Steam, GOG)
 Steam
 - Content overrides? (Steam Workshop? Overrides? Patch haks?)
 No custom content installed

**If needed, describe the bug**

Seemingly random VFX or tileset tiles appear on creatures deaths. I first noticed this bug in one of the .14 preview builds, but don't remember which. It is present in the current .14 development build [0caab8c0] and .15 preview build [f9fcfcb0]. I have heard other players on the .14 development build are also experiencing the same bug on the Cormyr and the Dalelands server.

Sometimes you have to spawn a few hundred creatures until the bug starts occurring. Sometimes it'll start with the first creature. 
I have seen things range from darkness vfx, to hellball vfx, to even tileset tile models that persist and do not disappear even after transitioning areas.

Here are some videos of the bug occurring in the Prelude after fresh game client restarts with no custom content installed.

https://gfycat.com/hilarioussimplisticdairycow
https://gfycat.com/poshpotabledassierat

**Comment by Daztek** [comment]
`EffectDeath()` which DM Kill uses applies visual effect `VFX_COM_GIB` (119) which has a ProgFX_Impact of 800, so my guess is that the problem lies there somewhere due to the ProgFX changes, since the issue doesn't happen in 8193.13
