### ISSUE TITLE
Bow Enhancement Bonus and Bonus Damage Bug

### ISSUE THREAD

**Issue by CormyrTFK** [Beamdog/nwn-issues#149]
**To Reproduce**

 - Edit itemprops.2da to allow ranged weapons to be given enhancement bonus and bonus damage properties.
 - create a longbow with an enhancement bonus and bonus damage properties.
 - Create a test module including the bow, a PC and a goblin.
 - Load module and attack goblin with bow.
 - Both PC attacks and goblin attacks will occasionally not show in combat log for up to several minutes after damage is rolled,
    reported in combat log, and applied to targets.
 - PC attacks with bow sometimes show proper total attack bonus, but at other times, show incorrect and varying total attack 
    bonuses.

**Specifics**

 - OS (Windows)
 - Game build (unsure, steam auto-updates though)
 - Distro platform (Steam)
 - Content overrides? (PW haks, but none affecting combat calculations or the combat log)
 - Regression? (unknown)

![AttackRollTimingBug](https://user-images.githubusercontent.com/70111531/90987208-21c9a500-e557-11ea-98bb-0837869ab610.PNG)

**Comment by CormyrTFK** [comment]
This bow should be giving the PC a total attack bonus (including BAB and Dex) of +8.  As shown in the screenshot, it at first gave a +4 total attack bonus, and then when switching from full plate to studded leather (unsure if that actually had an effect though, as the attack values have changed in the past without switching armors), it shot up to the +8.

**Comment by YunimNWN** [comment]
Does this PC have Point Blank Shot? Using a ranged weapon in melee range gives a -4 AB penalty unless the attacker has Point Blank Shot. Try attacking with combat debugging enabled and check the combat log for more details.

**Comment by CormyrTFK** [comment]
The changing attack bonus is explained by that it turns out, but the weird reverse order of showing damage, and then sometime later the attack rolls showing up seems to still be an issue.

**Comment by Shad000w** [comment]
We have enhancement bonus and damage bonuses on all ranged weapons in Arkhalia for years and never noticed any such issues. We are using old NWN-EE patch though.

**Comment by CormyrTFK** [comment]
That's really weird.  Maybe an update in some of the newer patches affected it?  I can't think of why that should be the case though.

This module is one that was originally built in NWN 1.69 though, could that possibly be a factor?  I could fairly easily make a new module and associate the Q haks and our custom haks with that new module and then import the areas, etc. from the old module if that might fix the problem.

**Comment by CormyrTFK** [comment]
Curiouser and curiouser...

I just tested with a regular bow with no properties and got the same original results of weirdly varied attack bonuses (not just the -4 you'd expect from being in melee range, but losing 6 AB one time, and only losing 2 AB another time).  I also got the mis-ordered damage first, then attack rolls.  One attack roll even took so long to show up that my test PC rolled for initiative again when it showed up.

![Base No-Properties Longbow Combat Bugs](https://user-images.githubusercontent.com/70111531/91102140-91fb2800-e636-11ea-8e92-88efa793158e.PNG)

**Comment by YunimNWN** [comment]
Assuming that you're testing this on a PW, regular players can't enable combat debugging and I don't know if DMs can. Combat debugging can definitely be enabled in single player so it might be worth testing offline to see if you still experience any problems.

Despite damaging the goblins all of your attacks are misses so something isn't working normally.

The AB of your attacks were: +0, +2, +0, -2, +2.
According to the character sheet your AB is +4, although the character sheet lies so it's possible that's not completely accurate.
Using a ranged weapon in melee range gives a -4 AB penalty and using a ranged weapon against a moving target gives a -2 AB penalty. Without combat debugging I can't be certain, but the -2/4/6 AB differences can be accounted for with those penalties.

The reversed attack / damage rolls happens fairly regularly in my experience, although I've never experienced a large delay between them. It's only really a problem if an OnPhysicalAttacked script (or functions related to it) have to be run before an OnDamaged / OnHit script. I've only noticed this reversal happen in the very first flurry of a fresh attack, once your character is in combat the attack / damage roll order should work normally.

**Comment by CormyrTFK** [comment]
I was running it via the "test module" button in the toolset.  I'll try loading it as a single player module. 

With the reversed attack and damage rolls, is that something you've only experienced with ranged weapons or with melee weapons as well?

**Comment by YunimNWN** [comment]
I've noticed the reversed rolls with both melee and ranged weapons, but only in the first flurry of a fresh attack. I've never experienced a large delay between rolls or any missing combat messages before though.

**Comment by CormyrTFK** [comment]
So I just tested it in single player, not as a test-build, and it worked just fine with no delays, and the combat rolls were all in the right order.  I'll put it up to something weird that's not a huge issue, and just keep building lol

**Comment by Finaldeath** [comment]
Closing since no issues apparently.
