### ISSUE TITLE
[8193.15 Preview] More TNO Ground Texture Issues

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#152]
**Description**

Many of the building Groups under "Grass" on the Tileset Palette have the wrong ground textures. In the screen shot I have painted many of the buildings - ALL have texture issues as evidenced in the screenshot.

**To Reproduce**

1. Open a module and construct an area using Castle Rural Exterior (TNO).

2. Paint Houses, Inn, etc. from under the "Grass" header that are larger than 1x1 tiles. You'll see that MANY have texture issues - using tno01_dirt03 instead of tno01_grass (as in v1.69).

![Whoops](https://user-images.githubusercontent.com/58920224/91510354-d0991880-e8aa-11ea-8c21-36924bd1bd35.jpg)

**Specifics**

 - Game build 8193.15,
 - Win 10
 - Steam

**Comment by pstemarie** [comment]
As a side not - when I tried to decompile TNO01_M37_10 and TNO01_M37_11, nwncompdcomp indicated the files were corrupt. These are the tiles that make up the 1x2 Inn Group.

**Comment by Bill-Harper** [comment]
I gave all the grass tiles a check, and think I got them all (at last).

**Comment by pstemarie** [comment]
Found some issues in the Dirt Buildings with missing geometry around some of the windows - Roundhouse 1, Roundhouse 2, etc. Might want to look at those too.

**Comment by Bill-Harper** [comment]
I think we finally got all these, at last?
