### ISSUE TITLE
Attack Bonus Progression Miscalculation in Combat UI

### ISSUE THREAD

**Issue by Prince-Raymond** [Beamdog/nwn-issues#155]
**To Reproduce**
1. Start a new game in NWN:EE
2. Create a level 1 Human Monk. Monks get the Cleave feat for free at level 1.
3. Using the Point Buy method, set ability scores as follows: STR: 14; DEX: 15; CON:10; INT: 14; WIS: 14; CHA: 10
4. While in game, enable both Debug Mode and Combat Debugging by using the Tilde ~ key followed by the DebugMode 1 and dm_enablecombatdebugging 1 console commands.
5. Level your character by using the Tilde ~ key followed by the GiveLevel (number) console command and take levels in Fighter. Dump all your Ability points into Dexterity. Spend one of your character feats on Circle Kick, and your Fighter bonus feats on the following: Point Blank Shot; Rapid Shot; Power Attack; Great Cleave; Weapon Finesse
6. Acquire and equip a Haste item when you can.
7. Locate any cluster of multiple enemies and engage them in unarmed combat while Flurry of Blows is both activated and deactivated.
8. Watch the combat log at the bottom of the screen _**very closely**_ as your character's base attack bonus falls into negative digits during every round of combat.

- The extra attacks granted by Attacks of Opportunity, Flurry of Blows, Haste and Rapid Shot should all be done at full base attack bonus, subject to the -2 penalty from FoB when in melee and the -2 penalty from Rapid Shot when in ranged combat.
- FoB, Haste and Rapid Shot attacks should be done at the beginning of a character's first flurry, not at the end of the final flurry.
- Circle Kick attacks should be done at the same base attack bonus of the attack that activated it, subject to the -2 penalty from FoB.
- Both Cleave and Great Cleave attacks should be done at the same base attack bonus of the attack that dropped the previous target(s), subject to the -2 penalty from FoB.
- The combat UI _**should not**_ apply an off-hand attack progression to free attacks in addition to normal melee and ranged attacks done by a character wielding neither two weapons nor a double weapon, especially a character striking unarmed.
- All attacks per round should be done in sequence from highest base attack bonus to lowest base attack bonus. The combat UI arranges a character's melee and ranged base attack bonuses out of sequence during every round.

**Specifics**
- OS: Windows 10
- Game Build: Patch 1.68 to Current
- Distro Platform: Any
- Content overrides: None
- Regression: Patch 1.68 released by BioWare for Neverwinter Nights broke what used to work in earlier builds. Don't believe me? Run a side-by-side comparison of the same combat encounter with two copies of NWN patched to 1.67 and 1.68, respectively. You will clearly see for yourselves the combat UI is not, I repeat, _**not**_ working as intended. You will also see there is absolutely nothing describing this bug/issue/mechanic/regression anywhere in NWN's patch details. This digital migraine has (officially) been in the game since August 30, 2006.

**If needed, describe the bug**

NWN:EE's combat UI is erroneously applying an off-hand attack progression to what are **_clearly not_** off-hand attacks. These include both normal melee and ranged attacks, as well as free attacks granted by Attacks of Opportunity; Circle Kick; Cleave; Flurry of Blows; Haste; and Rapid Shot. This broken mechanic creates a downward spiral of negative modifiers rendering a character's base attack bonus no longer a bonus, but a penalty in and of itself. Great Cleave (done at full base attack bonus) briefly resets a character's BAB to its highest positive modifier before it is suddenly dropped back into negative digits. This is both aggravating and appalling to the point of making me quit playing NWN:EE out of sheer disgust. I'm begging you, please, **_please_** stop the combat UI from applying this false progression.

![Pelude0](https://user-images.githubusercontent.com/70658358/140673902-f010911b-8ffb-4135-91b3-91b9e1f39b6a.png)
![2021-07-11 (1)](https://user-images.githubusercontent.com/70658358/140672070-1661b53e-6751-41e4-9ed2-9821481a57d3.png)
![2021-07-11 (2)](https://user-images.githubusercontent.com/70658358/140672076-86e58f38-3f0b-4e30-bab9-b3ec4ac747ea.png)
![2021-07-11 (3)](https://user-images.githubusercontent.com/70658358/140672078-ddc56ed1-3ff1-41c3-9efd-b79b4f983057.png)
![2021-07-11](https://user-images.githubusercontent.com/70658358/140672080-6cd87585-dde9-4291-87e5-afd827537d27.png)
![Circle Kick Same Target Chapter One](https://user-images.githubusercontent.com/70658358/140672081-9a2db28f-cbf1-4eca-ba32-5bf30d439ae4.png)
![Cleave Same Target Chapter One](https://user-images.githubusercontent.com/70658358/140672084-36e54e68-cafa-4c51-bdbb-33f658d3ffd3.png)

**Comment by LaputianBird** [comment]
A "please" would probably help

**Comment by Prince-Raymond** [comment]
@LaputianBird Check my most recent edit (21 hours ago), sir. You are my first response since deleting "Please." from the end of my post. If you truly believe in your heart of hearts that it will help, I will most certainly retype it.

**Comment by LaputianBird** [comment]
I hadn't realized that you had the explicit strategy of removing the "please" - don't mind me

**Comment by pF-arQon** [comment]
For reference: Rapid Shot has effectively the same bugs, i.e. attacks with that and Haste will be at e.g. 40/35/40/35/30/25 instead of 40/40/40/35/30/24.
(I don't think I could reach a negative AB on the last attack though: not without at least a helpful hostile Nerf caster.  :P)

**Comment by Prince-Raymond** [comment]
@pF-arQon Was this tested with a character that had Point Blank Shot in addition to Rapid Shot? I don't recall if one is a prerequisite for the other or not.

**Comment by pF-arQon** [comment]
Jep, was a typo, sorry - now corrected.

**Comment by pF-arQon** [comment]
I've found yet another variant of this, when using Rapid Shot on a Cleric along with Haste and Divine Power.

At Cleric6, casting DivPower to reach e.g. 14 AB (but with FTR BAB, and thus 2 APR now) should produce attacks at +14 and +14, which it does.

However, with Haste, that char should get THREE attacks, ALL of them +14, which it does not. instead, the attacks are +14/+14/+9.

And with Rapid Shot as well, that char should get FOUR attacks, ALL of them at +12. Unsurprisingly, it doesn't, but the error is even worse, and instead they end up with +12/+12/+7/+2. Obviously, that last attack is basically guaranteed to miss, making the whole combination rather pointless.  :(

**Comment by Prince-Raymond** [comment]
@pF-arQon That is very interesting, indeed. In all the time I have spent playing both NWN and NWN:EE, I have never played a Cleric. I prefer to play the more martial classes such as, Barbarian, Fighter, Monk and Paladin. This new revelation has got me curious, though. I wonder how this bug/mechanic would treat a Wizard high enough to cast Tenser's Transformation (for the improved BAB) with the Rapid Shot feat, Haste and levels of Arcane Archer. Who knows how many variants there could be as a result of BioWare's hack to the combat UI?

Something else that is rather pointless is the fact when you score a natural twenty on your attack with so low a base attack bonus (especially a negative one), that attack is basically guaranteed not to crit. Unless the RNG gods were to bless you with back-to-back natural twenties on both your hit and confirmation rolls, your potentially awesome critical hits will probably deal only normal damage.

Unfortunately, I'm afraid I have exhausted all my opportunities to express my concern with this issue on Beamdog's forums. I can't mention it there anymore without the risk of being banned. Besides, it seems it will take a lot more than one forum member to convince the devs at Beamdog to make it a priority. You, and anyone else you might know who play NWN:EE, can still report it [here](https://beamdog.atlassian.net/servicedesk/customer/portals) if you wish.

Thank you for further researching this annoying bug. Have a blessed day, be safe, and stay healthy.

**Comment by Prince-Raymond** [comment]
@pF-arQon Another thought occurred to me. Could there possibly be another variant of this bug regarding characters with Rapid Reload and Haste who attack from range with crossbows? Have you tested this with your Cleric?

**Comment by Prince-Raymond** [comment]
@niv @virusman Season's Greetings,

First, I would like to thank you all at Beamdog for releasing the HD Models & Textures Pack as a free download. It is very much appreciated. Second, I just wanted to know if you are still looking into Issue #155. I realize that I have raised this issue numerous times on the Beamdog Forums, and I don't mean to bother you with it. I just can't seem to get any fulfillment from playing NWN:EE with my OCD getting triggered by the combat UI's erratic behavior. To me, it doesn't make sense for attacks to follow a progression in addition to the Monk's unarmed attack progression and the standard attack progression of all other classes. This is especially unsettling when I see this happen to attacks that are supposed be done at full base attack bonus, such as Attacks of Opportunity and the extra attack granted by Haste. The fact that my character's base attack bonus consistently drops from a positive modifier to a negative one frustrates me to no end.

As @pF-arQon and I have mentioned earlier, there are variants of this issue. It affects both melee and ranged attacks, including those granted by spells like Divine Power and Haste. Flurry of Blows and Rapid Shot were designed to give an extra melee and ranged attack, respectively, at the character's full base attack bonus with a -2 penalty applied to all the character's attacks. The monk with FoB, and the archer with Rapid Shot, are already sacrificing accuracy for an extra opportunity to damage their targets. There seems to be no reason why the combat UI should stack a cumulative -5 penalty with the -2 penalty applied by either FoB or Rapid Shot in combination with Haste. Ironically, this doesn't happen to a character with Rapid Reload while Hasted.

What I don't understand is why you seemingly fixed what determines how attacks like Cleave etc. passively select their targets, yet you neglected to fix what determines whether or not these attacks will actually _**hit**_ their targets. Judging by a couple of screenshots I uploaded, it appears the fixes to passive target selection got broken in a later patch. Mr. niv stated in a PM on the Beamdog Forums that you would get to my issue sometime this year. Well, this year has just under a month left. Hopefully, you haven't forgotten about me. I am fully aware of your triage system, and I am not trying to influence or persuade you to prioritize fixing one bug over another. All I am asking, is that you please consider fixing passive target selection and Issue #155 an equal priority. There is one more thing I would like to ask. Before Mr. Andrew Gauthier left Beamdog, he told me the Base Attack Bonus Bug in the combat UI "definitely raised a few eyebrows". Can any of you tell me what he meant by that?

@LaputianBird I added "Please", twice, at the end of my ticket. Is that better?

You all have a blessed day, be safe and stay healthy. Happy Holidays.

~ Prince-Raymond

**Comment by Prince-Raymond** [comment]
And here we are in February 2022. I sincerely hope this issue gets fixed before it's old enough to get a regular driver's license. Considering this bug is 15 years old, it could already get a restricted operator's permit in my home state of Florida. How ridiculous do you all think _that_ is?

Thank you for reading. Happy, healthy (both mentally and physically) gaming to all.

**Comment by Prince-Raymond** [comment]
@pF-arQon I think I may have noticed another variant of this issue. Remember what I said in my comment about critical hits? Well, if you look at the bottom 2 screenshots, you will see the combat log displaying a critical hit process from a Cleave attack. The process is displayed as, _"hit (20 - 4 = 16 : Threat Roll: 3 - 4 = 7)"_, with the modifiers of the attack roll being subtracted and the modifiers of the threat roll being added. What's weird is the combat log displays the threat roll modifiers as part of a subtraction equation with a greater number subtracted from a lesser number. I'm no mathematician, but from what I understand 3 - 4 = -1 and 3 + 4 = 7.

I mean, which is correct? Should the modifiers of both the hit and threat rolls be added or subtracted? If the modifiers of the hit roll should be added, why are they not? If the modifiers of the threat roll should be added, why are they not displayed as such?

@Bill-Harper I just wanted to take a moment to congratulate you and the rest of the Beamdog Development Staff/Team on the recent release of your IP titled, Mythforce. I sincerely hope it is very successful. I understand you and the rest of the Beamdog Development Staff/Team are probably hard at work maintaining both Mythforce and the EE's, especially with Aspyr Media's acquisition of Beamdog. Would it be possible for someone on the development side to confirm whether or not this critical hit resolution process is working as intended if and when the time allows? I believe in my heart of hearts this should, at the very least, be documented and added to Aspyr Media's/Beamdog's development repo if it hasn't been done so already. Please.

Thank you for reading. Happy, healthy (both mentally and physically) gaming to all.

**Comment by Prince-Raymond** [comment]
Not gonna lie. I died a little inside when I got that email.

**Comment by Prince-Raymond** [comment]
Thought I should try testing the latest dev build through the BDC just for the hells of it. I went through the slums of Blacklake District and fought my way through a swarm of enemies with combat debugging enabled. On more than one occasion, my level 10 character did an Attack of Opportunity with a -6 BAB alone. The -2 penalty from FoB was factored in separately. After one of the AoO's, my character did unarmed attacks at -1, -6, and -11 BAB respectively. Again, these were all factored into his attack rolls separately from the -2 penalty applied by FoB. I took a screenshot of the occurrence. Here it is.
![Attack Progression Test](https://github.com/Beamdog/nwn-issues/assets/70658358/609cdbb5-7e6e-4c06-be59-24ef9dca88b7)

From what I could tell, there were no circumstantial penalties that would have robbed my character of his positive BAB. The only constant through all of this has been the -5 free attack progression. I humbly request that my ticket be re-opened, and this issue be investigated. Please. I have attached a game save for you to test with. Thank you for all you do.
[000005 - BAB Test.zip](https://github.com/Beamdog/nwn-issues/files/13433202/000005.-.BAB.Test.zip)
