### ISSUE TITLE
Visual Transform Bug

### ISSUE THREAD

**Issue by Adolin1** [Beamdog/nwn-issues#159]
The following mod will allow the tester to become scaled up and the animation to slow down. This is done to make the larger scale look more realistic so that it doesn't look like the tester is running in place. The bug is in slowing down the animation speed. Default armors and outfits work fine, however when a robe is applied everything slows down except for the torso, biceps, forearm, and cloak.

[Visual Transform Bug.zip](https://github.com/Beamdog/nwn-issues/files/5221648/Visual.Transform.Bug.zip)

**Comment by weavejester** [comment]
I also discovered this issue with the `OBJECT_VISUAL_TRANSFORM_ANIMATION_SPEED` visual transform.

As well as causing issues with robes, this bug also applies to cloaks when not wearing a robe. So if you have a character with their animation slowed or sped up, you'll see both cloaks and robes operating at normal speed.

My guess is that someone just forgot to apply the visual transform to the cloak and robe parts of the appearance.
