### ISSUE TITLE
[8193.16] Items with no tag in an inventory remove traps when the carrying PC or NPC walks over the trap

### ISSUE THREAD

**Issue by summonFox** [Beamdog/nwn-issues#164]
**To Reproduce**

 - Draw a trap on the ground in the toolset.
 - Create or copy an item and delete its tag.
 - Place the item without a tag on a PC or on an NPC.
 - Walk over the trap.

**Specifics**

 - OS (Windows, Mac, Linux)
Windows 10 64bit
 - Game build (e.g. 8193.8, or commit hash)
8193.16 ed828c00
 - Distro platform (BDC, Steam, GOG)
Steam
 - Content overrides? (Steam Workshop? Overrides? Patch haks?)
None
 - Regression? (Build which broke it, if known)
Has existed in NWN to my knowledge since (at least) 1.69.

**If needed, describe the bug**

When an item with no tag is carried by an NPC or PC and they walk over a trap, the trap is removed when it would normally trigger. This occurs for both toolset placed traps, player set traps (including friendly traps from yourself or faction members), and DM placed traps. It does not matter if traps are flagged as One Shot or not, they simply get removed and vanish when the NPC/PC walks over the trap.

I've attached an example module with the default Helm's Hold book copied into Miscellaneous > Books with its tag deleted. The bartender NPC has one in his inventory. Between the blue lights in front of the NPC are multiple resetting traps to walk over.

[Items Breaking Traps Bug.zip](https://github.com/Beamdog/nwn-issues/files/5251064/Items.Breaking.Traps.Bug.zip)

**Comment by Finaldeath** [comment]
Oddly the toolset will auto populate a tag on items so not sure how you made the test module (without direct GFF edits) but it can be reproduced and obviously would be good to fix.

**Comment by summonFox** [comment]
There are ways to accidentally remove tags from or create items without tags inside the toolset, but it's been so long now I can't even remember how.
