### ISSUE TITLE
[STABLE 8193.16] The texture with the *_d suffix is ​​not installed.

### ISSUE THREAD

**Issue by LiarisFreeze** [Beamdog/nwn-issues#166]
The texture with the *_d suffix is ​​not installed. If you remove the suffix, the engine finds it.
 Maybe, file * .mtr is not readable?

![20200920165619_1](https://user-images.githubusercontent.com/46865150/93713314-a06c2f00-fb63-11ea-9671-0600b098f043.jpg)

- Game build (STABLE 8193.16)
 - Windows 7
 - Steam
 - Content overrides? (haks)
 - Regression? (.15-.16)

[plc_trouble.zip](https://github.com/Beamdog/nwn-issues/files/5251801/plc_trouble.zip)
[plc_trouble.zip](https://github.com/Beamdog/nwn-issues/files/5251800/plc_trouble.zip)

**Comment by Soren217** [comment]
This should be fixed in the latest preview release - could you verify? @LiarisFreeze

**Comment by Soren217** [comment]
The issue seems fixed. However, I noticed that the material file reads:

`renderhint NormalAndSpecMapped
texture0 nwp_rocks_03_d
texture1 nwp_rocks_03_n
texture1 nwp_rocks_03_s
`

With two entries called `texture1`. This caused it to not show up properly even with the fix.
