### ISSUE TITLE
[STABLE 8193.15] Missing model: ptm_tnowater1 (Water, Wavy - TNO01)

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#167]
As indicated in the report title, the model ptm_tnowater1, associated with line 15522 in the placeables.2da is missing.

**Comment by Bill-Harper** [comment]
Thanks for the report! We got this one sorted out, should be in the next patch. I advise using a height of -0.8 or lower over a pit (e.g.), else you'll have some waves peeking out of the nearby ground

**Comment by pstemarie** [comment]
Why not just lower the model itself to Z -0.8 or -1.0? Probably save a lot of repeated questions/answers later.
