### ISSUE TITLE
Changing lightcolor.2da results in "List Index out of bounds"

### ISSUE THREAD

**Issue by Grymlorde** [Beamdog/nwn-issues#168]
**Description**

Making any changes in lightcolor.2da (changing values or adding lines) results in "List Index out of bounds" when right-clicking on a tile in the toolset but no problems with placeables using new entries.

**To Reproduce**

Use the attached lightcolor.2da or make changes/add lines on your own.
Place in a hak or the development foler
In the toolset, right-click on a tile.
Get error message.

Conversely, edit placeables.2da to give the stock chandelier a light value equal to Amber (from the attached lightcolor.2da)
[lightcolor.2da.txt](https://github.com/Beamdog/nwn-issues/files/5257394/lightcolor.2da.txt)

Place the chandelier in the toolset
Run the game and enjoy the new amber light.
No errors.

**Specifics**

 - Game build 8193.16
 - Windows 7
 - BDC,
 - Same result in hak or development folder. No other overrides or CC

**Comment by Bill-Harper** [comment]
I can confirm this issue, it cannot accept more than 32 entries. I was able to change some existing entries around successfully.
