### ISSUE TITLE
(Great) Cleave issues

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#172]
- any OS, any build

(Great) Cleave is not triggered properly.

- sometimes, randomly (great) cleave is not triggered at all despite there are nearby enemies
- - this seems to be happening much more often if the player fights creatures with large models, but is definitely not limited to such creature models
- - this is almost always happening if the monster got killed by devastating critical/vorpal
- - this is happening with 99% rate if the creatures have circle auras on them (but that is actually a [different issue](https://github.com/Beamdog/nwn-issues/issues/52))
- sometimes, if the monster is killed in a first attack in flurry and player has 3 attacks in that flurry (or more) and they hit too, cleave is actually triggered multiple times incorrectly
- if the player gains a cleave attack and then cancels attack action immediately by moving for example, next time he starts attacking the cleave will be executed on the previous intented cleave target no matter if that npc is around or even in same area, this causes player to execute a first flurry and then stop attacking

**Comment by pF-arQon** [comment]
- Cleave also randomly triggers on the creature that just died.
- Cleave also randomly doesn't trigger at all.
- Cleave is also typically followed by the killer disengaging from combat as "Target out of reach" despite the Cleave hitting them (and often even when there's a direct / clear path to the enemy that the killer just got dropped from).
