### ISSUE TITLE
[8193.17 PREVIEW] Gem Weapon & Shield Issues

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#174]
**Description**

The Gem Shields (AshTo_052, 053, 054) do not show the textures as no UV Mapping has been applied to the mdl.

The Gem Weapons (wblhw_071-07 and wswgs_071-074) all have a greenish tint.

These are caused by the same issues as the Gem Golems that Bill Harper fixed in the latest patch. I have enclosed a copy of my fixed models if you want to just include these.

[GemWepShld.zip](https://github.com/Beamdog/nwn-issues/files/5305440/GemWepShld.zip)

**Specifics**

 - Game build 8193.17 e8f2fd8a
 - OS Windows 10
 - Distro platform Steam
 - Content overrides? n/a
 - Regression? 8193.14

**Comment by Bill-Harper** [comment]
Shield models had UV's, but not very good UV's. I took care of the self-illum all around, matching values up. I also included the gemstone placeables. New UV Mapping all across the board.

![gemstones](https://user-images.githubusercontent.com/53191846/95344108-44a1e580-0887-11eb-9eb6-82bd411947d9.png)

**Comment by Bill-Harper** [comment]
![gemshield_icons_inventory_1x-2x-scale](https://user-images.githubusercontent.com/53191846/97321650-7df5c180-1845-11eb-8ea0-6cc7cfd69257.png)

Added icons as requested. A mental Ray render at 512x1024, a flat reflection-free opaque render overlayed with a 100% transparent, fully reflective layer, in Photoshop. I can't use the larger icons for now, have to go 64x128 else they don't show up in toolset (but look great in game).

**Comment by Bill-Harper** [comment]
![gemshield_icons_inventory_1x-2x_UI-Scale_8x_Real-Scale](https://user-images.githubusercontent.com/53191846/97324434-33297900-1848-11eb-9cd8-305a985a4e76.png)
