### ISSUE TITLE
[Switch] Client crashing when applying FloatingTextStrRefOnCreature that is too long

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#176]
We received a lot of reports from Switch players that their client would crash at certain times and the common thread was the use of a FloatingTextStrRefOnCreature that was too long; it seems that over a certain number of characters (somewhere between 100 and 198) a Switch player will crash consistently when this is applied on their character.

**Comment by niv** [comment]
> DO NOT REPORT MOBILE OR CONSOLE BUGS HERE. This is only for the desktop build of the game. Bugs on other platforms need to be reported through Service Desk, via the link above. Reports for non-desktop platforms will be closed without comment.
