### ISSUE TITLE
[8193.16] Standard Palette Orcus Doesn't Have Creature Skin

### ISSUE THREAD

**Issue by Balanor** [Beamdog/nwn-issues#177]
**To Reproduce**
- In the toolset, go to Creatures > Standard > Planar > Fiendish, and then right-click on Orcus and go to Edit Copy
- Click the Inventory button, and then click on the Natural Equipment tab.
- Note that the creature is missing the Orcus Properties creature skin (ResRef: orcusproperties) found in the Items > Standard > Creature Items > Skin/Hide palette

**Specifics**
-Game Build 8193.16

**If needed, describe the bug**
It would be nice to have the standard palette version of Orcus updated to have the Orcus Properties skin equipped on him.

**Comment by Bill-Harper** [comment]
Thanks for the report! I've made another copy of the blueprint, with both creature hide and wand in inventory.

**Comment by Balanor** [comment]
Sounds great, thank you! Just a quick note on that too; if you just put the Wand in inventory, you might want to also add the Simple Weapon Proficiency as the Standard palette Orcus does not have it, so he isn't able to use maces.
