### ISSUE TITLE
[8193.16] City, Exterior Tileset - Missing Model Faces

### ISSUE THREAD

**Issue by Clockwerkd** [Beamdog/nwn-issues#178]
**Description**

Where City tiles are placed adjacent to water tiles in the City, Exterior tileset, building model faces appear to be missing.

![image](https://user-images.githubusercontent.com/52304166/94874248-2c5d4100-0417-11eb-9943-5b8e3fde8ba2.png)

**To Reproduce**

 - Create a new area using the City, Exterior tileset
 - Place water tiles in the center of the area creating a pool of water that is 3 tiles x 4 tiles
 - Surround the water tiles with building tiles
 - Building model faces at corners will exhibit missing faces 

**Specifics**

 - Game build 8193.16
 - Windows 10
 - Beamdog

**Comment by Bill-Harper** [comment]
Thanks for the report! Did you see any besides the corner tile (TCN01_A06_01)? That was the only one which turned up for me when making a pool bordered by buildings.

![tcn01_a06_01](https://user-images.githubusercontent.com/53191846/95324334-93db1c80-086d-11eb-9583-449f7961179d.png)

**Comment by Clockwerkd** [comment]
Hi, Bill.

From what I can tell, it was just the corner tile that was missing faces. Thanks for repairing this!
