### ISSUE TITLE
[8193.16] SkillPointModifierAbility set to "****" causes error in ValidateLevelUp

### ISSUE THREAD

**Issue by weavejester** [Beamdog/nwn-issues#180]
**To Reproduce**

 - Add a custom `racialtypes.2da`
 - Change the `SkillPointModifierAbility` to `****` (or an invalid ability like `NONE`) to disable abilities modifying skillpoint totals
 - Create a character
 - Level them up once, skillpoint totals are correctly calculated without any ability modifier
 - When finishing the level up, the server will report: `[Server] Character applied invalid number of skillpoints.` and revert the level up.

**Specifics**

 - Windows client, docker-based Linux server
 - Game build: 8193.16
 - Distro platform: Steam

**Description**

Daz in the NWNX Discord suggests that this is an issue with `CNWSCreatureStats::ValidateLevelUp`, where a blank or unknown `SkillPointModifierAbility` will be interpreted as a strength-based modifier.

In other parts of the code the ability modifier is correctly disabled, i.e. on the character creation/level up screens you get the base number of skillpoints to spent without any ability modifiers being applied.

**Comment by niv** [comment]
Thanks for the report. It's actually a undefined memory read (`m_lstAbilityGainTable[i - 1][ability]` for `CABILITY_NONE` is reading the STR adjust for the _next_ level, or out of bounds, whichever comes first. ;))

**Comment by weavejester** [comment]
Thanks for the fix!

**Comment by weavejester** [comment]
Unfortunately this has not been fixed. 8193.20 still has this issue.

**Comment by weavejester** [comment]
According to a conversation with Daz on the NWNX Discord:

> when you set the skillpoint ability to none it sets the ability base to 0 ... which when calculating the modifier is ... -5
> If you set the ability base to 10, which is neutral, it should work correctly

For those who are looking for a workaround and are using NWNX on their server, there's now a NWNX Experimental plugin that disables level up validation entirely.

**Comment by niv** [comment]
Another attempt was made
