### ISSUE TITLE
[8193.16] ttf02_i07_02.mdl has extra branches/foliage that don't don't belong

### ISSUE THREAD

**Issue by plenarius** [Beamdog/nwn-issues#181]
**Description**

`ttf02_i07_02.mdl` has extra branches/foliage that don't don't belong, maybe a compilation issue, not sure

Now:
![Screenshot-20201004045358-969x691](https://user-images.githubusercontent.com/11622375/95011298-a51df200-05fd-11eb-9680-669b085c4aec.png)

Before:
![Screenshot-20201004045253-850x668](https://user-images.githubusercontent.com/11622375/95011276-7bfd6180-05fd-11eb-876e-cb61f3b14497.png)

**To Reproduce**

 - Create new area with `Forest - Facelift` tileset
 - Place `Wall Gate 2` from the Features 

**Specifics**

 - 8193.16
 - Linux
 - Steam

**Comment by Bill-Harper** [comment]
![181_too_many_leaves](https://user-images.githubusercontent.com/53191846/96284991-5c2a4e00-0fac-11eb-9f16-a4533f7ef48f.png)

Thanks for the report and followup! I thinned out the leaves, and set the grassrim texture to the proper/new ttf02 version
