### ISSUE TITLE
Human XP Penalty Bug

### ISSUE THREAD

**Issue by ZarkIsBad** [Beamdog/nwn-issues#182]
To Reproduce

 - Human Character
 - 9 of any base class, 11 of another base class and rest as a prestige class
 - Normally a human would take the highest levelled base class as its favoured class
 - Was online and not single player/campaign (have checked if it was server specific and it isn't however)

Specifics

 - Windows 10
 - Game build 8193.15
 - Steam
 - No overrides
 - Not known

Further Description

I noticed this first on a 4monk 12cleric and 20weapon master where I was gaining the 20% XP reduction penalty on all kills, normally as a human you wouldn't since the cleric would be taken as the favoured class not the weapon master. As I said above it was in a server but it was not due to server specific changes. 

I apologize if this is just a feature or it was a bug before that it didn't apply to prestige classes.

**Comment by Arvirago** [comment]
The game takes the human highest class (20 weapon master) as favoured class, even if it's a prestige class.
So the human gets the 20% penalty for the difference between monk and cleric levels.
Same for half-elves.

**Comment by Stratovarius667** [comment]
> The game takes the human highest class (20 weapon master) as favoured class, even if it's a prestige class.
> So the human gets the 20% penalty for the difference between monk and cleric levels.
> Same for half-elves.

This is incorrect behaviour. Prestige classes do not count for the multiclass penalty and should be ignored, thus counting the 12 Cleric as the highest class level in the example given.
