### ISSUE TITLE
[8193.16] Mines and Caverns Tileset - Exit 1 Tile Missing Model Face

### ISSUE THREAD

**Issue by Clockwerkd** [Beamdog/nwn-issues#183]
**Description**

Instances of the Exit 1 tile in the Mines and Caverns tileset appear to be missing a model face on the interior right side of the opening.

![image](https://user-images.githubusercontent.com/52304166/95027612-805a6680-065f-11eb-8fe7-d51bc5409fe4.png)

**To Reproduce**

 - Create a new area using the Mines and Caverns Tileset.
 - Place an instance of Exit 1.
 - Using the filter toggles in the Toolset, toggle door objects to not be visible.
 - Maneuver the camera to inspect the interior faces of the exit opening.

**Specifics**

 - 8193.16
 - Windows 10
 - Beamdog

**Comment by Bill-Harper** [comment]
Thanks for the report! This mesh was completely missing, not just shifted around. Copied from the other side and put into place.

![tdm01_o11_01](https://user-images.githubusercontent.com/53191846/95322893-3ba31b00-086b-11eb-9180-83d0848cb8be.png)

**Comment by Clockwerkd** [comment]
Thanks, Bill! Sounds good.
