### ISSUE TITLE
[8193.16] Standard Barrel Model No Longer Plays Open Animation Upon Clicking It

### ISSUE THREAD

**Issue by Clockwerkd** [Beamdog/nwn-issues#184]
**Description**

The standard barrel container's lid does not open when selected. 

**To Reproduce**

 - Place a barrel object in an area with the module's start location.
 - Ensure that the barrel is set to Useable and Has Inventory.
 - Save and start the module.
 - Click on the barrel with your PC. The open sound will play, but the lid will not animate.

**Specifics**

 - 8193.16
 - Windows 10
 - Beamdog

**Comment by Bill-Harper** [comment]
By "standard barrel" do you mean the original named "Barrel" (in toolset, appearance tab) or the "Barrel 01" that was added in XP3 patch? The "Barrel" is working fine for me in my tests. "Barrel 01" is a one-piece model mesh and thus never came with open/close animations.

![barrel_lid](https://user-images.githubusercontent.com/53191846/95321284-d6e6c100-0868-11eb-972f-fa1b77c3f9b4.png)

**Comment by Clockwerkd** [comment]
I apologize as I should have been more specific on which barrel!

On my end, both the plc_barrel (TAG: Barrel) and x2_easy_barrel (TAG: x2_easy_Barrel) fail to animate the lifting of the lid in game. I can set them in the toolset to be opened and they appear as anticipated, but it seems that the animation does not work in game.

**Comment by Clockwerkd** [comment]
Bill,

Upon further testing, it looks like it may be 2DA related on my side. Is there a 2DA parameter that controls the animations?

**Comment by Clockwerkd** [comment]
I just confirmed with Pstemarie that this is an issue when there are multiple instances of the same container model in an area but that have different Static/Has Inventory/Useable check boxes checked. To recreate, place 2 instances of “Barrel” in an area. Set one to be static. Set the other to Has Inventory/Useable. The useable barrel’s lid animation will not function.

**Comment by pstemarie** [comment]
I have confirmed that the same issue applies to chests and crates as well - and my assumption would be anything that has an openable lid. Even odder is that when the lid is opened and fails to move, it still generates a shadow as if it opened correctly.

**Comment by hendrikgit** [comment]
I just came across the same issue. Having one chest as static breaks the animation of the usable one. I attached a minimal module to reproduce.

[module.zip](https://github.com/Beamdog/nwn-issues/files/5772227/module.zip)

![image](https://user-images.githubusercontent.com/7437391/103691230-220e8e00-4f96-11eb-9465-9eec04aabbe8.png)
