### ISSUE TITLE
RDD ability increases apply when polymorphed.

### ISSUE THREAD

**Issue by YunimNWN** [Beamdog/nwn-issues#185]
**To Reproduce**

 - Create any character with at least two Red Dragon Disciple levels and access to some form of polymorph (eg. Druid5/Bard1/RDD2).
- Polymorph and note that the RDD ability increases (+2 STR for RDD2) apply when polymorphed.

**Specifics**

 - OS: Windows
 - Game build: 8193.16
 - Distro platform: GOG
 - Content overrides? None
 - Regression: Definitely a regression from 1.69. Untested, but possibly started in 1.79.8193 when the PM/RDD changes happened (https://store.steampowered.com/newshub/app/704450/view/1700601856699270960).

**If needed, describe the bug**

Ability increases from RDD levels modify the base STR/CON of polymorph forms which didn't happen in 1.69. This applies to all forms of polymorphing, whether from feats, spells, or scripts. I haven't tested how RDD ability increases should work for polymorph forms with a blank STR or CON value in polymorph.2da, but there's no way for an RDD to access those polymorph forms in vanilla NWN so that's less of a concern.

Below is a picture of a Dragon Shape build with 56 STR and 34 CON (instead of 48 STR and 32 CON) that has +8 STR and +2 CON from RDD ability increases. These ability increases don't apply to the +12 ability cap, so this build can potentially reach 68 STR and 46 CON.

![RDD Polymorph Bug](https://user-images.githubusercontent.com/69238778/95102837-c846bf80-072b-11eb-8957-d0dc6bc44698.png)

**Comment by niv** [comment]
Technically speaking, class-based bonuses apply regardless of current racial type. Yes, it's a regression, but the same argument can be made for the natural AC bonus (which has probably also "broken" this way since 1.79) and more philosophically speaking, whatever else the class provides as a bonus effect. Should those also not apply?

Is this something that should be reverted or is the new approach, maybe, the more correct one? (Apart from Polymorph being utterly insane in the first place, of course, but that's neither here nor there.)

**Comment by OrionNwnworkshop** [comment]
Hi NIV
Yunim is reporting an unexpected finding identified and shared by another player, TheSquid, to a group of experienced players. 

In terms of whether it should be reverted is a different question. Obviously Yunim has a view but I have an alternative one. From a character building perspective I actually don't view this as a particularly overpowered mechanic. It's why I haven't reported this myself.

Firstly Most RDD builds will be strength based characters and it makes little sense to polymorph oneself to a essentially weaker form. 

The downside with playing a Druid / Bard / RDD with Dragon Shape is that it precludes the Druid from having a Monk level. Monk adds the Wisdom modifier (which will be 38-42 with Owl's Insight) and essentially doubles the number of attack of the Dragon Shape. There might be some quirky builds with a Bard 12 / RDD 10 / Druid 18 however the Bard/Curse song in the build does not hit the natural power spot for Bards at level 16 (which provides -5 AC to curse song).

If one were to play a sorcerer / RDD, it costs 10 caster levels to invest in RDD that one normally would not invest, making spells more likely to be dispelled, and requiring investment in spell penetration feats or suffering lower spell penetration.

I had a discussion with a [group of experienced players](https://www.tapatalk.com/groups/worldofgreyhawkfr/shapechange-and-rdd-builds-t5427.html#p71296) about trying to apply this mechanic on one of the NWN community's most difficult player versus monster persistent worlds, to the Shapechange spell. We actually dissected out this mechanic in detail try to apply it to the Shapechange spell. 

Some of the comments were:
"I consider those ABs and ACs to be fairly low for WoG, to be honest." (for a Sorc / RDD / BG divine might/shield idea)
"(For a Bard RDD BG idea) Yes, I was going to say that such a high CHA score seems kind of wasted on a Bard, but I guess I understand. If you were to leave CHA at something like 20 and pump STR, then you'd have less incentive to use Shapechange. So, most of the time you'd fight in your regular shape, only switching to Iron Golem when Critical Hit immunity was needed..."

In the end it adds +4AB and +4DMG to attacks and +40 HP to a 800-900 hp behemoth (for dragon shape)
I don't view it as a bad thing that should be removed, rather some thing that has 'inadvertently enhanced things' in the Enhanced Edition, by allowing character builders to explore new ideas - are there ways we can make character builds that can make use of RDD?   

I am wary that your time is precious and this is a game that is 18 years old, however in terms of Beamdog's resources (which are not limitless, unlike games such as Dota 2) I believe you should direct your efforts elsewhere. Just my opinion on the matter.

Orion

**Comment by pF-arQon** [comment]
after the fact, but...

@OrionNwnworkshop  >Firstly Most RDD builds will be strength based characters and it makes little sense to polymorph oneself to a essentially weaker form.

Really? I can give you a trivial one off the top of my head: a Zombie, for the trifecta of Crit Immunity, Necro Immunity, Mez Immunity; and more.

(As a sidenote: If the bug is fixed, it would be trivial to crank the stats etc back up with a script. If the bug is NOT fixed though, admins will have no way to repair the stats to the values they should have).
