### ISSUE TITLE
[8193.16] twc_03_c53_01 & _06 missing fire animation

### ISSUE THREAD

**Issue by Grymlorde** [Beamdog/nwn-issues#188]
**Description**

In the Fort tileset (twc), tiles twc_03_c53_01 and _06 are missing the fireplace animation in both the toolset and the game.

**To Reproduce**
Create a Fort Interior area with the toolset.
Place the two bedrooms which have fireplaces.
Select the animate checkbox.

**Specifics**

 - Game build 8193.16
 - OS (Windows 7)
 - Distro platform (BDC)
 - Content overrides? (None)
 - Regression? (8193.16 or earlier?)

**Comment by Bill-Harper** [comment]
Thanks again for the reports! I got the fireplaces working, and added woodpiles as well from the other fireplace (they looked pretty silly burning w/o fuel).

![fireplaces](https://user-images.githubusercontent.com/53191846/95351656-7454eb80-088f-11eb-9948-192a509cce15.png)
