### ISSUE TITLE
[8193.16] iit_torch_002 has smoke emitter

### ISSUE THREAD

**Issue by Grymlorde** [Beamdog/nwn-issues#189]
**Description**

The new candlestick "torch" (iit_torch_002) still has the torch smoke emitter.

**To Reproduce**

In the toolset, create a candlestick item (iit_torch_002)
Place it in an area
Play the game and have a PC equip the candlestick.
Note the smoke emitting from the candlestick as if it were a torch.

**Specifics**

 - Game build (e.g. 8193.16)
 - OS (Windows 7)
 - Distro platform (BDC
 - Content overrides? (None)
 - Regression? (8193.16 or earlier)

**Comment by Bill-Harper** [comment]
Mass, velocity, lifetime and birthrate have all been reduced significantly.
