### ISSUE TITLE
[8193.16] (trm02) Medieval Rural 2 - Tile 1313 is missing left crosser data

### ISSUE THREAD

**Issue by Daztek** [Beamdog/nwn-issues#194]
**Description**

Tile 1313 in Medieval Rural 2 is missing its left crosser data.

Tile 1313's .set file entry

```
[TILE1313]
Model=trm02_g46_03
WalkMesh=msb01
TopLeft=grass
TopLeftHeight=0
TopRight=mountain
TopRightHeight=1
BottomLeft=grass
BottomLeftHeight=0
BottomRight=mountain
BottomRightHeight=1
Top=
Right=stream
Bottom=
Left=
MainLight1=1
MainLight2=1
SourceLight1=1
SourceLight2=1
AnimLoop1=1
AnimLoop2=1
AnimLoop3=1
Doors=0
Sounds=0
PathNode=A
Orientation=0
ImageMap2D=mi_trm02_g46_03
```

The tile in question:

![Tile](https://i.imgur.com/Idb9ONB.png)

`Left=` should be `Left=stream`

**Specifics**

 - Game build: 8193.16
 - OS: Windows
 - Distro platform: Steam
 - Content overrides: None
 - Regression: Unknown

**Comment by Bill-Harper** [comment]
.Thanks for the report; there hasn't been much feedback on the Medieval tiles, yet. SET file corrected for the proper crosser data.
