### ISSUE TITLE
[8193.16] (tcm02) Medieval City 2 - Multiple tiles with water issues

### ISSUE THREAD

**Issue by Daztek** [Beamdog/nwn-issues#195]
**Description**

The following tiles are missing their water:

Tile 514 - tcm02_i34_05
Tile 515 - tcm02_i34_06
Tile 1042 - tcm02_i34_07
Tile 1043 - tcm02_i34_08

Example:

![Example](https://i.imgur.com/JafJ7Vg.png)

**To Reproduce**

Create some terrain that looks like the following and place Wall crossers at the Xs

![Repro](https://i.imgur.com/hr5unbB.png)

**Specifics**

 - Game build: 8193.16
 - OS: Windows
 - Distro platform: Steam
 - Content overrides: None
 - Regression: Unknown

**Comment by Daztek** [comment]
Tile 688 (tcm02_g13_01) appears to have some issues with its water too.

![Tile688](https://i.imgur.com/xyg9bJg.png)

**Comment by Daztek** [comment]
Tile 250 (tcm02_b82_01) has its water a bit too high.

![Tile250](https://i.imgur.com/D5uyIZT.png)

**Comment by Bill-Harper** [comment]
![tcm02_water-walls](https://user-images.githubusercontent.com/53191846/96289298-ccd46900-0fb2-11eb-84ae-165e4eb55d7c.png)
 Well, I  got the first round of reports, at least. Water was present, but undersized and not positioned properly. I simply copy/pasted in a full-sized water plane from another tile and re-exported. Should all be good now.

**Comment by Bill-Harper** [comment]
![stream_rockfall](https://user-images.githubusercontent.com/53191846/96293631-10ca6c80-0fb9-11eb-8125-a00dbe40564c.png)

No idea what happened with this tile, it was more than just rotated wrong, but it worked out pretty well in the end.

**Comment by Daztek** [comment]
Awesome, thanks Bill! If I come across any other issues, I'll post em.
