### ISSUE TITLE
[8193.18 bb6e5cb7] Toolset Crashes When Attempting to Open ANY Area

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#205]
**To Reproduce**

 - Open the Toolset
 - Open an area
 - Toolset crashes

Note: If attempting to open an area made with a tileset from a HAK, the error is "Abnormal Program Termination"

**Specifics**

 - Game build? 8193.18 bb6e5cb7 PREVIEW
 - Regression? 8193.18 aeb4b135 works ok

**If needed, describe the bug**

When opening an area in the Toolset, the toolset immediately crashes with the error in the image. The tiles don't even attempt to load.

![crash](https://user-images.githubusercontent.com/58920224/97311023-45041f80-183a-11eb-8894-cfb6a1304f4b.jpg)

**Comment by pstemarie** [comment]
Screenshot was actually taken by Jasperre - he's having the same issue.

**Comment by Soren217** [comment]
This should be fixed now, could you verify?

**Comment by pstemarie** [comment]
All fixed
