### ISSUE TITLE
Caster Levels with Feats and Items are not correctly calculated when applied as an effect

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#210]
**To Reproduce**

 - Load this module with the Exalted Sorcerer (40) pre-generated character: [Jasperre Test Spells.zip](https://github.com/Beamdog/nwn-issues/files/5513754/Jasperre.Test.Spells.zip)
 - Pick up the rod )or some potions in the chest, same difference)

Bug 1 - initial item usage uses wrong caster level.

 - Use the Cats Grace (3) spell from the rod. See that the spell script detects Caster Level 3 correctly, but effects applied are actually set to Caster Level 10. This can be tested by using Lesser Dispel on the lever (it will work 1 of 20 times, but not as often as a real low level spell cast - eg; the Barkskin option in the conversation would dispel roughly 50% of the time).

![image](https://user-images.githubusercontent.com/6137144/98602632-af0bd280-22d8-11eb-9bac-f81bc5f45ec2.png)

 - Now use the Protection from Spells (20) from the rod. It detects level 20 in the spell script but the effect applied is at caster level 13. This can no longer be dispelled by Lesser Dispel Magic (1) but can be by Dispel Magic (10).

![image](https://user-images.githubusercontent.com/6137144/98602741-dfec0780-22d8-11eb-9765-d5a9a40fb13b.png)

In both cases the caster level is set on the effects improperly - ie to 10 and 13 instead of 3 and 20. It appears to use the same calculation as if it was a "cheat-cast" spell (or DM cast) ie; Always minimum of 10, or (2 * Innate spell level) - 1 (so 10 for 1-5, then level 6 is 11, 7 is 13, 8 is 15 and 9 is 17).

Bug 2 - caster level overrides item level.

 - Carry on from previous tests, or to be sure, use Cats Grace (3) and show the caster level is detected as 3, with effects applied as 10.
 - Cast Bulls Strength from the Exalted Sorcerers castbar (CTRL + F9)
 - Cast Endurance (10) from the rod (note the caster level is properly detected in the spell script)
 - Note you have ability increases at caster level 10 (cats grace), 38 (Bulls Strength) and 38 (Endurance)
 - Any more items you use will be now at level 38 caster level
 - Even Greater Dispel Magic, usually 15 + d20 vs 11 + caster level - so should be able to dispel the Endurance (10) which is DC 21 but this doesn't work (it never dispels).

![image](https://user-images.githubusercontent.com/6137144/98603095-67d21180-22d9-11eb-9ab6-67fc192467c5.png)

Testing with a lower level caster decreases the spell effect level - ie Protection from Spells (20) becomes level 5 when the item is used by a level 5 caster (in this case a Bard).

![image](https://user-images.githubusercontent.com/6137144/98604286-4bcf6f80-22db-11eb-90dc-b7749626aa35.png)

Bug 3 - caster level for feats is also incorrect.

 - Use the same module with this Harper character: [harper1.zip](https://github.com/Beamdog/nwn-issues/files/5513680/harper1.zip)
 - Use "cats Grace" from spell bar. It correctly reports level 5 caster level (ie; Harpers class levels) but applies the effect at level 10

![image](https://user-images.githubusercontent.com/6137144/98605164-e9776e80-22dc-11eb-8fa8-661c2d3d7c26.png)

No easy way without hakpacks to do a caster level test to see if it follows the "cheat" type casting caster level but it likely does.

Bug 4 - Even worse feat caster levels when Innate column is not set at all

 - Blackguards and Assassins use buggy spells.2da lines with no "Innate" spell column value.
 - Use this blackguard file:  [blackguard1.zip](https://github.com/Beamdog/nwn-issues/files/5513750/blackguard1.zip)
 - Use "Bulls Strength" and see it cast at a correct caster level of 2
 - See your admittedly impressive magic skill as you have 509 caster level on the effect, making it impossible to dispel using even Mords Disjunction.

![image](https://user-images.githubusercontent.com/6137144/98606584-67d51000-22df-11eb-85ae-2008565a1a4c.png)

**Specifics**

 - OS Windows
 - Game build 8193.19
 - Distro platform Steam preview
 - Content overrides? None relevant
 - Regression? NWN:EE at some point altered it so caster levels were more correctly stored on the effects, rather than "getting the data from the caster again" but this has not seemed to be set correctly in regards to items or feats (with Items getting the spellcasters level sometimes, or both using some metric of "caster level" from 10-17).

**If needed, describe the bug**

Fixes needed:

 - Items cast from spells need to consistently use the same caster level as their described property for the spell script (GetCasterLevel) and the applied effect level, instead of either the "cheat-cast" approach of 10-17 or the "last caster level from a real spell". Neither of these should be possible.

 - Feats also need to apply what level is set in GetCasterLevel which appears - at least at first glance with the Harper and Blackguard spells - to be correct (prestige class level is used). But they always rely on 10-17 calculation which bugs out massively on Blackguard and Assassin spells (509 caster level, which is probably an underflow bug doing min(10, 510 + (2 * 0) - 1) :) ).

**Comment by eveferon** [comment]
Confirmed. Currently our PW community is suffering quite a lot from it. Reason - in PVP world having no access to potions where Caster Level can be set differently to the default 10 is important. 

I will follow up with a small video to demonstrate the most painful (in our honest opinion) aspect from this series of oddities.

**Comment by Finaldeath** [comment]
Looks like it is basically wrong in this code (thanks to NWNX channels) https://gist.github.com/GoLoT/9855d81707fe2f688381f2f01821db4a

 - Doesn't check for an item or feat at all
 - Fall through logic assuming the "last spell cast" is same as "this spell cast"

Another bug in the code unrelated to the above is that AOE's should store the caster level properly on themselves so the "last spell cast" doesn't keep overriding it, but there is probably tons of code that is wrong about them I still need to dig into wheeeeeee \*sobs\*

**Comment by pF-arQon** [comment]
> Feats also need to apply what level is set in GetCasterLevel which appears - at least at first glance with the Harper and Blackguard spells - to be correct (prestige class level is used).

This has historically been very inconsistent: we've found that, as you say, it's *sometimes* correct - but even in the rare cases that it looks right when you first test, it later turns out to be broken after all depending on specifics like whether it's a PC or an NPC using the feat, and so on. You're MUCH better off using GetLevelByClass explicitly in the scripts for "feat spells" rather than trusting anything GetCasterLevel produces, ever.

**Comment by Finaldeath** [comment]
I've also been doing some testing of effects with just the in-game console - and it appears GetEffectCasterLevel() on effects applied outside any spell script also have a bug that they get the last caster level used.

Instead it should probably clear it or better yet we get a SetCasterLevel() function to override it (where needed, when a magical effect needs a proper dispel level) :)

**Comment by Christian-Vassallo** [comment]
Confirmed. I have the same problem too.

**Comment by Finaldeath** [comment]
Fixed in 36.
