### ISSUE TITLE
Creature window lacking information

### ISSUE THREAD

**Issue by Gsjlink3** [Beamdog/nwn-issues#213]
**To Reproduce**
Open or create creature

**Specifics**

 - Game build (e.g. 81.8193.16

**If needed, describe the bug**

Creature stats do not reflect equipment you put on them. You also cannot see attack bonus/attack and number of attacks. This makes designing/testing creatures tedious. It would be nice to have access to this information and even better, be able to override it (I think there is a variable switch for # of attacks).

If warranted, add videos/screenshots to showcase the issue.

**Comment by virusman** [comment]
This repository is for bug reports only. Please request features in the forum.
