### ISSUE TITLE
[8193.16] Global Faction Reputation changes when using a non-DM character as a DM avatar

### ISSUE THREAD

**Issue by Jorteck** [Beamdog/nwn-issues#216]
**To Reproduce**

 - Copy any standard, non-DM character file from a local/server vault into the dmvault (isDM=0 as an entry in their .bic)
 - Connect to a server using the DMC.
 - Observe faction reputation shifts using the `dm_getfactionreputation` console command. On a brand new module, this usually causes "Hostile" to become 100 (friendly) with all other factions.

**Specifics**

 - OS: Windows 10 64 bit
 - Game build: 8193.16
 - Distro platform: Steam
 - Content overrides: None
 - Regression: 8193.16, I think as a part of the Player DM feature.

**Comment by tinygiant98** [comment]
Resolved in .35.
