### ISSUE TITLE
[8193.9] Tile tno01_b70_01 - Bad Geometry (Fix Enclosed)

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#22]
Tile tno01_b70_01 has geometry out of place. I have uploaded a fixed version here:

[tno01_b70_01.zip](https://github.com/Beamdog/nwn-issues/files/4432573/tno01_b70_01.zip)

**Specifics**

 - Game build 8193.9
 - Windows 10
 - Steam

**Comment by Bill-Harper** [comment]
[tno01_b70_01.zip](https://github.com/Beamdog/nwn-issues/files/4540175/tno01_b70_01.zip)
Thanks for the handy tile, it made this a lot quicker. Only change I made was on the walkmesh, to change the vertical wall from non-walk to obscuring.
