### ISSUE TITLE
BUG - Resizing Placeables

### ISSUE THREAD

**Issue by PJHNWN** [Beamdog/nwn-issues#224]
**To Reproduce**

- Unzip the module and put it in the right directory.
- Load the module in the toolset.
- Notice there are 5 resized mushrooms using the toolset resizing function.
- Press F9.
- Notice the 5 resized mushrooms are not resized, but simply retain their original placeable size.

**Specifics**

 - Windows 10
 - v83.8193.21 (dgegc503)
 - Steam Development
 - Stock content
 - Regression? (Worked before .18 afaik, just recently updated to .21)

**If needed, describe the bug**

Non-static placeables resized in the toolset remain as such within the toolset, but revert to their standard footprint size when the module is loaded.

[BUG - Resizing Placeables.zip](https://github.com/Beamdog/nwn-issues/files/5644978/BUG.-.Resizing.Placeables.zip)

**Comment by BlittlePrime** [comment]
I can confirm.  I had this same bug independently within 28 minutes of this post.
