### ISSUE TITLE
Fire Giant sword is enormous - other giant creatures too have oversized weapons

### ISSUE THREAD

**Issue by calgacus** [Beamdog/nwn-issues#229]
**To Reproduce**

 - Load attached module, open first area.
 - look at the fire giant.
 - Sword is too big, as is the frost giant's hammer.  
- try other huge creatures like the Balor, same issue.

**Specifics**

 - Game build (e.g. 8193.21)
 

**If needed, describe the bug**
 Giant creatures have ludicrously oversized weapons.
mod link https://drive.google.com/file/d/1IY8JwpoPsQjiWvxxlRocz3wAN-TarFCL/view?usp=sharing
image https://drive.google.com/file/d/166dT5tJqp18nerk4an1dT1WgKNU19pPz/view?usp=sharing

The issue is apparent during play too not just the toolset.   I tested in the dev build 8193.19 (under my beamdog install) and the issue is not there.  I guess it started in 8193.20 (which I use under steam).  

OS  Windows 10.

**Comment by calgacus** [comment]
oversized sword still there in 4fe201ed - 15 Dec 2020 - 20:30Z
https://drive.google.com/file/d/1gHvBzjWJNiEcXd3vjoYgtFTlcNuy5bKY/view?usp=sharing

**Comment by pF-arQon** [comment]
sidenote: You might want to provide the images as part of the ticket, instead of uploading them to some random site that they will inevitably vanish from at some point in the future. That would also make the bug obvious to anyone looking at the ticket without putting the burden on them to go chasing your links.

**Comment by calgacus** [comment]
> sidenote: You might want to provide the images as part of the ticket, instead of uploading them to some random site that they will inevitably vanish from at some point in the future. That would also make the bug obvious to anyone looking at the ticket without putting the burden on them to go chasing your links.

ok, done.

**Comment by plenarius** [comment]
Can confirm same issue here on Linux latest preview (e0481881).

**Comment by Soren217** [comment]
Found the cause and will be corrected by next update. Thank you for reporting it.
