### ISSUE TITLE
[8193.9] Texture tno01_chain01 - Bad Alpha Channel (Fix Enclosed)

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#23]
Texture tno01_chain01 has a bad alpha channel that leaves a visible black line to either side of the chain. Fix enclosed:

[tno01_chain01.zip](https://github.com/Beamdog/nwn-issues/files/4432580/tno01_chain01.zip)

**Specifics**

 - 8193.9
 - Windows 10
 - Steam

**Comment by Bill-Harper** [comment]
[tno01_chain01.zip](https://github.com/Beamdog/nwn-issues/files/4540155/tno01_chain01.zip)

 Thank you for the report! I gave this a good cleanup, and resized by 2x using Photoshop's  Nearest Neighbor function & manual cleanup. This kept the chain links well-rounded yet didn't feather out the alpha channel, and quite frankly our textures are too small for 2020 standards anyways.

**Comment by Bill-Harper** [comment]
[tno01_chain01_b.zip](https://github.com/Beamdog/nwn-issues/files/4540318/tno01_chain01_b.zip)
I went a little further, and rounded off one of the link edges where it looked too squarish.
