### ISSUE TITLE
[8193.16] Feat.2da: Master Column set to same Feat Row as the Feat causes a Client Crash

### ISSUE THREAD

**Issue by Aschent89** [Beamdog/nwn-issues#231]
**To Reproduce**

- Open feat.2da
- Modify a feat that will be granted to a PC's "Master" column and set it to itself.
  - For example, modify "Alertness" feat's Master Column to: `0`.
- Open game
- Level up to the point that the PC receives the feat
- If feat is received via another way (nwnx for example), simply open the character sheet, navigate to the feats, and that should crash the client.

**Crash Dump**

- This is a lock-up crash, no .dmp is generated.

**Specifics**

 - OS: Windows 10
 - Game build: 8193.16
 - Distro platform: Steam
 - Repro Rate: 100%
 - Content overrides: Many custom content haks, however the fix was to modify the master column.

Although this is a mistake on the part of the user, it shouldn't result in a hard-crash of the client. Instead it should just not function, or even throw some kind of error rather than crash out completely. This issue had no impact on the server itself.

**Comment by Shad000w** [comment]
There is better. Set feat Successor to be feats's prerequisite feat and it results into endless loop and total server lockdown.

**Comment by tinygiant98** [comment]
For original gripe, check `nwruless.cpp:1094` and add check for `nInt == i` to skip that entry and maybe add a log warning (?).  FOr successor gripe, check `nwrules.cpp:1070` and check prereqs aren't `i`?

**Comment by tinygiant98** [comment]
This is a custom content issue and outside the scope of this repo.  Please visit <https://nwn.wiki/display/NWN1/feat.2da> and provide feedback on conditions that cause 2das to be invalid for inclusion in 2da descriptions.
