### ISSUE TITLE
[8193.16] Bug - packages.2da/classes.2da interaction

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#232]
**To Reproduce**

 - Add new class entry in classes.2da, set a Package that doesn't correspond to the classes.2da line
 - Add new entry in packages.2da; set to whatever you want.
 - Try to use Recommended options in-game when leveling up or choosing skills/feats/spells manually.

**Specifics**

 - OS (Windows, Mac, Linux): Windows
 - Game build: 8193.16 but likely started happening when changes to packages.2da were introduced
 - Distro platform (BDC, Steam, GOG): Steam/BDC
 - Content overrides? (Steam Workshop? Overrides? Patch haks?): No overrides, just editing classes/packages
 - Regression? (Build which broke it, if known): Unknown

**If needed, describe the bug**

When reproducing the steps above, the game will use the wrong package when players level up/create characters. Rather than referring to the line indicated under the column Package in classes.2da, it will refer to the line in packages.2da that corresponds to the class' line in classes.2da. Ie: if the class is on line 50 in classes.2da and the package on line 130 in packages.2da, it'll use the package information found at line 50 rather than 130. It works properly when a player picks the actual package at character creation (ie: Default XYZ) but not when they level up or if at creation they choose the Recommended option when picking skills, feats, spells, domains, etc. Haven't tested if it levels NPCs up correctly.

**Comment by Stratovarius667** [comment]
I'll add that this was a bug introduced by Beamdog when they made changes to how packages.2da and classes.2da interacted early on in the life of NWN:EE, and has never been fixed. It is a clear regression from Classic era content where classes.2da always accepted whatever was in the packages column.
