### ISSUE TITLE
[8193.20.1] Broken fullscreen mode

### ISSUE THREAD

**Issue by Taro94** [Beamdog/nwn-issues#233]
**To Reproduce**

 - Start the game (in fullscreen)
 - Hope the game launches
 - It launches and its music starts playing, but it's either black or still displaying your desktop
 - either:
   a) kill the process, turn off fullscreen in YAML and retry, or
   b) try alt + enter to turn off fullscreen (will randomly work or not)

**Specifics**

 - OS: Linux (Manjaro XFCE)
 - Game build: 7cb918c9, 8193.20.1
 - Distro platform: GOG and Steam alike
 - Content overrides: none
 - Regression: never happened in 8193.16 on GOG

**If needed, describe the bug**

At times it *may* launch successfully in fullscreen, or you may successfully alt-enter again from windowed mode into a working fullscreen, but then it works in the resolution of 1920x1051, with a black strip at the bottom (my native resolution is 1920x1080).
Also, alt + enter may freeze the game completely (with music still playing).

**Comment by B1gSea** [comment]
I have started encountering a similar bug described here but after I've launched, and for the current time seems to only happen when the window is not fully maximized (in windowed mode, and not displaced).

This happens some time after I've left the window inactive, but the game is still running, and the window just refuses to pop back up. I haven't tried any other maximize or alt+enter commands. I will try to replicate it a few more times.

Specifics

OS: W10
Game build: Preview Branch (41f2bb18)
Distro platform: Steam
Content overrides: --
Regression: Didn't happen in previous preview builds, but after I had tweaked some registry values that I now reset and the issue persists.
