### ISSUE TITLE
[8193.21] sqrt: DOMAIN error

### ISSUE THREAD

**Issue by PJHNWN** [Beamdog/nwn-issues#236]
**To Reproduce**

 - Load any stock module, such as To Heir is Human
 - Go to the creature palette and Edit Copy.
 - Move the mouse around.
 - Toolset returns sqrt: DOMAIN error
 - Continues to bring up sqrt: DOMAIN error whenever the mouse is moved

**Specifics**

 - Game build ( v83.8193.21 [ac45a6a7] )
 - Started to happen after updating Development build to .21

**If needed, describe the bug**

All attempts to see any creature, be it original NPCs or creatures, or even custom made ones, result in the appearance not being displayed and a sqrt: DOMAIN error popping up whenever the mouse is moved. *screen shot provided*

![sqrt1](https://user-images.githubusercontent.com/70107610/102723238-c2955a80-42d4-11eb-99b0-c9d12e0511b2.png)
![sqrt2](https://user-images.githubusercontent.com/70107610/102723355-3a638500-42d5-11eb-8658-f85c6e06f614.png)

**Comment by B1gSea** [comment]
Can confirm this is happening to me as well when trying to create just about anything like an item or creature. Same build as OP.

**Comment by virusman** [comment]
Thanks. We've identified and fixed the issue; it should be fixed in the next preview build.
