### ISSUE TITLE
EffectMovementSpeedXXX issues - Monk Bonus Speed and Initial Applications Don't Compute

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#239]
**To Reproduce**

 - Module download: [Jasperre Test Effect Variables.zip](https://github.com/Beamdog/nwn-issues/files/5756008/Jasperre.Test.Effect.Variables.zip)
 - Character download: [torutaramoku1.zip](https://github.com/Beamdog/nwn-issues/files/5756009/torutaramoku1.zip)

There are 2 bugs, both relating to the initial application of EffectMovementSpeedIncrease and EffectMovementSpeedDecrease (which seem to also be used for EffectHaste and EffectSlow).

**Bug 1**

Initial applications of the effects will multiply the existing movement speed factor, but not take into account the limit (1.5 for non-monks). This bug is easiest to test using the 2 left hand levers as a non-monk.
 - Load in as any non-monk non-barbarian
 - Select the lever marked "Apply Lots of Speed then Decrease 1" 
 - This should equate to a maximum speed (1.5) but instead you end up going 0.75 speed.
 - This can be tested using the running lever.
 - Reload the module (there are levers for this) 
 - Select the lever marked "Apply Lots of Speed and then One Decrease and remove a temp one"
 - This will "fix" the bug, it seems removing any movement speed change while under the effect of others will properly cap it to the bounded 0.125 - 1.5 min and maximums. In this case 5 increases should be capping at 1.5 speed increase, which it does.

Theory: The apply code just does "Get current factor * new factor" without checking all the existing factors, while the remove code goes "well lets check the existing factors".

**Bug 2**

Monks have another - maybe related? - bug. The effect code will not start with a factor of 1.0 (ie normal running speed) and add 1.3, meaning 2.3 total (the level 40 monks bonus speed with no effects). When an effect of speed change 0 is applied, instead it will for some reason take the initial factor as 2.3, then also apply the 1.3 bonus on top, going to 2.6. It gets even worse if an effect of higher magnitude is applied, since it will multiply the 2.3 by that number, eg; 2.3 * 1.5 (Haste) = 3.45 = capped to 3.0, +1.3 = 4.3

 - Load module with Monk supplied
 - Check the levers in order left to right, recommended to rest or restart between each one:
 - First will apply 0 increase, which should do nothing. Instead you speed along at 2.6 speed suddenly!
 - Second will apply a standard 150% increase (*1.5) but instead you end up as above at 4.3 speed
 - Third applies 300% increase (*3.0) which caps the monks speed - same as *1.5.
 - Fourth applies a "fix" similar to the first bug. It applies a 150% (*1.5) increase then a 0 one that is immediately removed. This then figures itself out and correctly has the right speed multiplier of around 2.8 (1.5 + 1.3).

**Specifics**

 - OS Windows
 - Game build 83.8193.21 3e84d2d3
 - Distro platform Steam
 - Content overrides? None
 - Regression? Seems to be a 1.69 present bug from accounts (not tested though)

**If needed, describe the bug**

Bugs as above. Copy the "remove speed change" code to the "apply speed change" code and it should fix it I'd hope.

Some other notes/oddities:
* Monks getting the crazy engine-breaking 300% cap for EffectMovementSpeedIncrease appears to be what was going to be the entire cap for their entire bonus + effects. Which would make a lot more sense than the current arbitrary maximum they randomly get and no other class (not even Barbarians) get, which then gets the bonuses applied on top! (so you can get up to 17meters/second movement, this can skip over triggers)
* Monks increments of 0.1 multipliers of movement appear to be the interpretation to have 10ft/round bonus per 3 levels, but this is off when used as an additive multiple when the run speed is 4.0. It's over 10ft/round. Adding on more multipliers messes up the maths a chunk. 

Basically Bioware's way of applying the bonus movement speed is weird no matter how you look at it, no wonder it causes so many issues, it never was meant to be this high even with the bugs.

Fix list would be:
* Fix so the proper caps are enforced when all magical movement speed changes are made (applying and removing, currently just removing) should fix both bugs at least when applying speed changes via. effects. It won't stop Monks breaking things though.

Wishlist would be a optional set of ruleset.2da additions to allow these behaviours to be tweaked and possibly SP be fixed by default:
* Monk increments per-3-levels option, and default to 0.1 (the game default) but could be tweaked to 0.93 (to be more like 10ft/round more in metric) or less (to be a bit more sensible)
* Optional toggle to have the monk bonuses add on rather than be bundled as multiplicative and same with Barbarian Endurance (again is meant to be a base rate change not multiplication of it)
* Monk Magical Movement Speed Cap (set to 3.0 currently, but should be 1.5 since no reason they get an exception)
* Non-Monk Magical Movement Speed Cap (set to 1.5 currently, and probably should stay matching whatever monks can get)
* Total Monk movement speed cap (not set at all currently it seems...so would be something big like 5.0, but then can be lowered to 3.0 or something sensible to stop breaking triggers)
* Total Non-Monk movement speed cap (set to 1.5 currently - Barbarian Endurance does nothing over the current magical increases if hasted for instance, so could be tweaked up to 1.6 to properly apply their bonus all the time)

**Comment by tinygiant98** [comment]
@Finaldeath do all the new ruleset.2da entries for movement speed management resolve this issue?

**Comment by Finaldeath** [comment]
Yes fixed the bugs associated with movement speed application as well.
