### ISSUE TITLE
[8193.9] Thieves' Hood UTI Has 50 Charges

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#24]
**Description**

The UTI for the Thieves' Hood has 50 charges set on the item, BUT none of the item properties have a charge cost. 

**Specifics**

 - 8193.9
 - Windows
 - Steam

**Comment by Bill-Harper** [comment]
[nw_armhe007.zip](https://github.com/Beamdog/nwn-issues/files/4551980/nw_armhe007.zip)
Thanks again for all the reports. This was an easy fix, clearly some oversight.
