### ISSUE TITLE
[8193.20.1] Off-Hand Inventory Slot Icon Doesn't Fill Entire Slot Graphically

### ISSUE THREAD

**Issue by Clockwerkd** [Beamdog/nwn-issues#240]
**Description**

When viewing a creature's inventory in the toolset, the off-hand slot exhibits white bars or border when slot is occupied.

**To Reproduce**

1. Select a creature from the Creatures Palette, and open its properties.
2. View the creature's inventory.
3. Equip an item in the creature's off-hand slot such as a shield
4. Resulting icon will not fully fill the slot leaving white bars or a border.

**Specifics**

8193.20
Windows 10
Beamdog

![image](https://user-images.githubusercontent.com/52304166/103445261-6ff26180-4c37-11eb-851e-30b8682f35d4.png)

**Comment by virusman** [comment]
Thank you. This should be fixed in one of the next buils.
