### ISSUE TITLE
[8193.16] Crash on module load with a module.sq3 file

### ISSUE THREAD

**Issue by Taro94** [Beamdog/nwn-issues#242]
**To Reproduce**

 - Pack a module.sq3 database file in the module
 - Try to launch the module
 - Game crashes

**Specifics**

- Game build: 8193.16
- OS: Linux (Manjaro XFCE)
- Distro platform: GOG
- Content overrides: none
- Regression: -

**Notes**

[stuff.zip](https://github.com/Beamdog/nwn-issues/files/5762258/stuff.zip)

Crash log and the module.sq3 file I used are attached. I don't have either the newer stable (8193.20) nor the preview patch installed due to issues #233 and #235 present in both these versions. As such, I could only test it on the old stable, .16, but I haven't seen anything in the patch notes suggesting it's either fixed or a known issue.

**Comment by Finaldeath** [comment]
@Taro94 is this still an issue?

**Comment by Taro94** [comment]
@Finaldeath  No, it's been fixed for a long while now.
