### ISSUE TITLE
Placeable Torch 01 no longer gives off light when set to Activated

### ISSUE THREAD

**Issue by PJHNWN** [Beamdog/nwn-issues#244]
**To Reproduce**

 - Load the supplied test module either in-game or the toolset.
 - Although set to Activated, the torch gives off no illumination as it once did in previous versions before .20
 
**Specifics**

 - Windows 10
 - v8193.20.1 [7cb918c9]
 - Steam
 - Stock, no haks.
 - Prior to .20 stable, placeable appearance Torch 01 illuminated when set to Activated.

**If needed, describe the bug**

The placeable Torch 01, when set to Activated, no longer gives off illumination as it did prior to the stable .20 patch.
An example Torch 02, also set to Activated, shows what Torch 01 used to look like when set to Activated.
In the toolset, turn on Area Lighting to blackout the tile, or simply load the module in-game.
The broken Torch 01 is on the left side, the working Torch 02 is on the right side, both set to Activated.

[BUG - Torch01.zip](https://github.com/Beamdog/nwn-issues/files/5777542/BUG.-.Torch01.zip)

**Comment by virusman** [comment]
Is this limited to one placeable, or applies to all placeables with illumination?

**Comment by PJHNWN** [comment]
Hi there.

As far as my experience goes, it is only Torch 01 as this is the placeable I've used since 1.69, but sleuths on Discord have mentioned that this will be any placeable that offered illumination with radius 0 in the .mdl file.

torch01 placeable -

    node light torch_light12
        parent base
        #part-number 6
        flareradius 0
        lightpriority 2
        ambientonly 0
        nDynamicType 1
        affectdynamic 1
        shadow 1
        generateflare 0
        fadinglight 1
        position 0 0.110051 2.25
        orientation 0 0 0 0
        radius 0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        color 0.941177 0.788236 0.172549
    endnode


Torch 02 placeable -

  node light nwnlight
        parent bracket
        #part-number 7
        flareradius 0
        lightpriority 5
        ambientonly 0
        nDynamicType 1
        affectdynamic 1
        shadow 1
        generateflare 0
        fadinglight 1
        position -0.00439512 -0.206833 0.61323
        orientation -0.577349 -0.577354 0.577349 2.09439
        radius 14 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
        color 0 0 0
    endnode
