### ISSUE TITLE
RDD / Dragon Disciple level up bug on level 9 when spending all skill points

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#245]
**To Reproduce**

 - Make a character with 8 levels of RDD (red dragon disciple)
 - Attempt to level up to RDD level 9 while spending all available skill points
 - The Game will reject your level up for spending too many skill points
 - Saving one skill point and spending it in a future level up will workaround the issue

**Specifics**

 - OS  Client: Windows 10, Server Linux, or Single  player Windows 10
 - Game build 8293.20.1
 - Distro platform (BDC and/or Steam)
 - Content overrides? None
 - Regression? Yes, compared to v1.69.  I suspect the issue relates to the unhardcoding of RDD stat gain, specifically INT, around patch 1.79

**If needed, describe the bug**

I had assumed this was an MP/ELC issue only, but I just helped someone claiming to be playing HotU Single player in Discord who was having trouble levelling up to RDD9. (Neverwinter Nights #builds channel: https://discord.com/channels/255801192263843840/346245671344537600/796609221386436608 ).  We identified this issue on our server over the 2020 Christmas break; we just migrated from v1.69.

If warranted, add videos/screenshots to showcase the issue.

**Comment by pF-arQon** [comment]
> I suspect the issue relates to the unhardcoding of RDD stat gain

ISTM it's more that the INT is now provided prior to finishing the levelup, but this new mid-game ELC just isn't aware of it. The NORMAL ELC, on login, DOES correctly accept that the char gained 6 skillpoints in those 2 levels, so it looks like that one got updated for it.

**Comment by shadguy** [comment]
Thank you for clarifying the level-up validation vs server login ELC.  Good point.

FYI, I have reports of hit point discrepancies for RDD level-up too.  I need to internalize that and will file a separate report; I don't know if it's due to +CON bonus, RDD HD evolution, or some combo.

-Dave

**Comment by calgacus** [comment]
Here is a saved game with that problem ready to test: https://drive.google.com/file/d/1XrAxiTWvQwvEs97hhilbyDL2Z9pwcpsF/view?usp=sharing

**Comment by Finaldeath** [comment]
Note on this issue; the 1.69 behaviour is to provide the intelligence (or other stat bonus) after levelup - ie not as a way to grant new skill points during levelup.

The D&D rules (at least for 3.5E) state "These increases stack and are gained as if through level advancement." thus since level advancement ability score increases do count for prereqs, skill point additions etc. that level, it makes sense to just change the validator to have +1 skill point acknowledged as valid.
