### ISSUE TITLE
[8193.20.1] Water Shader issue with annimesh model nodes (vs trimesh)

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#247]
**To Reproduce**

- Download the attached demo zipfile include an NWN module and a pair of txi files.  [Water Shader Animmesh Demo.zip](https://github.com/Beamdog/nwn-issues/files/5789813/Water.Shader.Animmesh.Demo.zip)
- place the provided .txi files in your development folder 
- Download/install CTP Babylon in your hak dir, available here: https://neverwintervault.org/project/nwn1/hakpak/tileset/ctp-babylon

- Load the attached Module, running 8193.20.1 (windows 10, BDC).  
- Demo 1: Look north to the boat and how the water looks in the boat tiles (using animmesh) vs other water bits (trimesh models)
- Demo 2: Look West/South to where the water interacts with cliffs.  

**Observations**
- When I dig into the models, it looks like tiles using animmesh nodes don't pick up the EE fancy shader water
- I can literally text edit an ascii model of affected tiles to search and replace animmesh with trimesh to fix it, but a proper fix requires more skill with modelling
- It's entirely possible something else is going on and I'm out of my element in the model understanding. :)
![Water Shader Animmes_0000](https://user-images.githubusercontent.com/38797333/104076627-3fcd3480-51dc-11eb-8b63-7af268bec1a7.png)
![Water Shader Animmes_0002](https://user-images.githubusercontent.com/38797333/104076633-4360bb80-51dc-11eb-814c-921189043ffe.png)

**Specifics**

 - OS (Windows)
 - Game build (8193.20.1)
 - Distro platform (BDC)
 - Content overrides? (only the specified custom tileset hak and provided txi files)
 - Regression? I don't know if this is a regression.  We just migrated our server from v1.69 and noted the issue.

**If needed, describe the bug**

Water modeled with animmesh nodes retains the legacy look, rather than picking up the awesome beautiful EE shiny water.  CTP Babylon is a good testcase as it presents a mix of animmesh & trimesh water modelling, for whatever reason.  Other popular custom tilesets that I have reports of this behavior with include:

- Sen's Terria (Original) - https://neverwintervault.org/project/nwn1/hakpak/tileset/phod-s-e-n-terria
- Illmater/CODI Daggerdale Swamp - https://neverwintervault.org/project/nwn1/hakpak/tileset/codi-daggerdale-swamp-set

I haven't added demos of these other tilesets, but am happy to test around if updates become available.

**Comment by shadguy** [comment]
FYI, on merricksdad's suggestion in the vault #customcontent Discord channel, I tried creating an mtr for these issues with these contents:

> customshadervs vswater
> customshaderfs fswater

This seems to solve most of my water texture on animesh issues.   I have edge cases, but they appear to be isolated to a few tiles here and there, and I think I need to own those as they're custom content from the vault, rather than BeamDog content.

However, my result seems to surprise merricksdad, so he thinks there may be value in further understanding what's going on.  There's some related debug happening in Discord today between he and LuckyDay on some of Lucky's art assets. I didn't realize the discussion was even related, but merricksdad is more talented in this art than I am (understatement), and is seeing some dots connect, so I'm leaving the issue open for now and inviting him to comment further.

If yall close it until we can better identify an issue, that's ok, too, I suppose.  I'm being a bit wishy washy due to my background being not super strong in this department yet.

-Dave

**Comment by shadguy** [comment]
FYI, a Discord user in the vault #builder-scripter channel reported this ?base tile? issue, reportedly without any haks.  IT looks like a problem with an underdark tileset tile.  

![image](https://user-images.githubusercontent.com/38797333/106925912-25508300-66d6-11eb-88ad-0dbfa2a8bb75.png)

Discord ref link:  https://discord.com/channels/255017439371329537/467392331188928513/806903686692339713

-Dave

**Comment by Soren217** [comment]
![marooned](https://user-images.githubusercontent.com/23218750/107120346-68a12200-688d-11eb-968e-9e977a05b020.jpg)

Think I managed to fix the animmesh part (or well, _did_, but hopefully not creating other issues).

The Underdark issue seems to be an issue with the specific model though.

**Comment by shadguy** [comment]
Soren, thanks!  

FYI, I've done some digging around - the underdark tile looks like ttu01_b02_01 to me, but I'm not seeing the issue in 8193.20.1.  I'm not sure if it's worth getting hung up on.

-Dave

**Comment by ElGrillo42** [comment]
Sadly Soren it looks like your fix for the animmeshes has not worked for the Sea Cliffs tiles in TNO01 tileset ('Castle Rural, Exterior') - I tried it on 8193.23 and the attached screenshots show the old-style water at the bottom of the sea cliffs.
![Desktop Screenshot 2021 05 16 - 14 10 41 71](https://user-images.githubusercontent.com/77232907/118398699-b201ca00-b651-11eb-81d2-19db3019eb00.png)

Here you can see on the left the old-style water on the 'Sea Cliffs' tiles (which use Animmesh for the water), whereas there is the new-style shiney water applying to the 'Lake/Moat' tiles (which use Trimmesh for the water):
![Desktop Screenshot 2021 05 16 - 14 06 11 62](https://user-images.githubusercontent.com/77232907/118398723-d2ca1f80-b651-11eb-9ba6-1c2c473f86de.png)

**Comment by Clockwerkd** [comment]
This still appears to be an issue in build 8193.33. The water in the sea cliff tiles does not render with the new shiny water.
