### ISSUE TITLE
NWN:EE Toolset | Tabs Glitch and are Unusable

### ISSUE THREAD

**Issue by whimsicaljoey** [Beamdog/nwn-issues#249]
**To Reproduce**

 - Open Toolset through Steam.
 - Load either a clean module or one with HakPaks.
 - Attempt to use palettes.
 - Text overlaps, tabs do not close properly, scrolling within textboxes does not work.

**Specifics**

 - Windows 10, Dell G5s laptop.
 - Latest
 - Steam
 - With CEP and Hakpaks, as well as without.
 - Regression? Did not happen on my old laptop.
 
![Picture1](https://user-images.githubusercontent.com/77301034/104237419-0a1b8c00-5426-11eb-9036-98a16f4b886b.png)

**Comment by virusman** [comment]
Does it happen if you open nwtoolset.exe directly, without Steam?
