### ISSUE TITLE
[8193.9] TNO01 Tile tno01_v00_09 - Wrong Ground Texture

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#25]
**Description**

Tile tno01_v00_09 (Ice Cellar) has the wrong ground texture. Currently the tile is using tno01_dirt03. It should be using tno01_grass.

**Specifics**

 - Game build 8193.9 
 - Windows 10
 - Steam

**Comment by Bill-Harper** [comment]
[tno01_v00_09.zip](https://github.com/Beamdog/nwn-issues/files/4540207/tno01_v00_09.zip) Sorry for this one; I had a wrong texture reference in my Max file somehow, missed it last export. Should be good now.
