### ISSUE TITLE
AIActionAttackObject bug

### ISSUE THREAD

**Issue by BhaalM** [Beamdog/nwn-issues#256]
**To Reproduce**

 - Change the PrefAttackDist value of a weapon on baseitems.2da to, let says, 5.0 
 - Play a module (with the change you made in baseitems.2da)
 - Grab the weapon you changed and attack an armor stand (something that cannot move)
 - The PC gets stuck and do nothing

**Specifics**

 - OS (Windows, Mac, Linux): Linux
 - Game build (e.g. 8193.8, or commit hash) 8193.20.1
 - Distro platform (BDC, Steam, GOG) BDG
 - Content overrides? (Steam Workshop? Overrides? Patch haks?) just the baseitems.2da
 - Regression? (Build which broke it, if known) I think it has always been like this

**If needed, describe the bug**

- The AIActionAttackObject calls (at the beginning) the MaxAttackRange and the DesiredAttackRange function. 
- Note that the first one is called with bBaseValue parameter set to 1 and the second one with bBaseValue set to 0
- The logic of the function checks then if the creature is in range with the target using the MaxAttackRange distance
- If not, it will try to move to a "closer" location at PrefAttackDist distance

Since the PrefAttackDist is called with bBaseValue set to 0, it could happen that instead of getting closer you are moving away. And the creature get stuck doing nothing.

**Comment by BhaalM** [comment]
**Update:** 

The same thing happens if the attack is passive (AoO, cleave,...)

**Some numbers**

- Human (appearance.2da): preferred attack distance is 1.7, weapon scale is 1, hit distance is 0.3
- Great sword (baseitems.2da): preferred attack distance is 1.8

So, if two humans are fighting each other:

- Base desired attack distance is 1.7 + 0.3=2.0
- Base MAX attack distance is: 2.0 + 1.5=3.5
- No base desired attack distance is: 1.8x1 + 0.3=2.1
- No base MAX attack distance is: 2.1 + 1.5 = 3.6

No problem in this case (Base MAX attack distance is greater than "no base" desired attack distance) 

Suppose now you increase the great sword preferred attack distance by 1.5, i.e., to 3.3. The only numbers that change are those that depend on weapons, that is, the "no base":
- No base desired attack distance is now: 3.3x1 + 0.3=3.6
- No base MAX attack distance is: 3.6 + 1.5 = 5.1

In this case, the engine will check if you are at a distance less than 3.5 (base max attack distance) and if this is NOT the case it will move you to a distance=3.6 (no base desired attack distance) so you may be even moving away instead of getting closer, and you get stuck in this loop.

**Comment by Soren217** [comment]
Good find! It's intertwined with a lot of other elements however, but trying to untangle it.
