### ISSUE TITLE
[8193.20.1]  Journal Quest Entries not retained on relogging into an MP server

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#258]
**To Reproduce**

 - Start nwserver with the attached module.  Make sure you DO NOT check "Reload When Empty".   
[JournalTest.zip](https://github.com/Beamdog/nwn-issues/files/5899537/JournalTest.zip)

 - Join the server with your favorite test character
 - Pull the lever in front of you - a quest is entered into your journal
 - Log off and re-log on with the same character
 - Your Journal is now blank - the journal entry has been lost
 - ##DM_Dumplocals will show the quest vars are set on your character (per screenshot)

**Specifics**

 - OS (W10 running lcoally.  We see the same behavior with W10 client on linux server ubuntu 18.04 LTS).
 - Game build - stable 8193.20.1
 - Distro platform (BDC)
 - Content overrides? (No.  See attached module)
 - Regression? (Yes.  In v1.69, quest entries are retained on relogin.  Based on Discord chatter, I think the bug was introduced in 8193.14.  We only migrated in December of 2020, after 8293.20 went stable, so I may be wrong.)

**If needed, describe the bug**

Journal entries should be retained when players log off and relog in, or crash and rejoin an MP server, etc.  Some other PWs work around this by always reloading all quest states from DB on each login, and using bAllowOverride.   We have some quests we allow to be repeated After a reset, so this approach doesn't work for our world.

Screenshot below shows a character having rejoined the server after activating a quest.  The journal is blank, but journal variables are present.

![image](https://user-images.githubusercontent.com/38797333/106381263-23f12480-637d-11eb-99cf-7808d85e6acb.png)

**Comment by Shad000w** [comment]
bump still happens in .34
