### ISSUE TITLE
Area Tabs that are open relay audio from those areas in response to camera position changes

### ISSUE THREAD

**Issue by Baaleos** [Beamdog/nwn-issues#260]
**To Reproduce**
Create an Area - Call it area A
Create an Area - Call it area B
Place a placeable sound effect in area A - Make it something like 'Magic Crystal- Water' or something.
Move camera away from the crystal - so you cannot hear it play.
Move to tab for Area B
Move camera around in Area B 
 

**Specifics**

**If needed, describe the bug**

Basically- when you do the above - you will see that you can get phantom audio seemingly appearing in Area B, but it is actually coming from Area A. It can be somewhat confusing - as the audio you hear from area A, is changing in volume according to camera position in Area B - Making one think that they are hearing some hidden sound effect.

When it happened to me - I thought there was a tile on the tileset somehow making audio - I thought it was as new feature... that tiles themselves could manufacture audio.

Expected behaviour: I would not expect to hear audio from Area A - if I am working in Area B, and I certainly would not expect Area A to change its audio based on camera movements in Area B.

**Comment by virusman** [comment]
@Baaleos Do you have a repro module?

**Comment by Baaleos** [comment]
Will see if I can create a repro module tonight. It was easy to do back when I posted this bug. 
In essence- it seems that the audio listener for the camera seems to pick up audio from all open tabs using the X,y,Z position from the camera- regardless of what tab is active. So moving the camera in tab A to a certain position will then pick up audio in range in both tab A and tab B.

**Comment by Baaleos** [comment]
On retesting on the latest version, I can see that the issue appears to be resolved.
