### ISSUE TITLE
Incorrect Param2 Value in line 525 of progfx.2da

### ISSUE THREAD

**Issue by Balanor** [Beamdog/nwn-issues#263]
**To Reproduce**
1. Put this in a module's OnEnter event:
`ApplyEffectToObject(DURATION_TYPE_PERMANENT, EffectVisualEffect(VFX_DUR_AURA_PULSE_PURPLE_BLACK), GetEnteringObject());`
2. Login and note that the pulsing color applied to the PC is glowing green to black, rather than purple to black, as noted in the left hand side of the screenshot below.

This is occurring because the Param2 value for line 525 in progfx.2da is 1.0 when it should be 0.0. Using the attached progfx.2da with the corrected value will result in the (correct?) pulsing purple glow on the righthand side of this screenshot. 
![image](https://user-images.githubusercontent.com/36014329/108887880-66023480-75d0-11eb-9e60-8286704f3bc4.png)

**Specifics**
 - Windows
 - 8193.20.1
 - Steam
 - Content overrides? Fixed progfx.2da (attached)
 - Regression? Seems to have occurred when progfx.2da was released in the 8193.14 patch. 

[progfx.zip](https://github.com/Beamdog/nwn-issues/files/6031058/progfx.zip)

**Comment by shadguy** [comment]
Minor typo in your report:  you changed Param2 to 0.0, rather than Param1.

-Dave

**Comment by Balanor** [comment]
Thanks shadguy - I corrected both the issue title and details section to Param2.
