### ISSUE TITLE
EffectDamage nDamagePower, Damage Penetration Bug

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#265]
**To Reproduce**

 - Load any module
 - Apply this script in the script debug panel:

`ApplyEffectToObject(DURATION_TYPE_PERMANENT, EffectDamageReduction(1000, DAMAGE_POWER_PLUS_TWO), OBJECT_SELF);
ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(1, DAMAGE_TYPE_BLUDGEONING, DAMAGE_POWER_NORMAL), OBJECT_SELF);
ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(1, DAMAGE_TYPE_BLUDGEONING, DAMAGE_POWER_PLUS_TWO), OBJECT_SELF);
`
 - Note there is 0 damage applied when there should be 1 damage applied (the one from DAMAGE_POWER_PLUS_TWO)

![image](https://user-images.githubusercontent.com/6137144/109435377-23968880-7a12-11eb-9e95-9234f4b1a9e0.png)

**Specifics**

 - OS Windows
 - Game build 8193.21 (7cd8c728)
 - Distro platform Steam
 - Content overrides? None
 - Regression? Has been like this since time immaterial

**If needed, describe the bug**

The bug appears to be that the nDamagePower is being saved but not being used later on in the "apply damage" engine functions and just ignored. This might be since the damage isn't from "a weapon". Since you can't pass in parameters into EffectDamage that make it "weapon damage" it won't work.

Some minor further notes here; https://nwnlexicon.com/index.php?title=EffectDamage

This would be somewhat of a gameplay change it'd finally mean you could have physical damage properly penetrate in spells and abilities, something Bioware seems to have assumed works but never fixed it to work. The only Bioware scripts that use physical damage which would affected are:
 - Evards Black Tentacles uses DAMAGE_POWER_PLUS_TWO
 - "Hurl Rock" (for Shifter polymorph into giant ability) uses DAMAGE_POWER_PLUS_ONE
 - Psionics: Mass Concussion Mindflayer Ability uses DAMAGE_POWER_ENERGY
 - "Bolt: Shards" uses DAMAGE_POWER_PLUS_ONE
 - Arcane Archer abilities should use the penetration of the bow weapon equipped (and is probably the biggest change) but don't, making them sometimes quite...useless.

**Comment by pF-arQon** [comment]
It's always been like this. DAMAGE_POWER_XYZ hasn't worked since at least HOTU (possibly earlier, but I wasn't testing this stuff back then) - damage applied by a script is ALWAYS as "+0".
