### ISSUE TITLE
[PREVIEW 2021-03-07] Large parts of the screen goes missing.

### ISSUE THREAD

**Issue by julien-lecomte** [Beamdog/nwn-issues#270]
**To Reproduce**

- Setup is set to windowed mode because of bug : https://github.com/Beamdog/nwn-issues/issues/211
- Install latest preview.
- "Lighting enhanced" is enabled
- "Enable sharpen" is enabled

**Specifics**

 - Linux Debian 10. GeForce GTX 970, nouveau drivers
 - Preview version of 2021-03-07
 - Steam distribution
 - Overrides: Statue Overhaul, Loadscreens with artwork, Magic The Gathering Portraits, High resolution damage numbers, NWN Font Override, Enhanced Great Axes (+ others), Prestige Spellbook Pack, CEP, Quality Fantasy Portrait Pack.
 - Regression? YES, from .20 version

**Describe the bug**

- When only turning off "Lighting enhanced", the black zones flicker.
- When only turning off "Sharpen", the black zones seem to disappear.

**Comment by julien-lecomte** [comment]
![Screenshot_2021-03-07_09-49-25](https://user-images.githubusercontent.com/1992050/110234780-bb253b00-7f2c-11eb-9d95-0e5dbd9b1fc0.png)
![Screenshot_2021-03-07_09-50-48](https://user-images.githubusercontent.com/1992050/110234782-bc566800-7f2c-11eb-93c2-b727c4bdebd1.png)

**Comment by julien-lecomte** [comment]
Tested with and without workshop files (`sudo chmod 000 workshop` to disable all of them). Issues remains.
Workaround is to disable Sharpen

**Comment by Soren217** [comment]
Could you try with these two shaders in your override:

[sharpen_override.zip](https://github.com/Beamdog/nwn-issues/files/6155155/sharpen_override.zip)

?

Thanks!

**Comment by julien-lecomte** [comment]
I've unzipped and put the files in the "ovr" folder, where there was already the same named files. The "ovr" folder is at the same level as "bin" and "data". Can you confirm this is the correct folder?

I haven't seen any change with my priest character.

**Comment by julien-lecomte** [comment]
I've tried with the two shaders in the ./ovr folder of the Steam version.

They did not change the issue, no improvement, no degration.

Of note, https://github.com/Beamdog/nwn-issues/issues/277 seems is problematic for me as there are no known workarounds.

**Comment by Soren217** [comment]
ovr works, but the best solution is using /override in your user folder.

Could you try this one instead?
[sharpen_fix.zip](https://github.com/Beamdog/nwn-issues/files/6183473/sharpen_fix.zip)

**Comment by julien-lecomte** [comment]
Yes!
This fixes this issue.
