### ISSUE TITLE
EffectSpellFailure Overriding and Removing Issues, and default subtype

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#273]
**To Reproduce**

 - Load any module with a mage such as our glorious default character Aluvian. I'd recommend a handy effect testing module (oh look! here is one :D  [Jasperre Test Effect Variables.zip](https://github.com/Beamdog/nwn-issues/files/6109755/Jasperre.Test.Effect.Variables.zip) )
- Open the nwscript and select yourself
- Run this script:

```
ApplyEffectToObject(DURATION_TYPE_PERMANENT, EffectSpellFailure(100), OBJECT_SELF);
```

 - Try testing a spell and note that it should say "Spell failed!" correctly
 - Bug 1: Try resting - if you rest the effect is not removed. Note the subtype is "0" meaning "not set" or "engine only" (ala skills like Taunt or feats like Knockdown use). The effect should default to SUBTYPE_MAGICAL which is removed correctly on rest.

 - Remove all effects or reload the module you're using
 - Try this script:
```
ApplyEffectToObject(DURATION_TYPE_PERMANENT, EffectSpellFailure(100), OBJECT_SELF);
ApplyEffectToObject(DURATION_TYPE_PERMANENT, EffectSpellFailure(0), OBJECT_SELF);
```
 - Bug 2: Try casting a spell - you can do so even though you have 100% failure. This is likely because the second effect simply overwrites any previous effect.

 - Remove all effects or reload the module you're using
 - Try this script:
```
ApplyEffectToObject(DURATION_TYPE_PERMANENT, EffectSpellFailure(100), OBJECT_SELF);
ApplyEffectToObject(DURATION_TYPE_PERMANENT, EffectSpellFailure(100), OBJECT_SELF);
RemoveEffect(OBJECT_SELF, GetFirstEffect(OBJECT_SELF));
```
 - Bug 3: One of the two effects is removed. You can see the remaining effect in the effect testing module debug. Note that casting a spell doesn't fail, it appears removing any EffectSpellFailure causes the amount to reset to 0 even if existing effects exist for it. The effect icon also disappears in spite of the other identical effect still being present.

**Specifics**

 - OS Windows
 - Game build 8193.21 [deb4b768]
 - Distro platform Steam
 - Content overrides? None
 - Regression? No

**If needed, describe the bug**

As above, the effect should:
 - Be magical by default, not subtype 0
 - When applied look at all existing effectsl, oop them all and set the effect spell failure amounts based on what now exists. They should stack.
 - When removed the existing spell effect failures should be rechecked and any applied if applicable now. Again they should stack.

The amount of spell failure should be additive in D&D - 50% + 20% = 70% failure. God knows how this interacts with Arcane Spell Failure however. Does it? Not sure it should mind you if it doesn't already; ala this 3E spell: https://dndtools.net/spells/players-handbook-ii--80/mana-flux--2913/ so you'd end up with ASF roll if applicable then a Spell Failure roll.

If this is fixed btw, it'd be great to have EffectDeaf use it rather than the current Arcane Spell Failure it uses.

One other minor thing; the values applied to this effect are not capped but seem to be limited to 255. It's useful to be able to set negative values, since you could have a power to counter such effects, if it was fixed fully. So this doesn't need fixing as such!

**Comment by pF-arQon** [comment]
> If this is fixed btw, it'd be great to have EffectDeaf use it rather than the current Arcane Spell Failure it uses.

Heartily agree. The current behavior of Deafness causing spell failure but ONLY for Arcane casters is very undesirable.

wrt ASF vs "Unequivocal Spell Failure", I do think it's important that they remain completely separate. It's extremely valuable having an effect that can't be nerfed or trumped by -ASF items, and Deafness in particular needs to use the correct "USF" form.

(sidenote: I have a vague recollection that Deafness actually stacks with ITSELF, escalating *A*SF to e.g. 40% and higher, which is obviously wrong, but I don't trust my memory enough to say for sure if that's really the case: I'd have to re-test first).

**Comment by Finaldeath** [comment]
Fixed in 35 except the default subtype which might be left as invalid due to some official modules making assumptions.
