### ISSUE TITLE
EffectRegenerate and Negative HP == Bad Times

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#275]
**To Reproduce**

 - Load effects testing if you want, or any module really, choose a low HP character: [Jasperre Test Effect Variables.zip](https://github.com/Beamdog/nwn-issues/files/6123154/Jasperre.Test.Effect.Variables.zip)
 - Use this script in the nwscript debug panel on yourself:

```
ApplyEffectToObject(DURATION_TYPE_PERMANENT, EffectRegenerate(-1, 6.0), OBJECT_SELF);
ApplyEffectToObject(DURATION_TYPE_INSTANT, EffectDamage(1), OBJECT_SELF);
```
 - See your HP go down to negative with the feedback: "Character: Healed -1 hit points."
 - Once 0 or lower you can still move around but are marked as Dead and then at -11 it heals to 1 and starts going to 0 again...and various buggy half-dead behaviour (can't use things but can do some things, etc.)

![image](https://user-images.githubusercontent.com/6137144/110792506-686cbb80-826b-11eb-9493-f6bcebc44d56.png)

**Specifics**

 - OS Windows
 - Game build 83.8193.21 [78a4a24d]
 - Distro platform Steam
 - Content overrides? None
 - Regression? No

**If needed, describe the bug**

nAmount in EffectRegenerate needs to be clamped to either a minimum of 0 (which does "work" it just says "Healed 0 hit points") or a minimum of 1, and return EFFECT_INVALIDEFFECT if it sees these values.

I presume this bugs out similarly to how SetCurrentHitPoints would if it allowed setting to 0 from 1 HP.

**Comment by tinygiant98** [comment]
@Finaldeath You did a lot of effect with recently.  Is this still an issue?

**Comment by Finaldeath** [comment]
Yes fixed in dev. I'll link the PR.
