### ISSUE TITLE
[Crash] Development Build 8193.21 - Game start crash!!! (T___T)

### ISSUE THREAD

**Issue by LiarisFreeze** [Beamdog/nwn-issues#276]
I can't start the game. The game crashes at the start.

![Безымянный](https://user-images.githubusercontent.com/46865150/110990185-08b60380-8384-11eb-9336-0a19c5c24d31.png)

[nwmain-crash DMP and LOG.zip](https://github.com/Beamdog/nwn-issues/files/6132597/nwmain-crash.DMP.and.LOG.zip)

Windows 7
Steam version
Development Build 8193.21

**Comment by LiarisFreeze** [comment]
The problem was that my username in windows is written in Cyrillic.

**Comment by niv** [comment]
Thanks. The game currently doesn't target Cyrillic languages, and Windows 7 unfortunately is also not on the supported list anymore.
