### ISSUE TITLE
[81.8193.21] Blackish square over some PC's

### ISSUE THREAD

**Issue by julien-lecomte** [Beamdog/nwn-issues#277]
**To Reproduce**

Reproduceable with at least one of my PC's on RoUM module with the .21 dev build.

- [priest.bic.gz](https://github.com/Beamdog/nwn-issues/files/6133488/priest.bic.gz)
- [Ruins of Undermountain.mod.gz](https://github.com/Beamdog/nwn-issues/files/6133493/Ruins.of.Undermountain.mod.gz)

**Specifics**

 - Debian Buster, GeForce GTX 970, nouveau drivers
 - Steam
 - Content overrides? Disabled.
 - Regression? YES.

![Screenshot_2021-03-12_23-34-28](https://user-images.githubusercontent.com/1992050/111007157-7830f080-838e-11eb-907b-029aa307c191.png)
![Screenshot_2021-03-12_23-44-45](https://user-images.githubusercontent.com/1992050/111007158-78c98700-838e-11eb-9351-c8bc016bb6c1.png)

https://youtu.be/Oc97Xzevlg4

**Comment by julien-lecomte** [comment]
![Screenshot_2021-03-13_10-30-17](https://user-images.githubusercontent.com/1992050/111025845-32544680-83e7-11eb-8acd-3d92ad58a9da.png)

**Comment by julien-lecomte** [comment]
![Screenshot_2021-03-13_10-32-48](https://user-images.githubusercontent.com/1992050/111025899-7c3d2c80-83e7-11eb-8cfb-258723ad1b49.png)

The thingy square seems to always be parallel to an equipped hand 1 or 2 item.

**Comment by julien-lecomte** [comment]
I believe that the issue depicted here (multi color squares) is part of this issue too. This square can appear when actively clicking down on the floor to walk to that point. As soon as click is released, the square disappears.
![Screenshot_2021-03-14_10-42-44](https://user-images.githubusercontent.com/1992050/111064041-3a2ced00-84b2-11eb-8fda-cc857a903f05.png)

**Comment by julien-lecomte** [comment]
![Screenshot_2021-03-14_10-45-20](https://user-images.githubusercontent.com/1992050/111064092-6ba5b880-84b2-11eb-8ef0-d14c190773e5.png)

**Comment by Soren217** [comment]
Very strange. It's like some geometry isn't uploading - or well, is uploading but as a square, which makes it even stranger.

Is anyone else able to reproduce this?

**Comment by Soren217** [comment]
Any luck with updating the drivers?

And are you by chance playing with enhanced lighting disabled? And if so, does enabling it (and restarting the game) alleviate the issue?

**Comment by julien-lecomte** [comment]
I'll be doing that this weekend.

Enhanced lighting enabled/disable (with restarts) does not alter the issue. No improvement, no degradation.

**Comment by Soren217** [comment]
Oh, another question: have you experienced this in other modules?

**Comment by julien-lecomte** [comment]
I didn't take the opportunity to test on another module; I only play one.

Remembering the hell that was installing the nvidia proprietary drivers with nvidia's half baked script; I rather installed the debian packaged non-free  _nvidia-driver_, and _nvidia-legacy-390xx*_ packages.

Issue is not reproduceable with those drivers.
I wouldn't know where to report this to the nouveau developpers.
