### ISSUE TITLE
[8193.21] dev build issue with ttf glyph for ellipsis (...)

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#278]
**To Reproduce**

 - Create a female character using the "Innocent Idealist" voice set and log in to a game
 - Use the VWR voice chat (Voice->Combat->Battlecry)
 - Look at your chat log.  The ellipsis (aka ... aka three dots) glyph looks like a square with an x through it, in either hires or lowres font options.
 
 **Specifics**

 - OS : Win10
 - Game build (8193.21 dev build released this week)
 - Distro platform (Steam)
 - Content overrides? (No ttf overrides)
 - Regression? (This is a change since 82913.20.1, probably related to the ttf font change).

**If needed, describe the bug**

8193.21 screenshot, hi res font: 
![image](https://user-images.githubusercontent.com/38797333/111044473-96d6cc00-840e-11eb-9f59-2ba35a3fc359.png)

8193.21 screenshot, low res font:  
![image](https://user-images.githubusercontent.com/38797333/111044490-b66df480-840e-11eb-90e3-9e6000bbacff.png)

The above screenshots show the regression vs 8193.20.1, below.  Below is the low res 8193.20.1 behavior: 
![image](https://user-images.githubusercontent.com/38797333/111044646-680d2580-840f-11eb-9af7-c300c07a34a2.png)

I haven't bothered showing the 8193.20.1 hi res glyph.  

The English tlk table ships with a number of ellipses in it.  I dunno if it's easier to swap out tlk entries for periods, update a font, or do some other handling.

-Dave

**Comment by Lord-Nightmare** [comment]
I think I figured it out. The dialog line in question (in lang\en\data\dialog.tlk at offset 0x787184 thru 0x7871a0) is using character 0x85 for the final character, which in the ISO/IEC_8859-1 Latin-1 character set is the ellipsis "…" character, but in Unicode (which the .ttf fonts want data to be formatted in) will instead attempt to render the "NEL" character (U+0085     133     0302 0205     Next Line     NEL ), which has no printed representation in most fonts, hence renders as an 'invalid character' boxed X. The correct offset for the ellipsis character in a unicode font is at character 0x2026.

I believe the simplest fix for this, not requiring the entirety of the engine in NWN to be re-tooled to handle UTF-8 or UTF-32 internally for strings, would be to edit dialog.tlk and its indices and just replace the 0x85 character with three periods (three 0x2e), although this may break automatic line breaks such that the ellipsis periods end up on multiple lines, which is likely undesirable.
This would also require fixing the indices for all strings with the character 0x85 in them in dialog.tlk. The 0x85 character appears at least 1,368 times in dialog.tlk (not all of these are in actual dialog though, some are likely in the headers and offset tables), so this may require a lot of work to do.

**Comment by drake127** [comment]
Hello, I encounter same issue but with game set to Polish. We use Windows-1250 and mostly it works but some special characters stopped working in late preview builds. When it's shown or typed, it causes entire font to go black until game restart!

The following characters don't work (I didn't test all of them): `†‡ ‰‹ ‘’“”•–— ™›` I believe that it's just U+2000-206F (General Punctuation) Unicode block that doesn't work (anymore). Can you please fix it? It would be unfortunate if we lost this punctuation on our PW world.

Following Windows-1250 characters work just fine:
```
ŠŚŤŽŹśšťžź
 ˇ˘Ł¤Ą¦§¨©Ş«¬­®Ż°±˛ł´µ¶·¸ąş»Ľ˝ľż
ŔÁÂĂÄĹĆÇČÉĘËĚÍÎĎĐŃŇÓÔŐÖ×ŘŮÚŰÜÝŢß
ŕáâăäĺćçčéęëěíîďđńňóôőö÷řůúűüýţ˙
```
