### ISSUE TITLE
[8193.10] Castle Exterior Rural - Grass: Forge Group Crashes Toolset

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#28]
**To Reproduce**

 - Create a module in the Toolset.
 - Choose Castle Exterior Rural as the tileset for the first area.
 - Click through module creation and save.
 - Open the area. 
 - Attempt to paint the Grass: Forge group. 
 - Toolset crashes.

** Specifics **

 - Game build 8193.10 DEV

![Crash1](https://user-images.githubusercontent.com/58920224/78937240-2137e280-7a7e-11ea-94a4-a739efbe158d.jpg)

![Crash2](https://user-images.githubusercontent.com/58920224/78937246-239a3c80-7a7e-11ea-8773-65f473b347bb.jpg)

**Comment by virusman** [comment]
Can't reproduce this.

**Comment by pstemarie** [comment]
Yup it was the override. I thought it was empty.
