### ISSUE TITLE
1.83.8193.21 Stack Underflow in SetObjectVisualTransform

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#283]
Drawing your attention to Jira NWNS-8532 on advice from Julius Borisov.
Not sure why it's necessary to report Development release issues in two places?
Someone said on the Vault that this is a known issue but I don't see it here.

Code which works in Retail fails with Stack Underflow in Development release 1.83.8193.21.

This is a showstopper.
**To Reproduce**

Run the attached module in the Retail editon. 
Click on the NPC named Foo Bar. 
Witness the correct visual transformation, which resets after 3 seconds. 

Now run the module in 1.83.8193.21 to see the Stack Underflow.
**Crash Dump**

Read the lovely crash dump generated by the above

**Specifics**

 - Win10
 - 1.83.8193.21 
 - BDC
 - Repro Rate 100%?
 - no custom content in demo
[_SetObjectVisualTransform test.zip](https://github.com/Beamdog/nwn-issues/files/6172289/_SetObjectVisualTransform.test.zip)

**Comment by tinygiant98** [comment]
Fixed in .22.
