### ISSUE TITLE
1.83.8193.21 ActionMoveToObject bug when target is transition door

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#285]
Drawing your attention to Jira NWNS-8564 on advice from Julius Borisov.
Not sure why it's necessary to report Development release issues in two places?

**To Reproduce**

Load test module
Pull the lever to watch the NPC go to a door and transition to another area!!!! Who told them to do that?
Notice "Complete" in the chat window, indicating that the rest of the action queue executed.
Pull again to watch them transition to a room in the same area.
Action queue does not complete.

The problem in real modules is far worse - see below.

**Specifics**

 - Win10
 - .21
 - BDC
 - vanilla content
 - .21
[_Alfred test.zip](https://github.com/Beamdog/nwn-issues/files/6172431/_Alfred.test.zip)

**If needed, describe the bug**

Although the demo works identically in .20 and .21, the severity in .21 is much higher. I've found 6 fatal instances in 3 modules so far, where the action queue works perfectly in .20, but fails to execute in .21 (all showstoppers).

If warranted, add videos/screenshots to showcase the issue.

**Comment by Soren217** [comment]
The issue partly pertains to the creatures now moving to the correct distance from the object (it was mistakenly always adding an offset of 0.1, leading to other issues especially in combat, where it would mean breaking off combat, losing attacks, etc.). 

The other part of it is that doors now all work in drive mode. 

Combined, it means that doors work just as area transitions (where you don't tell them to do that either), which (I presume) has the added benefit that NPCs are able to chase creatures through doors. 

Obviously we can't have showstoppers though. How prevalent is it? We could perhaps remove the ability of NPCs to use doors as they do transitions.

**Comment by Proleric** [comment]
I found 6 fatal instances across 3 of my modules. Some transitions within area, others across area.

The only thing that really needs fixing is for the action queue to resume once ActionMoveToObject is complete.

It would be unwise to change anything that allows creatures to use doors and transitions as I'm certain that many modules depend on that.

Observations of no importance:

In real modules, under .20 I have working examples of transitions both within and across area, which all fail in .21. However, for reasons unknown, when knocking up the simple demo, I couldn't make the former work in .20 or the latter fail in .21. Go figure.

According to the function description, it should complete when the creature is within 1 metre of the target (by default), but clearly this has never worked correctly in the case of doors.

I'm not sure that moving to a door normally results in an area transition? WASD doesn't do that, for example - you actually have to use the door.

I will be fixing all my instances, having discovered how flakey the function is, but that doesn't help legacy modules.

**Comment by Soren217** [comment]
Actually, I found out that the issue only applies to the ActionMoveToObject command and point clicking, so scratch all the driving mode stuff. I've changed the handling of that to only automatically try to open doors and enter for players (including DMs and possessed), which should match legacy behaviour.

It's worth noting that using ActionMoveToObject on doors have always been a bit funky - if you notice on the nwnlexicon, there's a remark there warning against using it for transition doors. At least now, with the incoming fix, it should be working reliably.

**Comment by Proleric** [comment]
LOL the Lexicon comment was added by me this week

**Comment by Soren217** [comment]
> LOL the Lexicon comment was added by me this week

Hmm, probably a bit quick to update the lexicon then, at least if you're sure it applies to .21 only? It's a dev patch after all.

Anyway, good that we got it fixed, thanks for reporting it.

**Comment by Soren217** [comment]
Ah alright, well, all is good then. :)

**Comment by Soren217** [comment]
Alright, it turns out that there's people relying on the NPC using the transition when calling ActionMoveToObject, so even if I agree that it makes more sense to not automatically enter the transition, we may need to restore that behaviour, hence why I've reopened this issue.

First of all though, I'm wondering what made the specific situations where you relied on not interacting with the door priorly not do so (where it would do so in most other). Could you point to specific examples, perhaps even providing savegames that will take me to the spot?

Thanks :)

**Comment by Proleric** [comment]
As you know, I changed my modules to work around the problem. However, here are two old versions which consistently reproduce the issue.

[ActionMoveToObject bug demos.zip](https://github.com/Beamdog/nwn-issues/files/6337553/ActionMoveToObject.bug.demos.zip)

You will need the haks / tlk from the Vault if you don't have them already. You can escape from all cutscenes.

Crown of Creation - start the module. Move the PC forward a little, triggering a cutscene. After a short conversation, in .20 Alfred runs upstairs and starts a second conversation, but in .22 Alfred never arrives because ActionMoveToObject(door) is deemed incomplete.

Dark Energy - start the module. Enter lower case t in the chat window to set the journal. Open the door then click on it, triggering a cutscene in which Miss Eva leads you through the palace to another door. In .20 you emerge into the garden where conversation ensures. In .22 nothing happens when you reach the second door.

Hope that helps.

**Comment by Soren217** [comment]
Thanks, that did help, in so far that as far as I can tell, what really breaks the cutscenes here are not the NPCs entering the doors, but the action queue erroneously breaking as they do (even before the actual transitioning). This appears to be another pre-EE bug that just became more apparent because of the other fixes. 

I'm gonna explore the possible solutions a bit further, stay tuned.
