### ISSUE TITLE
[8193.21] Cannot open nwhak.exe anymore

### ISSUE THREAD

**Issue by Chimerik** [Beamdog/nwn-issues#287]
**To Reproduce**

 - update to [8193.21]
 - Try to open nwhak.exe
 - Notice that nothing happens

**Specifics**

 - Windows 10
 - [8193.21]
 - Steam
 - None
 - [8193.21]

**Comment by DMSymphony** [comment]
This has been fixed in 8193.22.

Hooray.

**Comment by Chimerik** [comment]
Really? That's awesome. Kuddos to the team for the great work!
