### ISSUE TITLE
[8193.10] TN_SDoor19 Has Wrong Classification

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#29]
**Description**

Model tn_sdoor19.MDL in the XP3.BIF has the wrong internal "Classification." The model is currently classified as a "Tile" and should be classified as a "Door." If the door is exported, it generates an erroneous WOK file as well as the expected DWK file.

**Specifics**

 - Game build 8193.10
 - Windows 10
 - Steam

**Comment by Bill-Harper** [comment]
[tn_sdoor_19.zip](https://github.com/Beamdog/nwn-issues/files/4540183/tn_sdoor_19.zip)
Thanks again for the nice reports. I think this was originally that way; I found a WOK file in the old bif sources as well. Anyways, should be fixed now!
