### ISSUE TITLE
8193.21 crash

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#290]
Duplicate of NWNS-8600

**To Reproduce**

 during combat in Aztec Interior custom tileset
lighting looks weird too

**Crash Dump**

attached

**Specifics**

 - Win10
 - 8193.21 (works fine in 8193.20)
 - BDC
 - Repro Rate 100% will crash either during combat or movement in the same area
 - Custom Module (Dark Energy) with Aztec Interior, CEP, lots of other content
[nwmain-crash-1616343960.log](https://github.com/Beamdog/nwn-issues/files/6177884/nwmain-crash-1616343960.log)
[nwmain-crash-1616343960.zip](https://github.com/Beamdog/nwn-issues/files/6177885/nwmain-crash-1616343960.zip)

**Comment by Proleric** [comment]
This happened with Lighting Enhanced Off (my default setting because CEP stuff doesn't look right with it).
Attached screenshots show that lighting (at least) is better with Lighting Enhanced On.
Was able to play without crashing, too, but now not sure that crashing is 100% with Lighting Enhanced Off.
![Aztec Lighting Enhanced Off ](https://user-images.githubusercontent.com/80970201/111916790-9a083280-8a74-11eb-9d34-5ba61f4416ca.jpg)
![Aztec Lighting Enhanced On](https://user-images.githubusercontent.com/80970201/111916791-9aa0c900-8a74-11eb-87db-3c68912f1b07.jpg)

**Comment by Proleric** [comment]
If you want to see how CEP stuff looks wrong with Lighting Enhanced, try any marble floor e.g. 

Floor_Cover: Marble_Floor_2(ARF)

That issue already exists in .20, but I didn't report it before, as it's custom content, and (until now) playing with Lighting Enhanced off was a viable option.

**Comment by Soren217** [comment]
I'm curious about the non-enhanced lighting being wrong - could you do a repro-save that takes you right to that spot?

FWIW, I'm not seeing issues with that marble floor (perhaps try with .21?) but none the less, old content should still be made to work without enhanced lighting.

**Comment by Proleric** [comment]
To use the following demos, you'll need CEP2 and the haks / tlk here:
https://neverwintervault.org/project/nwn1/module/dark-energy

Here's a save demonstrating the bad lighting when not Enhanced. It won't fall over instantly (maybe because I cleared out some of the monsters for your safety) but it will if you wander around long enough. Maybe worthy of note is the light switch in the previous room, which has been used to change the area lighting from dark to light.
[023629 - Aztec Lighting bug.zip](https://github.com/Beamdog/nwn-issues/files/6183487/023629.-.Aztec.Lighting.bug.zip)

**Comment by Proleric** [comment]
In a different place in the same area, after visiting the bad spot, take the exit to find yourself in the sky above the sand:
[023630 - Aztec Lighting Bug 2.zip](https://github.com/Beamdog/nwn-issues/files/6183513/023630.-.Aztec.Lighting.Bug.2.zip)

**Comment by Proleric** [comment]
From either save, 
dm_jumptopoint 45 95 FollyIslandDelmondoPalace

to see how the CEP marble floor looks to me with Lighting Enhanced on:
![CEP marble lighting](https://user-images.githubusercontent.com/80970201/112018882-dac08400-8b26-11eb-8bc0-36c84cf015dc.jpg)

**Comment by Soren217** [comment]
Ah yes, it's actually because of using that super-bright light source in the CEP. The enhanced lighting supports overbright colors (meaning colors above 1.0), so it's actually just a symptom of being able to accurately portray very intense light. This has many advantages, but it does present issues when module authors relied on the limits of the old lighting engine. However, since it's not game breaking and only somewhat of a rare occurrence (I've only seen it happen in the context of the CEP light), it was generally agreed that the benefits outweighed the negatives.

Anyway, thanks for the saves, looking into that odd non-enhanced lighting now.

**Comment by Proleric** [comment]
I wasn't aware of using a "super-bright light source". Is there something specific in the toolset I can change so that Lighting Enhanced looks OK in those areas?

**Comment by Soren217** [comment]
Well, I checked out the module and once again I spoke a little too soon - it _is_ related to overbright, but it's not the notorious CEP light source. Rather it's the area setting, where both diffuse and ambient light is set to pure white, which combines to "superwhite". I'd suggest toning both down, and as a good rule of thumb, have ambient at between a fourth to a third as bright as the diffuse (e.g. diffuse 160,160,160 ambient 50,50,50).
