### ISSUE TITLE
Lighting Enhanced does not support white light correctly

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#291]
**To Reproduce**

Same files as issue #290 
- Download hak / tlk from https://neverwintervault.org/project/nwn1/module/dark-energy
- Load save below
- Set Lighting Enhanced on
- dm_jumptopoint 45 95 FollyIslandDelmondoPalace to see the bad effect of Lighting Enhanced

**Specifics**

 - Win10
 - 8193.20 
 - BDC
 - CEP marble floors
 - Build which broke it was the one that introduced Lighting Enhanced

**If needed, describe the bug**

Area lighting is set to Ambient=White, Diffuse=White (a deliberate choice to make characters clearly visible)
I'm told this is interpreted by Lighting Enhanced as a colour greater than 1 for some reason.
I've verified that the floor overbrightness is fixed by using the toolset default Interior Bright settings, however then the characters are poorly illuminated.
Since pure white is an option in the toolset, surely it ought to be supported, perhaps by capping colour at 1?    

If warranted, add videos/screenshots to showcase the issue.
![CEP marble lighting](https://user-images.githubusercontent.com/80970201/112112611-a93ecb80-8bad-11eb-8aa7-b58249a25caf.jpg)
[023629 - Aztec Lighting bug.zip](https://github.com/Beamdog/nwn-issues/files/6187827/023629.-.Aztec.Lighting.bug.zip)

**Comment by Proleric** [comment]
Save was made in 8193.21 so it will not load in 8193.20

**Comment by Soren217** [comment]
This is not a bug but a feature, as explained in the other ticket. You set very bright light and you'll get very bright light :)

**Comment by Soren217** [comment]
If you want to have the same result as priorly (which is essentially disabling all lighting), just set ambient to full white and diffuse lighting to black.
