### ISSUE TITLE
Underdark tileset is broken

### ISSUE THREAD

**Issue by Swogu** [Beamdog/nwn-issues#295]
**To Reproduce**

 - Load any module, open Underdark area.
 - Try to draw tiles.
 - Toolset crashes.

**Specifics**

 - Game build 8193.21
 
 In rare scenarios same error occurs on other tilesets

![651ad39ff04c0fe8](https://user-images.githubusercontent.com/81535877/112768868-c6005680-9026-11eb-8021-94fb9dde60bd.PNG)
![24c90bb2d122cf76](https://user-images.githubusercontent.com/81535877/112768956-458e2580-9027-11eb-85fc-7bbee680feb5.PNG)

**Comment by Swogu** [comment]
[Video](https://drive.google.com/file/d/1euNMCw35NAyUlKsbfaBCkq8Hs4jWrDKN/view?usp=sharing)

**Comment by Soren217** [comment]
Could you test whether this still happens with the latest dev patch (.22)? Thanks!

**Comment by Swogu** [comment]
The problem solved with latest patch(.22). Thank you for your work.
