### ISSUE TITLE
ActionAttack fails on invisible object (Showstopper)

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#302]
**To Reproduce**
WARNING for nudity and violence
You will need the haks from here:
https://neverwintervault.org/project/nwn1/module/enigma-island-complete
 - Talk to Wandal.
 - Keep choosing the first conversation option until Sir Roger transports you to Guano Bay.
 - Choose "The King will hear of this..." (or any other closing line, really)
 - In 8193.20 and earlier, the player is almost beaten to death, then conversation resumes.
 - In 8193.21, the guards appear to be trying to attack forever - the scene never ends (showstopper)

**Specifics**

 - Win10
 - 8193.21 is bugged
 - BDC
 - No overrides except haks already mentioned
 - 8193.21 broke it

**If needed, describe the bug**

The guards are trying to attack an invisible object named Beating (tag - GuanoVictim).
In 8193.21 it appears that they can't reach it, perhaps because the PC is in the same location.
The script trail is:
- bh_cut_guano1 on conversation end sets the Interrogation switch
- bh_mod_def_hb initiates the attack on module heartbeat
- OnPhysicallyAttacked the invisible object damages the player

As no damage occurs under 8193.21, it seems likely that the guards aren't getting close enough to fire the OnPhysicallyAttacked event.

If warranted, add videos/screenshots to showcase the issue.
[023632 - EI2 Interrogation Bug.zip](https://github.com/Beamdog/nwn-issues/files/6229494/023632.-.EI2.Interrogation.Bug.zip)

**Comment by Soren217** [comment]
Thanks for the report - found the issue and will be fixed by next update.
