### ISSUE TITLE
Toolset crash

### ISSUE THREAD

**Issue by BhaalM** [Beamdog/nwn-issues#308]
**To Reproduce**

 - Create a new module
 - Create an area with mines and caverns tileset (8x8 default settings)
 - Select "floor" and start to click in the area like you were creating a new area
 - After some clicks (sometimes 10, sometimes 50) toolset crashes.

**Specifics**

 - Toolset version v1.83
 - Regression?  v1.82 seems to work fine
 - No haks (new module), development folder empty, override empty
 - No workshops (I use BD client)
 - Windows 10
 
**If needed, describe the bug**

Sometimes textures disappears before the crash:
![1](https://user-images.githubusercontent.com/12261076/114099955-e69c9c00-98c3-11eb-83d2-f258cb586f3f.png)

Sometimes you get  an SQRT domain error :
![2](https://user-images.githubusercontent.com/12261076/114100141-25caed00-98c4-11eb-943b-50eb2e703d31.png)

And sometimes you get an Access violation:
![3](https://user-images.githubusercontent.com/12261076/114100293-5c086c80-98c4-11eb-912a-38f79f8ff1c2.png)

**Comment by BhaalM** [comment]
Maybe related to #295

**Comment by virusman** [comment]
Can't reproduce this on Intel GPU + Parallels.

**Comment by BhaalM** [comment]
The 4 guys that are working in my server with the toolset are getting the same error (new module, no haks, no development, no override, fresh install...). I think the only thing in common we have is that we are using Windows 10 and we have an nvidia graphic card.

**Comment by Daztek** [comment]
I get the `sqrt: DOMAIN error` on the 8193.21 branch on Steam, but not on the Preview branch.

**Comment by BhaalM** [comment]
Tested with the preview version, seems ok for me too!
