### ISSUE TITLE
Dedicated Server crash + Client crash

### ISSUE THREAD

**Issue by julien-lecomte** [Beamdog/nwn-issues#309]
**To Reproduce**

* Have at least version .21, and module from comment below.
* Create PC One, chat "goto", logout 
* Create PC Two, chat "recreate", logout
* Login with PC One, chat goto

**Crash **

**Specifics**

- Linux Debian, .21 to .26 build for both client and server, Steam, 100% Repro Rate.
- Some portrait workshop items, no hakpaks.

**Comment by julien-lecomte** [comment]
[Ruins of Undermountain.mod.tar.gz](https://github.com/Beamdog/nwn-issues/files/6281918/Ruins.of.Undermountain.mod.tar.gz)

**Comment by julien-lecomte** [comment]
[nwserver-crash-1617920481.log.gz](https://github.com/Beamdog/nwn-issues/files/6281921/nwserver-crash-1617920481.log.gz)

**Comment by Daztek** [comment]
Can you repro it without NWNX loaded?

**Comment by julien-lecomte** [comment]
Yes, it's reproduceable without NWNX. In this case, the repro method is the same, but you won't get confirmations such as "area recreated"

**Comment by julien-lecomte** [comment]
Can I ping this issue? It's kinda of a blocker on my PW server.

**Comment by julien-lecomte** [comment]
[nwserver-crash-1625072547.log](https://github.com/Beamdog/nwn-issues/files/6742738/nwserver-crash-1625072547.log)
[ReproBug.mod.gz](https://github.com/Beamdog/nwn-issues/files/6742744/ReproBug.mod.gz)

**Comment by julien-lecomte** [comment]
Ping since updated issue with module with no nwnx, and simple module with only 2 areas and 1 script
