### ISSUE TITLE
[8193.7+] Dynamic Model Textures Don't Display In-Game

### ISSUE THREAD

**Issue by Balanor** [Beamdog/nwn-issues#31]
**To Reproduce**
1. Extract the test hak and Model Texture Issue mod files from the attached zip. Please note that the module was created and saved using the 8193.6 build
2. Using a 8193.6 version of the toolset and client, first open the module in the toolset and observe the creature's model and textures. Press F9 to test the module. The creature should appear in-game, just like it does in the toolset
3. Login to the module using an 8193.7+ version of the client (I'm not sure if you have to save the module as .7+ or not - you may have to, first). At this version, the creature will NOT appear like it does in the toolset. See attached screenshot for reference.

**Specifics**
 - OS: Windows Client
 - Game build: 8193.7+
 - Distro platform: BDC and Steam

**If needed, describe the bug**
The texture for a dynamic creature model (we have observed it with the Gnoll, Goblin, and Orc dynamic models) is not being loaded correctly in-game starting with build 8193.7. The client appears to be defaulting to the human male textures, however when looking at these models in the toolset, they do display correctly.
[texture_issue](https://user-images.githubusercontent.com/36014329/79140935-69a51800-7d7e-11ea-80f6-f55de14e8a0d.png)
[ModelTextureIssue.zip](https://github.com/Beamdog/nwn-issues/files/4470647/ModelTextureIssue.zip)

**Comment by Soren217** [comment]
Is it intentional that there's only plt textures for the first (001) variant of each bodypart?

**Comment by Soren217** [comment]
Alright, found the cause and will fix ASAP, thanks for reporting it :)
