### ISSUE TITLE
[8193.21] GetObjectVisualTransform doesn't reset cleanly

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#310]
**To Reproduce**

 - Run the attached module.
 - Pull the lever.
 - Notice that the lerp transform starts after 2 seconds.
 - Pull the lever.
 - With a delay of 0 seconds, nothing happens - ship appears stuck in final position
 - Pull the lever (this is an endless toggle)
 - With a delay of 2 seconds, the ship appears in its original position then transforms correctly

An additional glitch is that if the PC approaches the ship in its final position, it disappears. Being 40m from the placeable model origin, this might be expected behaviour, but it looks a bit different to me.

**Specifics**

 - Windows
 - 8193.21
 - BDC
 - No content overrides

**If needed, describe the bug**
The script issues a transform with a translation of 0 metres to reset the ship to the initial position if necessary.
Then, after a delay, it issues the transform with a tranlation of 40m.
If the delay is not zero, both actions work every time.
However, if the delay is zero (or if DelayCommand is not used at all), the reset does not work, which must be a bug.

[_lerp test.zip](https://github.com/Beamdog/nwn-issues/files/6289369/_lerp.test.zip)

**Comment by Finaldeath** [comment]
Should be fixed back in .31.
