### ISSUE TITLE
[8193.22] Inconsistent NWScript behavior on Linux and Windows

### ISSUE THREAD

**Issue by Taro94** [Beamdog/nwn-issues#311]
**To Reproduce**

 - Download the attached module: [repro.zip](https://github.com/Beamdog/nwn-issues/files/6330197/repro.zip)
 - Download medruralcomp.hak from [here](https://neverwintervault.org/project/nwn1/hakpak/tileset/mountains-and-more)
 - Start the module on Linux.
 - Exit the starting room and head to the door leading downstairs.
 - Select the option to input custom seed for map generation.
 - Say "1208956411" via chat and continue.
 - Don't customize the ruleset.

 - Select the smallest map size (4x4).
 - Generate the map (without adding any companions).
 - Scroll up the chat log to find a warning (in orange).
 - Compare the behavior to that of a Windows version, in which no warning occurs.

**Specifics**

 - OS: Linux
 - Game build: 8193.22
 - Distro platform: GOG, Steam
 - Content overrides: none
 - Regression: same behavior in 8193.16

**If needed, describe the bug**

The warnings should in fact appear due to wrong order of the calls in lines 176 and 177 in cnv_mg_generate.nss (PlotGeneration() should be called earlier than Spawn()). Long story short, Spawn attempts to use a plot object, which is OBJECT_INVALID if PlotGeneration() hadn't been called.

The point is that it still works on Windows, even though it shouldn't due to the wrong order. This may indicate that PlotGeneration is called earlier than Spawn despite being called with a greater delay.

![image](https://user-images.githubusercontent.com/31405835/115129087-05491400-9fe3-11eb-97fa-424310898534.png)

**Comment by Finaldeath** [comment]
@Taro94 saving me sorting my WSL can you report if this is still an issue between Windows and Linux, several VM changes and fixes have been done since 2021.

**Comment by Taro94** [comment]
@Finaldeath I've just checked, the inconsistency between Windows and Linux binaries are still occuring.

**Comment by mtijanic** [comment]
Is there any chance there is a division by zero anywhere? Inthe onoy other such bug I know, where whirlwind attack would sometimes lockup on Linux but not on Windows, the culprit was different results when dividing by zero (or by NaN, I forget)

**Comment by Taro94** [comment]
@mtijanic Dividing by zero would be reported in the console and quit the executing script.

**Comment by Daztek** [comment]
Happens on windows for me.

![image](https://github.com/Beamdog/nwn-issues/assets/31415508/ce5d0f4c-d098-4b8f-b416-5fc2ce82dbf1)

Have you tried increasing the delays? There's a lot of DelayCommands with low delays going on and I don't know how the engine sorts them or deals with it.

**Comment by Taro94** [comment]
@Daztek Yes, I've already worked around the inconsistencies by increasing the delays, just found it weird that it behaves differently on Linux and Windows. And now it turns out the inconsistencies don't happen for everyone.

**Comment by mtijanic** [comment]
Is this windows/linux on same physical machine?

Anything timing related is gonna be fuzzy. IIRC scheduling things at 0.0001 vs 0.001 vs 0.0 should be equivalent (even ignoring IEEE754 inaccuracies) because they all happen in the next tick. Ehat are the actual delay differences here, and what is the tickrate? If the delay diff is 0.1 but your tick takes 150ms because of the heavy scripts, it could cause this.
And, of course, windows is _much_ slower at nwscript than linux.

**Comment by Daztek** [comment]
```
    DelayCommand(0.1f, Spawn());
    DelayCommand(0.2f, PlotGeneration());
```
```
void Spawn()
{
    SendMessageToAll(GetLocalizedString("Areas creation...", "Tworzenie obszarów..."));
    int i;
    for (i = 1; i <= 256; i++)
        DelayCommand(0.0f, SpawnMapTiles(i, mapObject));
}

void PlotGeneration()
{
    SendMessageToAll(GetLocalizedString("Plot creation...", "Tworzenie scenariusza..."));
    SpawnPlot(mapObject);
}
```

Here's the code

**Comment by Daztek** [comment]
Wait... 

>The warnings should in fact appear due to wrong order of the calls in lines 176 and 177 in cnv_mg_generate.nss (PlotGeneration() should be called earlier than Spawn()). Long story short, Spawn attempts to use a plot object, which is OBJECT_INVALID if PlotGeneration() hadn't been called.

But the above code calls PlotGeneration() later...?

**Comment by Taro94** [comment]
@Daztek Yes. This is a bug in the module build attached as a repro. PlotGeneration should be called before Spawn, but is not. That's the reason for the warning message so the warning being printed is the correct behavior.

**Comment by Daztek** [comment]
Well, it's printing the warning for me on Windows. Have you tried it on the preview build? It has some VM perf improvements

**Comment by Finaldeath** [comment]
Another one fixed without me doing anything! I'm on a roll.

**Comment by mtijanic** [comment]
I wouldn't say fixed as much as 'not a bug'. Timing sensitive things behave differently in different scenarios. You gotta account for that when building.

**Comment by Taro94** [comment]
Still, in this situation a call with a greater delay was executed before a call with smaller delay (on Windows). I do understand the explanation you've provided above on how it can happen, but personally I'd not hesitate to call this behavior buggy.

**Comment by mtijanic** [comment]
I'd go with 'quirky' rather than 'buggy'. We should probably add explicit documentation to DelayCommand about this though
