### ISSUE TITLE
[8193.22] Saves incompatible with earlier releases

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#312]
**To Reproduce**

 - Start a new game in 8193.22 (any module created prior to .21)
 - Save
 - Start 8193.20
 - Attempt to load save
 - Fails with an (incorrect) error message saying the module was created on a later release

**Specifics**

 - Win10
 - 8193.22 (same issue in .21)
 - BDC
 - No custom content or overrides

**If needed, describe the bug**

It is of course correct for the toolset to stamp a module with the version for which it was created. However, the version stamp should not be changed when the game is saved, because the saved game cannot be using any new features.

This is a new bug - in the past, it was possible to load Development release saves in the previous Retail release (an essential feature for working around fatal errors in Development).

**Comment by mtijanic** [comment]
> However, the version stamp should not be changed when the game is saved, because the saved game cannot be using any new features.

Save games can add new version features in several ways:

* Use CreateArea() on an area created with newer version placed in override/
* Use the new nwscript debug window to DelayCommand() something that uses new nwscript functions
* Use ExecuteScriptChunk() with a new nwscript function
* Sometimes game versions update the bic, like when RDD stat gain was moved to 2da. Reverting will break the character.
* Dynamically switch appearance of a creature/placeable to something added in newer release

IMO this is working as indented. If you're an advanced user that knows that they're doing, you can easily modify the version field with a GFF edit.

**Comment by Proleric** [comment]
Understood, but I believe this needs more scrutiny, because it is a change in behaviour in a fundamental area - the rules governing backward compatibility. To the best of my knowledge, no release prior to 8193.21 has ever stamped saves as unusable by prior releases - only module creation did that.

With one exception, the cases you mention are all "modding". It's generally understood that anything broken in that way is the player's own fault - similar things were always possible in earlier releases, but it was never advanced as a reason for blocking loads in earlier releases before.

The RDD case is different. If that actually does break the save for earlier releases, then of course there is a case - the save should be stamped for that release and later (so that later releases can still revert to that release).

More generally, though, that case makes the bigger point - we really don't want saves to be "corrupted" by later releases if at all possible.

Of course it is true that the immediate issue can be fixed with a GFF editor, but if changes like the RDD thing become commonplace, who knows whether that's safe?

Which brings me back to the original point about needed to regress a save safely when there is a showstopper in the new development release.

What do you think?

**Comment by mtijanic** [comment]
> What do you think?

Honestly, I think the save version is good. Ideally it would be a different field and a different message so you know when it's just the save and when it's the whole module. 

What I think would be better here is just an "I understand the risks and want to try it anyway" button when trying to load a newer save/mod. 

As for the RDD changes, there is a 'migration version' published in the patch notes and some pseudocode how to undo them if you need the bic on older game versions. So long as these back-out steps are well documented, I think it's fine. 

Anyway, I'm just some guy, that does PWs and not SP anyway, so take my opinions with a lot of salt. Just wanted to say that there are plenty of ways to make a save incompatible with older game versions, even accidentally.

**Comment by Finaldeath** [comment]
I've reviewed this and to clear down old bugs this needs closing as "not planned".

This is primarily because newer game versions may fix save games - for instance data previously not saved might now be saved correctly, or saved under a new field properly. Loading that save on an older version will cause that data to be either lost or fixed data to be misread by the game causing further issues.

It also means any modding of the game by a user outside the module content may not work on older versions (eg new appearances parts past 255).

As noted advanced users can manually alter the save game metadata at their own risk.
