### ISSUE TITLE
Weapon focus: unarmed strike with old baseitems.2da

### ISSUE THREAD

**Issue by BhaalM** [Beamdog/nwn-issues#317]
**To Reproduce**

 - Download the 2da and put it in the override folder (the 2da is just the original 2da without the weapon feats columns)

[baseitems.zip](https://github.com/Beamdog/nwn-issues/files/6351156/baseitems.zip)

 - Create a new module without haks (put at least a chest or something to hit)
 - Play the module with a monk with Weapon focus: unarmed strike
 - Equip a glove and enable dm_enablecombatdebugging 
 - Hit the chest (or whatever) you'll see the +1 due to weapon focus is missing
 - Additionally, note that the character sheet shows the correct numbers

**Specifics**

 - OS: Windows
 - Game build: 8193.21
 - Distro platform:  BDC
 - Content overrides: the attached baseitems.2da file
 - Regression: 8193.9

**If needed, describe the bug**

Just wanted to share this "issue" with you. I know the problem is my 2da is outdated, but it was said in 8193.9 that the changes in baseitems.2da would not break modules with old haks, and it does.

**Comment by Finaldeath** [comment]
Fixed in .24
