### ISSUE TITLE
NWNEE 8193.20+ does not display entries that use Custom Tokens.

### ISSUE THREAD

**Issue by SeanMJOBrien** [Beamdog/nwn-issues#319]
**To Reproduce**

 - Start a new game using the attached module.
 - Attempt to use the "Setup and start the action" menu option with any character.
 
**Specifics**

 - Windows 10
 - 8193.20.1-.22, I have not tested this module with earlier versions of NWNEE, only the original NWN1 (1.69)
 - Steam
 - No overrides
 - Regression? Unknown, I had not attempted to play the module in many years

**If needed, describe the bug**

The dialog branches using Custom Tokens do not display in the dialog as expected. All works fine in vanilla NWN (1.69). See screenshots and module.

![image](https://user-images.githubusercontent.com/11039906/116798950-7b507f00-aaa9-11eb-8b15-ca16016e1e2e.png)
![image](https://user-images.githubusercontent.com/11039906/116798963-9d4a0180-aaa9-11eb-8c0b-c9c8a2965a60.png)
[CustomTokensBug.zip](https://github.com/Beamdog/nwn-issues/files/6410589/CustomTokensBug.zip)

**Comment by Daztek** [comment]
In (one of) the StartingConditionals it references a teams.2da. If it a returns an empty string it doesn't show an options, make sure its somewhere where the game/server can find it.

```c
    string sName=Get2DAString("teams","TEAMNAME",nBase+nRunner);
    if (GetStringLength(sName)<1) return FALSE;
    SetCustomToken(1000+nRunner,StringToRGBString(sName,"377"));
```

**Comment by SeanMJOBrien** [comment]
I was missing a hak file with the 2DA.
