### ISSUE TITLE
Preview Water Goes Black / Bugs Out [1.83.9193.23]

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#320]
**To Reproduce**

 - Load module: [Buggy Water.zip](https://github.com/Beamdog/nwn-issues/files/6414313/Buggy.Water.zip)
 - Turn to the left a bit, buggy void is present (or should be)

![image](https://user-images.githubusercontent.com/6137144/116866599-96370680-ac03-11eb-9db6-bde38cf1f98e.png)

I previously got it shimmering and appearing/disappearing/flickering while moving around but this is certainly more "reliable".

**Specifics**

 - OS Windows
 - Game build 1.83.9193.23 / e3ca309a
 - Distro platform Steam
 - Content overrides? None
 - Regression? Well kinda, shaders change all the time :D 

**If needed, describe the bug**

As above. Water seems to mess up on this tileset at least - not sure about others.

**Comment by shadguy** [comment]
Jasperre,
Thanks for reporting this.  I have numerous screenshots of the black void/horizon issue, but have not been able to make a reliable repro case.  I appreciate you nailiung it down.
-Dave
