### ISSUE TITLE
Performance Down 8193.23

### ISSUE THREAD

**Issue by WodahsEht** [Beamdog/nwn-issues#321]
The latest dev builds (8193.22 and 8193.23) dropped my framerate down to 20-40fps on a Ryzen 2700 with Athlon RX 480.  The previous builds usually stayed around 65-80 in the same areas with the same settings.  Issue is persistent no matter which mode is used (fullscreen, windowed, or borderless windowed.)

The following settings have the greatest impact: Ambient Occlusion, Sharpness, and Skybox Enable.

**Comment by Soren217** [comment]
What operating system are you using? Are you running the most recent Radeon drivers?

**Comment by tinygiant98** [comment]
@WodahsEht We're trying to clean up this repo a bit.  Is this still an issue.  If no response in about a week, we'll close the issue without further comment.  Thanks.

**Comment by tinygiant98** [comment]
Original author states unable to duplicate.
