### ISSUE TITLE
[8193.5+] ELC check failed for RDD characters

### ISSUE THREAD

**Issue by TomRotfl** [Beamdog/nwn-issues#33]
**To Reproduce**

Create a character with RDD levels, get a feat with STR requirement (like Devastating Critical or Thundering Rage). Into "some" circumstances, that character will fail the default ELC check. "Player do not meet requirement for a feat"

**Specifics**

 - OS Windows
 - Game build (Server 8193.5) - (Player 8193.9)
 - Distro platform Steam

**If needed, describe the bug**

Many players in my PW are still experiencing issues with ELC checks while having RDD levels and taking feats with STR requirement (like Devastating Critical or Thundering Rage). 

My server is still at 8193.5 but i haven't read anything about RDD ELC fix on next patch notes so i guess this problem is still up even on 8193.10

I attach one character bic file at lvl 35, with 38 DEFAULT STR that took Thundering Rage (25 STR requirement), at level 35, but it still fails the ELC check. Even is without RDD levels it would have 30 STR, so more than enough to get that feat.

I tried to delevel that character to lvl 21, where it already has 25 STR without RDD levels, and if you take the feat BEFORE taking any RDD levels, ELC will work fine then.
[bichofeio.zip](https://github.com/Beamdog/nwn-issues/files/4470555/bichofeio.zip)

**Comment by niv** [comment]
.9 is the latest stable build. It should be fixed there. Please recheck and reopen if still present.
