### ISSUE TITLE
Development folder not recognised

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#334]
**To Reproduce**

 - Add a line to placeables.2da referencing a new model
 - Add modified placeables.2da and model to Development folder
 - Run toolset
 - Edit a placeable appearance
 - Notice that the new appearance is not available

**Specifics**

 - 8193.20.1

**If needed, describe the bug**

The Development folder is recognised in game, which you can prove using Get2DAString on the new line.
If you put the modified placables.2da in a hak, the toolset still says that the model is missing.
The workaround is to put the model in override.
However, this kinda defeats the object of the Development folder as a means of over-riding haks temporarily during module development.

**Comment by niv** [comment]
This was fixed in .23, the latest stable. .20.1 is a bit older.
