### ISSUE TITLE
Creatures cannot figure out how to leave a room when in combat mode.

### ISSUE THREAD

**Issue by SeanMJOBrien** [Beamdog/nwn-issues#337]
**To Reproduce**

1. Load attached module.
2. Enter room with wolf (very slow wolf).
3. When it starts attacking leave the room and run past the room confines outside.

**Specifics**

 - Windows 10
 - Build 8193.27
 - Steam
 - No overrides

**If needed, describe the bug**

Wolf will enter combat and chase PC, but when PC is outside of the room, past the farthest corner outside the room, the wolf will remain in the room and remain stuck in the corner.
[BugWallsPathing.zip](https://github.com/Beamdog/nwn-issues/files/6735081/BugWallsPathing.zip)

**NOTE:** The wolf will path correctly if it is walking waypoints. I.E.; If you place a POST for the wolf to the same location your run to to get the wolf stuck, the wolf walks waypoints just fine.

**Comment by Soren217** [comment]
Do you have any idea how new this is?

**Comment by SeanMJOBrien** [comment]
It appears this particular issue of "ignoring walls" started in 8193.25
8193.24 appears fine.

**Comment by Soren217** [comment]
Alright, I think I've identified the issue (it was a bit inconsistent for me in the first place), will have a fix in the next patch.

**Comment by Soren217** [comment]
Nvm, turned out to be unrelated.

Could you help me a bit with how to reproduce it? How do I need to move exactly?

**Comment by SeanMJOBrien** [comment]
This module is very simple. There is a wolf that is hostile to the PC. The wolf is set to the lowest possible movement speed in the toolset. Move your PC into the field of view of the wolf, and once the wolf starts moving towards you to attack, run out of the door and down the hall towards the corner of the wolf room.

I expect the wolf will run to the corner of the room nearest you, rather than out of the doorway to attack you in the hallway where your PC is standing. The wolf will remain in the corner inside of the room, and your PC will be safe as long as they don't approach the doorway to the room.
If your PC approaches the doorway to the wolf room, the wolf will move towards you, along the wall. Kind of like a marble tilt puzzle.

**Comment by Soren217** [comment]
This should now be fixed in the latest preview. Thanks for the report!
