### ISSUE TITLE
AreaOfEffect created from non-spell scripts can cause crashes with some event scripts

### ISSUE THREAD

**Issue by GoLoT** [Beamdog/nwn-issues#34]
**To Reproduce**

- Create an AoE effect (i.e. Darkness) from a script that isn't a spell-script. Snippet provided by Sarceez while troubleshooting, called from an onDamage event:
```cpp
effect eAOE = EffectAreaOfEffect(AOE_PER_DARKNESS);
lTarget = GetRandomLocation(oArea, oCaster, 5.0);
ApplyEffectAtLocation(DURATION_TYPE_TEMPORARY, eAOE, lTarget, RoundsToSeconds(2));
```
- Trigger an AoE event that expects a valid spellId set on the AoE effect (`GetCasterLevel()` in this specific crash instance).
- The server will crash when trying to dereference the spell returned by `CNWSpellArray::GetSpell(-1)` in `CNWVirtualMachineCommands::ExecuteCommandGetCasterLevel()` because `CGameEffect::SetCreator()` didn't set a spellId.

**Crash Dump**

- Linux: I'm linking the pastebin that was provided by Sarceez in NWNX's discord: https://pastebin.com/UdG9TSZ2

**Specifics**

 - OS: Linux
 - Game build: 8193.10
 - Distro platform: dedicated nwserver
 - Repro Rate: 100%
 - Custom Content: NWNX

**Extra info**

I'm not sure if this is an engine bug exactly as creating spell effects from scripts that aren't spell scripts isn't intended. It's a crash though that should be easily avoidable by adding a null guard to the `CNWSpellArray::GetSpell()` result in `CNWVirtualMachineCommands::ExecuteCommandGetCasterLevel()`:

```cpp
        if (bVar1 == 0xfe) {
          uVar8 = CNWSCreatureStats::GetSpellLikeAbilityCasterLevel
                            (*(CNWSCreatureStats **)(lVar7 + 0xa60),iVar2);
          uVar9 = (uint)(byte)uVar8;
          if ((byte)uVar8 == 0xff) {
            pCVar6 = CNWSpellArray::GetSpell(*(CNWSpellArray **)(g_Rules + 0xd0),iVar2);
            uVar9 = ((uint)pCVar6->m_nInnateLevel - 1) + (uint)pCVar6->m_nInnateLevel;
          }
        }
```

It will result in event scripts using a caster level of 0 but it should prevent the crash.

**Comment by niv** [comment]
0 makes sense here. Other code branches (i.e. placeables) return 10, but 10 only if there's a valid spell as well. Otherwise, it'll be 0.
