### ISSUE TITLE
[8193.29] Development Crashes on VFX Application

### ISSUE THREAD

**Issue by Aschent89** [Beamdog/nwn-issues#341]
This was reported by a player testing on The Dragon's Neck. I do not have a Repro mod however will attempt to provide clarification. Our accessory system leverages visualeffects (via visualeffects.2da). A player reported that when a color was changing for a hairstyle, they would instantly crash. 

Our approach to changing hairstyle consists of the `.mdl` using the hair channel color, swapping the hair channel color, removing the existing VFX, and then applying the VFX again so it uses the newer hair color.

**To Reproduce**

 - Log into TDN
 - Interact with Tailor, apply a Hairstyle, and change the color.

**Crash Dump**

No .dmp or .log files available.

**Specifics**

 - OS: Windows
 - Game build: 8193.29
 - Distro platform: Steam
 - Repro Rate: 100%
 - Content overrides? None.

**Comment by Soren217** [comment]
Thanks for the report - found the issue and will have it fixed by next update.
