### ISSUE TITLE
[8193.20+] Visual Effects Issue

### ISSUE THREAD

**Issue by ud4ever** [Beamdog/nwn-issues#343]
In versions above .20 there is a problem with the display of visual effects located "near the ground", such as Spell Mantle(VFX_DUR_SPELLTURNING), Freedom of Movement(VFX_DUR_FREEDOM_OF_MOVEMENT) etc. Attached are screenshots taken on different versions of the game `8193_20.png, 8193_21.png, 8193_29.png`. If you pay attention to the spell mantle, you can see that on versions above .20 it starts "to fall into the ground" a bit. If you move the visual effect up on the Z-axis (`effect eVis = EffectVisualEffect(VFX_DUR_SPELLTURNING, , FALSE, 1.0, [0.0, 0.0, 0.1]);`), you can see that it starts to appear in the game as it did in versions .20 and below `8193_29_up_z_axis.png`. The main problem is that the previously distinguishable effects have become almost invisible.
[screenshots.zip](https://github.com/Beamdog/nwn-issues/files/6799618/screenshots.zip)

**Specifics**

 - OS (Windows, Mac, Linux)
 - Game build (8193.20+)
 - Distro platform (Steam)
 - Content overrides? (Steam Workshop? Overrides? Patch haks?)
 - Regression? (8193.21)

**Comment by Soren217** [comment]
Thanks for reporting this - the issue has been identified and should be fixed by next patch.

**Comment by virusman** [comment]
@ud4ever Can you confirm this as fixed in .30?

**Comment by ud4ever** [comment]
yes, .30 solved this issue
