### ISSUE TITLE
Toolset fails to load spell list with altered columns in spells.2da

### ISSUE THREAD

**Issue by Arvirago** [Beamdog/nwn-issues#344]
**To Reproduce**

 - Customize the columns for classes in your spells.2da (I attach mine, with a column for Wizard, another column for Sorcerer, and another column yet for a custom prestige class: Ygnahir).
[spells.2da.txt](https://github.com/Beamdog/nwn-issues/files/6804394/spells.2da.txt)
 - The game runs fine, and each class receives its spell list (after putting the correct SpellTableColumn in classes.2da, of course).
 - Open the toolset and create a NPC with levels of Wizard or Sorcerer.
 - Now go to the Spells tab. The toolset fails to load the spell list, so you can't assign any spell to the NPC.

The image shows a NPC with sorcerer levels (Hechicero in spanish). The spell list is empty.
![image](https://user-images.githubusercontent.com/38470153/125356712-7d16a880-e35e-11eb-97dc-c8f2ba7db220.png)

**Comment by Shad000w** [comment]
Generally speaking, new columns should always be added at the end of the column list and everytime Beamdog adds new columns, you should reposition your columns to be at the end again because game or toolset code might access them not by column name but position. So try that first.

**Comment by Arvirago** [comment]
OK, i will try that, thanks. I thought all classes should be together, don't know why :)

**Comment by Arvirago** [comment]
I moved the added columns to the end.
Now the spell list for wizard works again.
But the sorcerer is reading the same spell list of the wizard, it does not read its column.
And the prestige class has an empty list.
It looks as if the column for each class spells was hardcoded in the toolset, it does not follow what's in classes.2da
So the new possibility of adding custom spell lists remains only for PCs, not for NPCs.

**Comment by virusman** [comment]
@Arvirago Please also attach classes.2da you're using.

**Comment by Arvirago** [comment]
Sorry I did not get this msg. Thanks, will try new preview build! :)
