### ISSUE TITLE
[8193.29] EffectIcon not working when linked

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#345]
I've been running the latest development patch, and EffectIcon doesn't seem to work when linked with another effect. Here's a snippet of script where it doesn't work:

```
    effect eIcon = EffectIcon(EFFECT_ICON_ABILITY_DECREASE_CHA);
    eIcon = EffectLinkEffects(EffectVisualEffect(VFX_DUR_CESSATE_POSITIVE), eIcon);
    ApplyEffectToObject(DURATION_TYPE_TEMPORARY, eIcon, OBJECT_SELF, 20.0f);
```

**Comment by Daztek** [comment]
I guess it works as a visual effect and can't be linked with other visual effects. It'll need a non vfx/icon effect in the link.

**Comment by FrogsOfDoom** [comment]
Thanks; that worked like a charm. Going to close it then.
