### ISSUE TITLE
[8193.29] Tile Properties Cannot be Edited After Painting an Object from the Palette

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#348]
**To Reproduce**

 - Load the attached module
 - Paint a creature in any tile
 - Click on Tile Selector on the tool bar
 - Right click on any tile and select Tile Properties
 - Toolset crashes with two click-thru warnings and can not edit Tile Properties

**Specifics**

 - Game build 8193.29
 - Regression? Unknown

![error_1](https://user-images.githubusercontent.com/86877958/126050878-d835220b-b9d0-4c25-8f7b-bc46203ee8c4.jpg)
![error_2](https://user-images.githubusercontent.com/86877958/126050880-be44db57-b11b-48b1-9022-b71310f5a2e2.jpg)

[_Test.zip](https://github.com/Beamdog/nwn-issues/files/6835387/_Test.zip)

**Comment by pstemarie** [comment]
Just tried it in .28 Stable - same thing.

**Comment by pstemarie** [comment]
I opened up nwtoolset.ini and changed "DisableTabs=0" to "DisableTabs=1" and that fixed the issue.

**Comment by pstemarie** [comment]
Seems my "fix" was a little premature, because it produces the error now with tabs disabled. Not sure what's going on.

**Comment by LaputianBird** [comment]
Works fine for me, no crash or errors

![image](https://user-images.githubusercontent.com/60814252/126077376-8b5bdcca-bd40-46f9-a28d-27da543bca85.png)

**Comment by pstemarie** [comment]
@LaputianBird - hmmm. What OS and brand CPU and GPU do you have. I'm using an Intel/nVidia setup with the latest video drivers on Win 10.

**Comment by virusman** [comment]
Anything in overrides?

**Comment by pstemarie** [comment]
Is it possible my config - nwtoolset.ini - has an error?

[Start Up]
CPU Affinity=0
Show Welcome=1
Create Backup Modules=1
Verify On Save=0
Show Retail=1
Disable Tabs=0
Always Open Module Directory=0
[Undo]
UndoStackSize=32
[CustomColors]
ColorA=787878
ColorB=000000
ColorC=000000
ColorD=000000
ColorE=000000
ColorF=000000
ColorG=000000
ColorH=000000
ColorI=000000
ColorJ=000000
ColorK=000000
ColorL=000000
ColorM=000000
ColorN=000000
ColorO=000000
ColorP=000000
[Warning]
NameSpace Warning=0
Standard Resource Warning=0
Creature Spells=1
Inventory=0
ColorDepth=1
Character Set=1
ResourceInHak=0
[Spelling]
EnableSpellCheck=1
ClearIgnoreChangeAllLists=1
AutoSpellCheckConv=0
InteractiveCheckOnEnterConv=0
InteractiveCheckOnExitConv=0
CheckSpellingConv=1
CheckGrammarConv=1
CheckBadCharsConv=1
AutoSpellCheckLoc=0
InteractiveCheckOnEnterLoc=0
InteractiveCheckOnExitLoc=0
CheckSpellingLoc=1
CheckGrammarLoc=1
CheckBadCharsLoc=1
TextColorSpellingError=128
TextColorGrammaticalError=32768
TextColorSpellingAndGrammaticalError=8388736
[Application]
State=2
Top=-1
Left=-1
Height=0
Width=0
ContentsWidth=251
PaletteWidth=219
MessagesHeight=58
ContentsVisible=1
PaletteVisible=1
MessagesVisible=1
ToolbarVisible=1
MinimizeOnTest=1
[Toolbars]
FileVisible=1
FileTop=2
FileLeft=11
DisplayVisible=1
DisplayTop=2
DisplayLeft=147
SelectionModeVisible=1
SelectionModeTop=2
SelectionModeLeft=206
FiltersVisible=1
FiltersTop=2
FiltersLeft=299
PreviewVisible=1
PreviewTop=2
PreviewLeft=597
[Area]
Background Color=12632256
Show Fog=0
Display Shadows=1
Fade Geometry=0
Use Area Lighting=0
Display Grid=1
Camera Controls=1
UseEnvironmentMapping=0
Show Spawnpoint Markers=1
Spawnpoint Marker Height=12
Spawnpoint Marker Width=4
Show Door Orientation=1
[Sound]
Enable Area Sounds=0
Enable Area Ambient Sound=0
Enable Area Music=0
Ambient Music Volume=92
Show Listener Position=0
2D3D Bias=1.25
[Script]
FontName=Courier New
FontSize=10
Templates=d:\documents\neverwinter nights\scripttemplates
AutoCompile=1
GenerateDebugInfo=0
ScriptEditorWidth=1936
ScriptEditorHeight=1056
ScriptEditorLeft=-8
ScriptEditorTop=-8
ScriptEditorState=2
ScriptEditorSideWidth=248
ScriptEditorBottomHeight=116
ColorSelectedText=16777215
ColorSelectedBack=8323072
ColorText=0
ColorBack=16777215
ColorMargin=8355711
ColorComment=32512
ColorDirective=127
ColorIdentifier=0
ColorKeyword=16711680
ColorNumber=8323199
ColorString=8323072
ColorError=255
[Conversation]
PlrDefaulDelay=0
NPCDefaulDelay=0
TextPopup=1
ShowNames=1
PlayerTextColor=16711680
NPCTextColor=255
BackgroundColor=16777215
ConvLinkPasteMode=1
ConvLinkLinkMode=0
AutoBackup=1
AutoBackupInterval=5
Maximized=0
X=0
Y=0
Width=1440
Height=759
RightWidth=385
BottomHeight=308
[Language]
UseDefault=1
LanguageID=0
[General]
PlotManagerSize=25
PlotManager=0
[Help]
Width=320
Height=240
Left=0
Top=0
[Build Module]
Build Unused=0
Build Unused Scripts=1
Build Unused Conversations=1
Build Unused Blueprints=1
Build Missing=1
Build Missing Areas=1
Build Missing Conversations=1
Build Missing Creatures=1
Build Missing Doors=1
Build Missing Encounters=1
Build Missing Items=1
Build Missing Placeables=1
Build Missing Sounds=1
Build Missing Stores=1
Build Missing Triggers=1
Build Missing Waypoints=1
Build Compile=1
Build Compile Scripts=1
Build Compile Creatures=1
Build Compile Encounters=1
Build Compile Palettes=1
Spell Check=0
Spellcheck Areas=1
Spellcheck Conversations=1
Spellcheck Blueprints=1
Spellcheck Creatures=1
Spellcheck Doors=1
Spellcheck Encounters=1
Spellcheck Items=1
Spellcheck Placeables=1
Spellcheck Sounds=1
Spellcheck Stores=1
Spellcheck Triggers=1
Spellcheck Waypoints=1
Build Module Advanced=0
Build Module Height=200
[Journal]
Maximized=0
X=240
Y=140
Width=1440
Height=759
[MRUResTypes]
Type00=nss
Type01=dlg
Type02=utp
Type03=utc
Type04=utd
Type05=ute
Type06=uti
Type07=utt
Type08=are
[MRU_nss]
Res00=_inc_gennui
Res01=g1_area_onenter
Res02=onmodulenui
Res03=onmoduleload
Res04=_inc_functions
Res05=_inc_debug
Res06=delete_me
Res07=checkvariables
[MRU_dlg]
Res00=x0_skill_ctrap
Res01=g1fencepost
Res02=ahfencepost
Res03=w2anchor
Res04=w2_anchor
Res05=dmspeaker
Res06=ah_post
Res07=d1_anchor
[MRU_utp]
Res00=areatransition
Res01=wm_compass
Res02=wm_worldmap
Res03=wm_pcicon
Res04=wm_maphelp
Res05=wm_icon_village
Res06=wm_icon_ruin002
Res07=wm_icon_ruin001
[MRU_utc]
Res00=npc_ezmerelda
Res01=r1_giantsnake
Res02=r1_giantfrog
[MRU_utd]
Res00=r1_barreddoor
Res01=r1_weakdoor
[MRU_ute]
Res00=g1_ratencounter
[MRU_uti]
Res00=it_mortarpestle
Res01=it_poison033
Res02=it_poison027
Res03=it_poison021
Res04=it_poison015
Res05=it_poison009
Res06=it_poison003
Res07=g1_it_evertorch
[MRU_utt]
Res00=g1_secretobject
[MRU_are]
Res00=whitecrag002
Res01=whitecrag005
Res02=whitecrag004
Res03=whitecrag003
Res04=whitecrag001
Res05=catacombs
Res06=whitecragcave
Res07=whitecrag
[Recent Files]
MRU0=C:\Program Files (x86)\Steam\steamapps\common\Neverwinter Nights\data\mod\Contest Of Champions 0492.mod
MRU1=D:\Documents\Neverwinter Nights\modules\Winter's Night.mod
MRU2=D:\Documents\Neverwinter Nights\modules\NUI_PopUpGUI.mod
MRU3=D:\Documents\Neverwinter Nights\modules\NUIGameRules.mod
MRU4=D:\Documents\Neverwinter Nights\modules\NUIPersistentChest.mod

**Comment by LaputianBird** [comment]
Test it with a new empty userdirectory

**Comment by pstemarie** [comment]
> Test it with a new empty userdirectory

Just tried - same error.

**Comment by virusman** [comment]
@pstemarie In the first crash, it looks like it was not able to find the tile model.

Internal note: `NewCAurObject((char *)ap_Tile->Name);` returned `nullptr`, causing `pObj->GetPartLocalPosition(l_sLightNodeName.c_str(), &l_vPosition, &l_qOrientation);` to dereference the null pointer.

**Comment by pstemarie** [comment]
That's odd - iirc that's the microset in the repro mod. I have tried it several other bioware/beamdog tilesets and get the same result in each.

**Comment by virusman** [comment]
It's very weird. Both crashes are something that would happen with invalid data or resources, the fact that it's happening with default tilesets but can't be reproduced by others leaves me puzzled.

**Comment by virusman** [comment]
Ok, I was able to reproduce this with MicroSet.

**Comment by virusman** [comment]
@pstemarie Verified and fixed for creatures. I don't see how the same issue could happen with placeables though. Please create a new issue if you see this happening with placeables (while there are no creatures in the area, only placeables).

**Comment by pstemarie** [comment]
Will do. Thanks for fixing this - it was annoying to say the least.
