### ISSUE TITLE
8193.29 - CreateObject is not looking/finding a safe location nor moving existing objects in that location

### ISSUE THREAD

**Issue by TomRotfl** [Beamdog/nwn-issues#349]
**To Reproduce**

Here is a simply corpse creation i do on my pw, to reproduce:
- Create a copy of the `Plague Victim Corpse` placeable
- Set flags: `usable`, `plot`, `has inventory` (this is my use case anyway)
- Make a character fire this script:
```
object oPC = OBJECT_SELF;
object oCorpse = CreateObject(OBJECT_TYPE_PLACEABLE, "my_corpse_ref", GetLocation(oPC), FALSE, "my_corpse_new_tag");
```

**Specifics**

 - OS: Client - Windows | Server - Linux
 - Game build: 8193.29
 - Distro platform: Client - Steam | Server - Docker
 - Content overrides: only 2da files inside of hak packs and override folder
 - Regression: no specific idea, but it was working fine in 8193.20 for sure

**If needed, describe the bug**

- The created objects will not be placed in a safe zone, nor the character in that same location will get moved to make room for the placeable. The placeable will be put in the same location of the caller, thus stucking caller making it unable to move unless the placeable is destroyed, or the character relogged.
- I have heard from others that this also happens if you do the opposite: create a creature object in the same location of an existing placeable.

Please let me know if more data or examples are needed.

**Comment by Arvirago** [comment]
I have this bug now too. It was working at least in 8193.23.

**Comment by Soren217** [comment]
Thank you for the bug report - we've identified the issue and it should be fixed by next patch. :)
