### ISSUE TITLE
Crash when starting new module (or loading game) with character with items of a baseitem that doesn't exists in such module/save.

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#351]
**To Reproduce**

 - Start a vanilla campaign and select uploaded character.
 - Client might crash, does not happen everytime, several repeats might be needed.
 
[0000000valeriasw.zip](https://github.com/Beamdog/nwn-issues/files/6838674/0000000valeriasw.zip)

**Crash Dump**

[nwmain_crah-dumps.zip](https://github.com/Beamdog/nwn-issues/files/6838676/nwmain_crah-dumps.zip)

**Specifics**

 - OS: Windows 10
 - Build: .28 nwmain.exe
 - Distro: Beamdog
 - Repro Rate: random
 - Content overrides: irrelevant

**Details**
When the game doesn't crash, the inventory is bugged as the custom invalid items aren't deleted and appear invisible in inventory too.
Not a critical issue, as I can edit my character and delete these items, but I think this is somewhat usual use case as players might be exporting their character from one singleplayer to another, and anytime they have custom baseitem items, this might happen.

Well at least this is my guess of what the issue is really about, I can't read the dumps so it is just educated guess, might be something else entirely.

**Comment by niv** [comment]
Thanks for the report.

That's sort of expected and I don't see that being fixed soon though. When playing content, all 2da need to match with the local data, both module and characters.

The same happens in MP: If you join with a mismatched 2da file, your network stream will go out of sync as soon as you get a baseitem sent that mismatches from what the server expects it to be (e.g. server sends you complex baseitem fields, you only read a simple appearance); and you will hang or crash.
