### ISSUE TITLE
Custom Spellcasters feedback

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#357]
I couldn't think of better place to post this, so sorry if it is not the right place.

Anyway, you probably know I am the one who brought custom spellbooks into NWN1 using NWNX and NWNCX. Since I cannot redo my work under EE anymore due to the client modification ban, please think about improving upon this. The current implementation of the custom spellbooks is very basic and limited. It is missing half the functionalities my implementation under NWNCX offered. Here is a list with explanation.

1) We still cannot select spells with a bard-like spellcaster when taking levels in prestige class improving arcane spellcasting capatibilities. This was requested many many times by dozen of peoples. I know very well this is not easy to do, but you could have do what I did several years before already - to allow select the missing spell levels at the base class level up. It is not ideal, but it suffices and it is actually very simple to do. It just needs a function GetSpellProgressionModifier and add this to the base class level in functions CNWCCreatureStats::GetSpellsKnownPerLevel and CNWCCreatureStats::GetSpellGainWithBonus and CNWSCreatureStats::ComputeNumberKnownSpellsLeft and CNWSCreatureStats::GetSpellGainWithBonus +effect caster level (if that is not rewritten already, I did that in CGameEffect::SetCreator function).

2) customizing prestige class spellcasting progression. This is trivial to do and is tied to the previous point. Currently, we cannot specify exact levels at which the prestige class improves spellcasting neither which type of it. For example in DnD Rules, the progression of the Pale Master should be +1 per level but starting at lvl 2. Another case is Mystic Theurghe which should improve both arcane and divine by +1 per level till lvl 10. And +1 to arcane at each odd level and +1 to divine at each even level. Here is a 2da example that shows my implementation:

6 lines from cls_prog_mystic.2da:

      2DA V2.0
      
            Level    ProgOption   Arcane    Divine
      0     1        0            1         1
      1     2        0            2         2
      2     3        0            3         3
      3     4        0            4         4
      4     5        0            5         5
      5     6        0            6         6

(Note, that this can be done via NWNX under EE as except the bard-like casters, the spell progression is entirely server-side.)

3) Is it not possible to create a custom spellcaster who would be casting like a bard but had access to all spells automatically like a cleric. Ie. MemorizesSpells = 0 + SpellbookRestricted = 0. These values make player not to select spells when levelling up which is okay, but the spellbook appears empty. (This can be tested in issue #356 with assassin class which is set this way). Current 2da structure already allows this and I think all that is needed is to add all known spells for the class and available spell levels at level up.

4) Is it not possible to create a custom spellcaster who would be casting like a bard but learning spells like wizard (which is how Harper Scout should work according to DnD rules). Unfortunately current 2da columns structure doesn't allow this. Perhaps the Learn Scroll column might be used to indicate this, but it is not perfect as someone might want to create a class like this but without scroll learning. Btw, learning scroll doesn't work on bard-like classes (can be tested in #356 again as the Harper Scout has this set).

5) Is not not possible to create Warlock-like spellcaster, ie. spellcaster who can cast his spells without limit. The problem here is with customization. I did this by creating a new 2da and column to refer to this 2da. 2da allowed to specify which spell level will be unlimited for each class level. Customization is preffered because builder might want to make spells unlimited after reaching specific level or just make cantrips unlimited. Unfortunately builder might want to make a both wizard-like caster with unlimited spellcasting possibility and bard-like so it is not possible to reuse SPKN 2da table. My suggestion is a new column in CLS_SPGN_* 2da with name like "NumLevelsUnlimited" or something like that. That would allow to make both 5DnD unlimited cantrips and Warlock and possibly anything else.

6) Is is not possible to create a custom spell type. Now this is super advanced feature so I doubt I persuade you to implement it, but if we are to create a Warlock, then we don't want Palemaster nor custom prestige class improving divine spellcasting capatibilities to improve his spell selection. We would also want to create a new prestige class Hellfire Warlock which improves Warlock spellcasting capatibilities, but not any arcane or divine class spellcasting capatibilities. I managed to offer this functionality via a combination of a new column in classes.2da which specifies the spell type name ie . "Invocation" and an custom prestige class spellcasting progression calculation (which I described in (2) ) which then read column names and compares them to this value. My code is actually very complex and allows to make various prestige class types ie. the ProgOption column in that 2da example. I can explain in more detail if needed.

**Comment by tinygiant98** [comment]
Thanks for the feedback.  This is a feature request and is out of scope for this repository.  There are new discussion and feature request forums in the NWNX discord server.  Please include these suggestions there for potential future action.
