### ISSUE TITLE
nwmain crash on area load

### ISSUE THREAD

**Issue by stenly87** [Beamdog/nwn-issues#358]
**To Reproduce**
    
   install hak [module and hak.zip](https://github.com/Beamdog/nwn-issues/files/6898160/module.zip)

 - Enter the first area. Here the placeable is created during PC enter and there is no error
 - Enter the second area. Here is the same placeable set and saved in the toolset. Game crashes.
 - You can save the game, while in the first area. And it loads without error. But next area still crashes client

    [Crash Dump.zip](https://github.com/Beamdog/nwn-issues/files/6898150/Crash.Dump.zip)

**Specifics**

 - OS Windows 10
 - Game build 8193.28, 8193.30
 - Distro platform Steam
 - Repro Rate 100%
 - Content overrides? (model, texture in test.hak)

**Comment by virusman** [comment]
Is it a regression? Did this happen with earlier versions?

**Comment by virusman** [comment]
(Crash in `LightningEmitter::Initialize` when initializing a static placeable with a lightning emitter)

**Comment by stenly87** [comment]
oh, disabled "Static" on a placeable and it works with no error. Mean, Its my bug?
