### ISSUE TITLE
[8193.9+] TNO Cave Transparent Doors - Wrong Model Reference

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#36]
**Specifics**

 - Windows 10
 - Game build 8193.9+
 - Steam

**If needed, describe the bug**

The SET file references for transparent doors for the various features/groups using them in the TNO tileset are pointing to the wrong line number in doortypes.2da. This causes the SAM mesh on the door model to extend far beyond the surrounding tile features.

The easiest fix is to point the offending DoorType references in the SET file to line #240 in doortypes.2da - this is the correct model for those tiles.

**Comment by Bill-Harper** [comment]
The one cave I was aware of, tno01_r10_01, is already set at Type=240. Which tiles are you referring to, and/or which (wrong) door type are they using?

**Comment by pstemarie** [comment]
Bill, after verifying my STEAM install files, the issue is gone and the entrances look correct now.

**Comment by pstemarie** [comment]
No longer an issue.
