### ISSUE TITLE
Calling GetLastRunScriptEffect() in EffectRunScript's OnRemovedScript returns an invalid effect when the effect is removed by RemovEffect.

### ISSUE THREAD

**Issue by txf063000** [Beamdog/nwn-issues#360]
**To Reproduce**

 - Add the following two scripts to a module:
[runme.nss](https://github.com/Beamdog/nwn-issues/files/6912135/runme.txt)
[runscriptend.nss](https://github.com/Beamdog/nwn-issues/files/6912136/runscriptend.txt)

- Trigger [runme.nss](https://github.com/Beamdog/nwn-issues/files/6912135/runme.txt).
- Combat log displays "0" for false, because the effect is invalid.

**Specifics**

 - Windows 10
 - Build ID 7070152 (Steam "development" Beta)

**Description of Issue**

- Calling RemoveEffect on a RunScript effect will trigger the OnRemovedScript, but the effect from GetLastRunScriptEffect will be **invalid**.
- If a RunScript effect expires from its duration, GetLastRunScriptEffect in OnRemovedScript is **valid**.

**Comment by Daztek** [comment]
It's a bit of a quirk. RemoveEffect() sets a flag on the effect that makes GetIsEffectValid() return false. 

The effect returned by GetLastRunScriptEffect() will still be valid in the OnRemove script, so you can still get data from it even if GetIsEffectValid() returns false.

**Comment by txf063000** [comment]
Thank you. It does work as you've described, and I'm able to get the SpellId from the effect even though it is flagged as invalid.
