### ISSUE TITLE
Dynamic placeables fade in

### ISSUE THREAD

**Issue by Proleric** [Beamdog/nwn-issues#361]
**To Reproduce**

 - Put the attached contents in Development folder temporarily
 - Run the demo module
 - Notice how chairs fade in gradually
 - Remove the OnEnter script, uncheck Static on table, run module
 - Notice how table now fades in gradually
 - Save/load to witness that it doesn't just happen on first entry to an area

**Specifics**

 - Win 10
 - 8193.28 (but 8193.30 is the same)
 - Beamdog client
 - Overrides only as supplied
 - Seems to have been getting progressively worse since 1.69

**If needed, describe the bug**

Many placeables seem to fade in very slowly when not static, which looks dreadful. As the demo shows, this is true, even if the placeables are not created by script. 

Also occurs when a door is opened into a room containing a dynamic placeable.

This bug discourages use of the (otherwise excellent) placeable scaling feature.
[Proleric Round Table.zip](https://github.com/Beamdog/nwn-issues/files/6939116/Proleric.Round.Table.zip)

**Comment by Daztek** [comment]
Seems like normal non-static placeable behavior for me


https://user-images.githubusercontent.com/31415508/128380691-8331e3e7-8c1f-402a-83c6-ba1fae66fe99.mp4

**Comment by Proleric** [comment]
Treat it as an enhancement request if you like.

Either way, to my eyes, this is by far the biggest visual glitch in the game now, ugly and immersion-breaking.

**Comment by virusman** [comment]
@Proleric Thanks for the request but this repo is only for bug reports.
