### ISSUE TITLE
[Feature Request] - Make GUIEVENT_PARTYBAR_PORTRAIT_CLICK also trigger when click on a portrait in the chat panel

### ISSUE THREAD

**Issue by Chimerik** [Beamdog/nwn-issues#366]
The GUIEVENT_PARTYBAR_PORTRAIT_CLICK event was recently added to the base game, however it is not triggered when clicking on a portrait in the chat panel (which I guess is normal, since it's name PARTYBAR).

It would be great if it could also be triggered by clicking the portrait on the chat panel, since both portraits do pretty much the same thing.

**Comment by tinygiant98** [comment]
Feature requests are outside the scope of this repo.  Please visit the feature request form on the NWNX discord.
