### ISSUE TITLE
iOS: Shields without TGA texture crashing game.

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#377]
**To Reproduce**

 - This is happening on a PW Arkhalia to players playing on iOS when they have character with shield equipped on login or when they open any inventory with such shield.
 - This started very recently when I removed lowres TGA textures that I kept in haks for Android support as Android used to not be able to handle DDS textures, but that was fixed already. Nobody else, but iOS players has any issues, and it is only shields, not anything else that uses DDS like placeables, tilesets.
 - Shields are from Project Q.

**Crash Dump**

[crashlogs.zip](https://github.com/Beamdog/nwn-issues/files/7094504/crashlogs.zip)

**Specifics**

 - OS: iOS
 - Game build: .28
 - Distro platform: iOS
 - Repro Rate: 100%
 - Content overrides? irrelevant

**Comment by niv** [comment]
This issues repo is only for desktop bugs.
