### ISSUE TITLE
[8188+] New fancymapped loaded bodyparts change old ones colors

### ISSUE THREAD

**Issue by Dafena** [Beamdog/nwn-issues#38]
**To Reproduce**

1. Have a bodypart that supports fancymapping.
2. Load the same model with different colors.
3. The old one will swap its colors for the same the new one has.

**Specifics**

- Issue persists since build 8188.
- OS: Windows 10
- Distro platform: Steam

I've included a zip with three videos showcasing it, a hak with a uncompiled head and a test mod from build 8187 (last working one). When you load it talk to the bodytailor and apply head 97 to yourself, it should change the colors from both to match your own.

[headbug.zip](https://github.com/Beamdog/nwn-issues/files/4522624/headbug.zip)

**Comment by Soren217** [comment]
The attached module requires a hak called "tw1people" - could you upload that as well?

**Comment by Dafena** [comment]
My bad! Here it is a mod that doesn't requires it.
[headbug.zip](https://github.com/Beamdog/nwn-issues/files/4523644/headbug.zip)

**Comment by LaputianBird** [comment]
To note - the same behavior happens when multiple fancymapped helmet models are rendered at the same time - they all use the same plt channel colors, regardless of the value stored in each helmet's GFF

**Comment by Soren217** [comment]
After some investigation, it seems to me that the easiest solution here is to simply not specifying any texture0 in your material file. This will make it use the plt with the same name as the head model like usual, while still allowing you to add other maps through texture1, texture2 etc.

At some point it would be nice to allow specifying a PLT in the material file, but the above should work for now.

Could you verify? Thanks! @LaputianBird , @Dafena

**Comment by Dafena** [comment]
Has been decided by the community to ignore texture0 line.
