### ISSUE TITLE
[8193.31] NuiTextEdit multiline doesn't text wrap

### ISSUE THREAD

**Issue by summonFox** [Beamdog/nwn-issues#382]
**To Reproduce**

 - Start a new module in the DM client, such as the Prelude.
 - In the nwscript debugger run this code snipped without main(){}.
 ```nss
#include "nw_inc_nui"
void main()
{
	json jCol = JsonArray();
	json jRow = JsonArray();

	json jTextEdit = NuiTextEdit(JsonString(""), JsonString("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."), 65535, TRUE);

	jRow = JsonArrayInsert(jRow, NuiHeight(NuiWidth(jTextEdit, 475.0), 440.0));
	jCol = JsonArrayInsert(jCol, NuiRow(jRow));

	json jRoot = NuiCol(jCol);
	json jWindow = NuiWindow(
		jRoot,
		JsonString("NuiTextEdit Test"),
		NuiRect(-1.0, -1.0, 500.0f, 500.0f),
		JsonBool(FALSE),
		JsonBool(FALSE),
		JsonBool(TRUE),
		JsonBool(FALSE),
		JsonBool(TRUE)
	);

	int nToken = NuiCreate(GetFirstPC(), jWindow, "nui_textedittest");
}
```

**Specifics**

 - OS (Windows, Mac, Linux)
Windows
 - Game build (e.g. 8193.8, or commit hash)
8193.31
 - Distro platform (BDC, Steam, GOG)
Steam
 - Content overrides? (Steam Workshop? Overrides? Patch haks?)
No

**If needed, describe the bug**

NuiTextEdit with multiline on with text wider than the element disappears off the side instead of wrapping to stay inside the element.

This was tested on 1680x900 resolution with UI Scaling 1.0.

**If warranted, add videos/screenshots to showcase the issue.**
![2021-09-18 07_45_55-Greenshot](https://user-images.githubusercontent.com/46043493/133856983-2d3f6112-81eb-46c5-a34a-e776c2eff8b4.jpg)

**Comment by tinygiant98** [comment]
Fix targeted for .35.
