### ISSUE TITLE
[8193.32] Tile source lights that are off change to red after loading save game / CreateArea / CopyArea / JsonToObject

### ISSUE THREAD

**Issue by summonFox** [Beamdog/nwn-issues#390]
**To Reproduce**

 - Create an area with some tile lights turned off
 - Save the game
 - Load the saved game
 - The tile source lights that should be off are now red

Same issue occurs for areas created through CreateArea / CopyArea / JsonToObject

**Specifics**

 - OS (Windows, Mac, Linux)
Windows
 - Game build (e.g. 8193.8, or commit hash)
8193.32
 - Distro platform (BDC, Steam, GOG)
Steam
 - Content overrides? (Steam Workshop? Overrides? Patch haks?)
No

**Comment by summonFox** [comment]
This snippet reports the tile source lights for _off_ to be 255.

```nss
object oArea = GetArea(OBJECT_SELF);

int nWidth  = GetAreaSize(AREA_WIDTH, oArea);
int nHeight = GetAreaSize(AREA_HEIGHT, oArea);

int x, y;
for (x = 0; x < nWidth; x++)
{
    for (y = 0; y < nHeight; y++)
    {
        location lTile = Location(oArea, Vector(x / 1.0, y / 1.0, 0.0), 0.0);

        int nTileSourceLight1 = GetTileSourceLight1Color(lTile);
        int nTileSourceLight2 = GetTileSourceLight2Color(lTile);

        SendMessageToPC(OBJECT_SELF, "TILE x " + IntToString(x) + " y " + IntToString(y) + ": Src1 " + IntToString(nTileSourceLight1) + " Src2 " + IntToString(nTileSourceLight2));
    }
}
````

After running it on a copied/created/etc it reports the tile source lights are 254.

**Comment by niv** [comment]
This should be fixed in the latest preview build.
