### ISSUE TITLE
ResRef of Instanced areas are not set as you would expect(8193.32)

### ISSUE THREAD

**Issue by driller-nwn** [Beamdog/nwn-issues#391]
**To Reproduce**

Create an instance with either CopyArea() or CreateArea().

Run GetResRef() against the instance.

 - OS (Windows)
 - Game build (e.g. 8193.328)
 - Distro platform (Steam)
 - Content overrides? (None)

<img width="271" alt="instance_and_resref" src="https://user-images.githubusercontent.com/37457443/134776214-41ac5b08-71b6-4559-ac44-6e49ce3f15fd.PNG">
.

**Comment by niv** [comment]
Looks ok to me. What did you expect the resref to read as?

**Comment by driller-nwn** [comment]
It used to set the Instance's sResRef to the original area you copied from or it was sSourceResRef when you used CreateInstance(). 

The behavior has changed. It breaks things for me, but I can work around it.

**Comment by niv** [comment]
That change was unfortunately needed to support save games. Hope your workaround isn't too much of a bother!
