### ISSUE TITLE
Over 2 meshes with same references to a texture causes game mdl to disappear

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#396]
If you have more than 2 meshes reference the same texture "bitmap=" in ASCII, then all meshes that reference that texture will disappear in game.  This bug happens in game, but not the toolset.  Doesn't seem to happen consistently.  Perhaps on higher poly meshes?
 
TO REPRODUCE

- Take attached zip file and dump in development folder
- Move "meshbug.mod" to module folder
- Start up the module
- See the diagram with four chains - it renders fine in toolset.
- Run module in game - chains do not render.

FURTHER DEBUGGING

- Edit meshbug.mdl in development folder and set chain.002 to reference "cat01_chain02" instead; repeat for chain.003 and chain.004 for cat01_chain03 and cat01_chain04, respectively.  Note the mtr files themselves still reference the same underlyng texture set.
- run game; see that chains now render
- play with naming of textures in "meshbug.mdl", it seems whenever there is the same texture referenced, the meshes sharing the same "bitmap" value aren't rendered in game

**Specifics**

 - Game build .33 stable
 - OS Windows
 - Distro platform (BDC + Steam)
 - Content overrides? (Steam Workshop? Overrides? Patch haks?) attached
 - Regression? (Build which broke it, if known) unknown

**Comment by pstemarie** [comment]
Wondering if this is an MTR related issue as I'm not seeing this? I have lots of models with multiple meshes referencing the same bitmap - tiles, placeables, creatures, etc.

**Comment by Txpple** [comment]
Did you use the steps to reproduce and you don’t see it?  I have seen it a number of times, but not always.  This one captures it.  I have other samples I could reproduce with, too.  So far the theme I’ve seen is higher poly meshes (5k+).

**Comment by Txpple** [comment]
Yea, same, it works as intended … usually.  MTR looks fine, tho, and it’s interesting to note there is a mesh set in the attached repro that all reference a diff MTR four times (the four wood beams) just fine.

**Comment by Dafena** [comment]
This was fixed on the preview for .35 (patch bf9a78f0 to be more precise)

> Revised and improved handling of model vertex data, allowing a greater amount (~x3) of faces/vertices per mesh and better performance for high poly meshes.
