### ISSUE TITLE
[BUG] 8193.33 Money does not putdowned on objects of dirt, grass, etc.

### ISSUE THREAD

**Issue by LiarisFreeze** [Beamdog/nwn-issues#399]
Money does not putdowned on objects of dirt, grass, etc.
This is only seen on non-static objects - grass, dirt, carpet.

 - OS (Windows)
 - Game build  8193.33 
 - Distro platform Steam
 - Content overrides? (No)

video
https://www.youtube.com/watch?v=FtjdY3ziGug

**Comment by eveferon** [comment]
Confirmed. It seems to be a simple issue. Whether the plc is usable or not, has inventory or not, the gold disappears in it.
