### ISSUE TITLE
Recommended button crashing when there are no options available.

### ISSUE THREAD

**Issue by pyro7r34d** [Beamdog/nwn-issues#40]
**To Reproduce**

-Choose any class that has no corresponding package row on the packages.2da (such as a custom class).
-Attempt to use the recommended button during the packages selection screen creation
-Game crashes

**Crash Dump**
- Windows: Attach the generated .log AND .dmp
[Logs.zip](https://github.com/Beamdog/nwn-issues/files/4542442/Logs.zip)

**Specifics**

 - Windows
 - 8193.9
 - Steam
 - 100%
 - Overrided custom packages and classes.2da. (I simply remoed the rows from the packages.2da to re-create the bug).

**Comment by TotallyNotLoinne** [comment]
**+ Repro:**


This is an example classes.2da with the new classes having blank "Package" column.

- Load any module with the hak/override/development containing this .2da
- Start creating a character
- At the class selection, pick any class option that goes after vanilla "Purple Dragon Knight"
- Pick whatever at the next screens
- At the "Packages" screen you will see an empty list, as the class does not have any packages assigned as default 

![image](https://user-images.githubusercontent.com/59966480/99321899-53b58380-2888-11eb-9e8b-476491f6bdb1.png)

- Pressing "Recommended" button at the Packages screen crashes the game

**Desired behaviour:**
- When the current levelled up class has no package attached to it, the button does nothing (Ability screen, skill selection screen, spell selection screen, feat selection screen)

**Example 2da:** [classes.zip](https://github.com/Beamdog/nwn-issues/files/5550357/classes.zip)
