### ISSUE TITLE
[8193.33] ActionMoveToObject makes all NPCs face east.

### ISSUE THREAD

**Issue by summonFox** [Beamdog/nwn-issues#400]
**To Reproduce**

 - Create a NPC with the default AI script packages for WalkWayPoints.
 - Create a POST_ waypoint facing north for the NPC.
 - Set `X2_L_WAYPOINT_SETFACING 1` on the waypoint.
 - The NPC will now turn to face east when ActionMoveToObject in the creature's WalkWayPoints routine is called, then immediately turn to face the waypoint orientation (north) after.

You can manually test that ActionMoveToObject makes the NPC face east by calling it directly after the above setup by running this in the script console on the NPC:

`ActionMoveToObject(GetNearestObjectByTag("POST_" + GetTag(OBJECT_SELF)));`

**Specifics**

 - OS (Windows, Mac, Linux)
 Windows
 - Game build (e.g. 8193.8, or commit hash)
8193.33
 - Content overrides? (Steam Workshop? Overrides? Patch haks?)
No
 - Regression? (Build which broke it, if known)
Broke in a build somewhere between .28 and .33.

**If needed, describe the bug**

ActionMoveToObject  makes all creatures face east. When you have NPCs on a single WP_\*\_01 or POST_\* waypoint, the NPC will turn to face east every WalkWayPoints call. If the waypoint is using `X2_L_WAYPOINT_SETFACING 1` then the NPC ends up doing a twitchy dance on the spot every few seconds as they turn to face east then turn to face the correct desired direction.

**Comment by pstemarie** [comment]
I was able to fix this for the WalkWayPoints function by editing the XP1 include x0_i0_walkway. Not sure if it will help with this bug specifically.

Add this block of code at line 387ish (after the IF(bIsFighting... statement)

[code]
// * if I'm already at my POST, I should continue walking waypoints
if (GetDistanceToObject(GetNearestObjectByTag("POST_" + GetTag(OBJECT_SELF))) < 1.5)
     return;
[/code]

You'll need to then recompile ALL scripts that call WalkWayPoints

**Comment by Finaldeath** [comment]
Fixed in 35: 
* Fixed creatures facing east when standing on _POST waypoints.
