### ISSUE TITLE
Attacking through jail-doors

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#406]
**To Reproduce**

 - Make a bridge with the jail-doors and make then locked, put spawn point at a one side and put some npc right behind them on the opposite side.
 - Attack the npc. It works. Even without any weapon the reach is quite absurd.

**Specifics**

 - OS: all
 - Game build: .33
 - Distro platform: irrelevant
 - Content overrides: irrelevant
 - Regression? Yes, pretty much sure it was one of those versions that changed pathfinding.

**If needed, describe the bug**

I am not sure whether this is another "feature", but even if it was, we builders have no controll over it and the reach behind doors is really absurd. As an archer I was attacked by longsword holding trogodlytes behind the doors pretty much at a half tile distance. If this is feature then we, builders needs a way to disable it , if we dislike it (I have several areas where this breaks intented difficulty of the dungeon where player was supposed to unlock doors while being attacked by archer or mage behind them) or modify it like apply some kind of penalty to AB or DMG as such attacks can't be realistically speaking so strong and it would be rather easy to dodge them.

**Comment by Finaldeath** [comment]
Fixed in 35.
