### ISSUE TITLE
[8193.33] Nui windows consume key-release and as a result prevent default key-release

### ISSUE THREAD

**Issue by eveferon** [Beamdog/nwn-issues#408]
**To Reproduce**

 - Load test module (character appears in an area with onarea enter script to open a simple nui window)
 
[nui key release.mod.zip](https://github.com/Beamdog/nwn-issues/files/7526817/nui.key.release.mod.zip)

 - Press any of the following keys (move character, rotate camera) and do not release
 - While key is pressed and character is moving (camera rotating) move mouse cursor on a Nui window
 - Observe, that the input is released immediatly although the key is still pressed
 - Release the key and observe that the input is stuck by moving cursor outside nui window and character resuming moving (camera rotating) although no key is pressed
 - Play around with it by simply moving mouse to and from nui window you will see that everytime you move the cursor outside the window the character will start moving or camera will start rotating

**Specifics**

 - OS (any)
 - Game build (e.g. 8193.33)
 - Distro platform (any)
 - Content overrides? (not relevant)
 - Regression? (since first release)

**If needed, describe the bug**

It is a big issue. Players run into it all the time when working with nui windows. They are confused as they need then to press all the stucked buttons to undo the behavior.

See the video with the behaviour
https://youtu.be/zvMO46U5atA

**Comment by MhlChesnokov** [comment]
I can confirm this behavior

**Comment by gm-xanther** [comment]
Issue is easily reproducible using the debug windows as well (ctrl+shift+F12) - using WASD to move character and mousing over the window will always cause unintended results.
