### ISSUE TITLE
VM: GetObjectUUID() does not return an UUID for areas

### ISSUE THREAD

**Issue by Daztek** [Beamdog/nwn-issues#41]
**To Reproduce**

 - Put `PrintString("UUID:" + GetObjectUUID(GetAreaFromLocation(GetStartingLocation())));` in a script somewhere and run it.
- Expect to get an UUID, but instead get an empty string.

**Specifics**

 - Client: Windows, Server: Linux
 - Game build: 8193.11
 - Distro platform: Steam
- Content overrides: None

**Comment by niv** [comment]
Seems to be a documentation issue. Feature was never meant to support Areas. 

Out of curiosity, what is the usecase where you ran into this?

**Comment by Daztek** [comment]
Purely due to laziness. I was working on an area instancing system and wanted to store a reference to the area in an array. I only had functions for string arrays and didn't want to add an object variant, so I was like, "why not just store the UUID"
