### ISSUE TITLE
Pathfinding is broken

### ISSUE THREAD

**Issue by pspronck** [Beamdog/nwn-issues#415]
If I send an NPC to a waypoint, and that waypoint is blocked because another NPC is standing on it, then the NPC that gets the command to move will move into a straight line towards the waypoint and stop at the first obstacle.

I have confirmed this by writing a small module, which has two NPCs which are hostile to each other, which spawn automatically at different points in the area if they are not yet present in the area. They both move to the same waypoint (in a slightly roundabout way because there are obstacles, in this case pits as I use the Crypt tileset), and their heartbeat will always command them to move to that waypoint. As soon as they meet, they fight. When one is killed, the other one's heartbeat makes them move onto the waypoint. The first one gets respawned, and will now move in a straight line in the direction of the waypoint, stopping at the edge of a pit. As long as the waypoint is held by the other NPC, they will not move again, despite getting the command to move every heartbeat.

This bug has been introduced sometime in the past year, as it definitely was not there a year ago, and it isn't in the 8186 version.

**Comment by pspronck** [comment]
FYI, here is the module that demonstrates the bug. Two fighters spawn, move to the middle, one kills the other, the killed one gets respawned and now tries to move to the middle in a straight line, getting stopped at the edge of a pit.

[Pathfinding bug demo.zip](https://github.com/Beamdog/nwn-issues/files/7609649/Pathfinding.bug.demo.zip)

**Comment by pspronck** [comment]
The bug is fixed in version .34.

**Comment by Finaldeath** [comment]
Fixed.
