### ISSUE TITLE
Nui Lists Throw Vector Error Upon Resizing List

### ISSUE THREAD

**Issue by zunath** [Beamdog/nwn-issues#427]
**To Reproduce**

- Load the attached module
- Click on the chest 
- Scroll the UI window down to the bottom
- Click the "Update List" button
- A vector error will display

**Specifics**

 - OS Windows
 - 8193.34  
 - Steam
 - No content overrides
 - Regression from 8193.33 -> 8193.34. Downgrading to .33 fixes the issue

**If needed, describe the bug**

I believe this is an error with the way NUI resizes the element after its contents change. It's consistently reproduceable any time you have a bound list, scroll to the bottom of said list, and then update the bound list with a smaller set of items.  If it helps, this issue was not present on 8193.33 and downgrading addresses the problem. 

[Nui_Vector_Repro.zip](https://github.com/Beamdog/nwn-issues/files/7739674/Nui_Vector_Repro.zip)

**Comment by Shad000w** [comment]
This started happening quite frequently with NUIs that worked without issue previously in version .34 and it is very annoying.

**Comment by summonFox** [comment]
This also happens with NuiGroups and NuiSetGroupLayout.

**Comment by zunath** [comment]
[Nui_Vector_Repro.zip](https://github.com/Beamdog/nwn-issues/files/8692894/Nui_Vector_Repro.zip)

Daz has produced a workaround for the issue. 

skill_window.nss: l96-97

mod_nui.nss: l84-87

**Comment by zunath** [comment]
Another workaround is to ensure your list size never reduces and instead make all items within the list are set to Visible = False.

Demo of this is shown here: https://cdn.discordapp.com/attachments/382306806866771980/975391210141278238/2022-05-15_15-35-50.mp4
