### ISSUE TITLE
[8193.9+] Renderaabb command does not render all tile walkmeshes

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#43]
Reported on the Vault by BlackRider and confirmed by me. The breakage coincides with the fix made to get rendertilepathnodes working. THIS WAS WORKING in previous versions of EE (prior to 8193.9).

**To Reproduce**

1. Run the game using any module and any tileset. 
2. Enter DebugMode.
3. Type renderaabb 1

You will see that several tiles do not render the walkmesh. It appears to be the same tiles each time.

![30fb8a588adacda3bb9e7aa25b4488dddd960fb1](https://user-images.githubusercontent.com/58920224/80915489-a9797280-8d20-11ea-9641-559cc9629795.jpeg)

![67239e266c1d0c01ceb8c81e06db8e7fcee08886](https://user-images.githubusercontent.com/58920224/80915491-ab433600-8d20-11ea-90aa-6da76ad3d81d.jpeg)

**Specifics**

 - Windows 10
 - 8193.9 +
 - All Distros
 - No overrides

**Comment by Soren217** [comment]
Thanks for the report, should be fixed by next update.
