### ISSUE TITLE
8193.34 regression; CTRL-click + drag selection functionality disabled for DMs

### ISSUE THREAD

**Issue by alfa050moonshaes** [Beamdog/nwn-issues#432]
**To Reproduce**

 - Log into DM client
 - Spawn a number of NPC creatures
 - Hold CTRL and attempt to click+drag across the area of the map containing the creatures
 - No bounding box appears and you cannot select multiple creatures using click+drag. See comment from Calgacus below this no longer works REGARDLESS of how the 'server.player-party-control' setting is configured in settings.tml. It appears that the change to that setting in 8193.34 has bugged the feature so it no longer works at all.
 ~~Whereas before 8193.34, DMs could select groups of creatures using CTRL-click and drag, which would produce a square 'bounding box' on the terrain that could then be manipulated over the group of creatures, this functionality is now disabled by default due to the change to the way the setting server.player-party-control works. Now DMs can only use this functionality if it is also enabled for players, which is a regression and causes significant difficulties for DMs in some scenarios.~~

**Specifics**

 - Regression: 8193.34 contains the patch note: 'Game: Disable ctrl-drag selection box on clients when server.player-party-control is off (the default). Note that clients will have to reconnect if you toggle this setting while a game is up.' However regardless of that setting, the functionality does not appear to work (see comment from Calgacus below). In any case, if fixed, the setting would need to be separate for DMs versus players as this is a critical feature for many DMs to have and most servers do NOT want players to have access to the feature. The simplest solution would be reverting it to the pre-8193.34 situation (DMs can use the feature regardless of what settings.tml says).

**If needed, describe the bug**

I was asked to report by people on the Vault. ~~The change to how server.player-party-control works means that DMs can only use the CTRL-click and drag functionality when that setting is ON. However,  when that setting is ON, all players can use CTRL-click+drag to select and manipulate their henchmens' actions.~~
~~This is a regression because presumably 'server.PLAYER-party-control' (name of the setting in settings.tml) is only supposed to apply to PLAYERS (emphasis added).~~
~~This is also a regression because DMs use that click+drag functionality all the time in large- and medium-scale scenarios, and most PWs do not want players to have that functionality at all, preferring players to only have access to the base game's henchmen AI. ~~

Update: per Calgacus's comment below, the update has broken the functionality for DMs to click+drag to select creatures, REGARDLESS of what 'server.player-party-control' is set to in settings.tml.
This is therefore a true bug arising from 8193.34.

A number of DMs have posted about this on the Vault discord, hence my reporting it as a regression. The quick solution would be to reverse the change made in 8193.34. The 'ideal' solution would be for there to be separate settings introduced to settings.tml; one which is the same as the current setting server.player-party-control, and a new one called server.DM-party-control. That way there would be full granularity over how these settings operate. However in the meantime, a quick fix would be very much appreciated. Thanks so much

**Comment by calgacus** [comment]
Even with `[server] player-party-control = true ` I cannot use ctrl-drag in DM mode at least on Windows 10.

**Comment by Finaldeath** [comment]
Fixed in preview.
