### ISSUE TITLE
ActionCastSpell not working with sub-spells and metamagic

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#433]
**To Reproduce**

 - Create a cleric character that can cast level 2 spells and prepare extended protection of evil spell in his spellbook.
 - Force the character to cast it via script from placeable like this: AssignCommand(oPC,ActionCastSpellAtObject(SPELL_PROTECTION_FROM_EVIL,OBJECT_SELF,METAMAGIC_EXTEND));
 - Nothing will happen.

**Specifics**

 - OS: irrelevant
 - Game build: .34
 - Distro platform: was this ever relevant?
 - Content overrides?: irrelevant, engine issue
 - Regression? I think this issue was inherited from 1.69.

**If needed, describe the bug**

Character can cast non extended version just fine if it is memorized via script, but not extended. Didn't test it but I suspect this applies for all types of metamagic and all sub-spells, ie. spells which has the column Master != "".

**Comment by Finaldeath** [comment]
Closing as duplicate, see that bug report for info.
