### ISSUE TITLE
Areas with several non-static (dynamic) placeables pause when loading

### ISSUE THREAD

**Issue by A1-Gorgon** [Beamdog/nwn-issues#449]
**To Reproduce**

 - Create a module with an area containing 50 or more non-static placeables.
 - Entering the area from another area in the module. There will be a pause at the end of loading progress. More non-static placeables cause a longer pause.
 - Repeat the test connecting to a module running on a server (only Linux servers have been tested so far). The pause at the end of load progress doubles (approximately).

**Specifics**

 - Client OS: Windows 10 [21H2] (and others).
 - Server: Linux - Ubuntu 20.04 VMs (both local and online hosting). 
 - Game build: 8193.34 Windows client and Linux stand-alone server.
 - Distro platform: Beamdog client used for personal testing, but it has been confirmed with others. 
 - Content overrides: No custom content.
 - Regression: I can only confirm the delay was not present in 1.69.

Local testing with a module area containing 50 non-static placeables causes a pause of a few seconds after most of the progress bar loaded in under 1 second. 100 placeables doubles it and so on. Testing the same areas on a Linux stand-alone server doubles that pause, which is quite noticeable for players when it takes 10 seconds or more to load an area. Also, I've tested using 10 year old (slow) and new hardware running the client when connecting to a server, and the pauses remain constant for me.

The tests were done without any custom content and a clean server. It has been confirmed by several people using a variety of hardware, and some had even longer delays.  
Note: The use of NWNX's NWNX_OPTIMIZATIONS_ALTERNATE_GAME_OBJECT_UPDATE setting did reduce the server's load pause by close to 50%, if that helps. 

The same area tests in 1.69 would load the areas within a second or two, both in local and server tests. I know that making placeables static will improve it, but that isn't really an option for many older areas on a server converting to EE, with usable objects and readable descriptions. The NWNX optimization setting is a band-aid at best, with it causing other NWNX functions to be unusable, and there is still a noticeable pause loading some areas compared to 1.69.

Any help with this would be appreciated.

**Comment by VoidHamlet** [comment]
> Any help with this would be appreciated.

All, it's been a few months -- we could really use a hand.

**Comment by Finaldeath** [comment]
@A1-Gorgon @VoidHamlet have you tried the Preview version? see the NWN Developers Chat discord for information. There have been several optimisations and options available now for faster loading on clients which you can tune.

**Comment by A1-Gorgon** [comment]
> @A1-Gorgon @VoidHamlet have you tried the Preview version? see the NWN Developers Chat discord for information. There have been several optimisations and options available now for faster loading on clients which you can tune.

The NWNX_OPTIMIZATIONS_CLIENT_GAMEOBJECT_UPDATE_TIME_LOADING setting for NWNX really helped with this. .35 will improve on that too, so thanks to everyone who came through on this.

**Comment by Finaldeath** [comment]
This has been (mostly) solved by the 35 load time improvements.
