### ISSUE TITLE
NWN1 Crafting Affordability Bug

### ISSUE THREAD

**Issue by NWNGuthlac** [Beamdog/nwn-issues#450]
**To Reproduce**

- Character with ranks in Craft Weapon and 10-99 gold
- Attempt to Craft Halberd, no option to proceed
- Fails because the affordability test is checking against the cost of crafting a Two Bladed Sword

**Specifics**

 - Affects both NWN Diamond and EE, original craft interface code
 - issue is in x2_ci_gotgold_* scripts, line 36: struct craft_struct stItem =  CIGetCraftItemStructFrom2DA(s2DA,nRow,0);
 - last parameter (nItemNo) is 0 in all scripts, should iterate 1..4 for scripts _2.._5.

**Comment by tinygiant98** [comment]
Legacy scripts changes are out of scope.  See Readme.md/Rule 4.  If you need help creating the four override scripts necessary to fix this legacy script issue, please visit the Neverwinter Vault Discord.
