### ISSUE TITLE
Special Attacks Resolving Damage

### ISSUE THREAD

**Issue by LoveLessDev** [Beamdog/nwn-issues#453]
**To Reproduce**

Spells like Endure Elements (if they are dealing those types of damage) and Stoneskin are just simply dealt damage regardless on the actual results of Special Attacks (Knockdown, Called Shot, Disarm, Sap, Smite Evil, Smite Good, Stunning Fist). This means in the event that the attack misses due to any reason, then the effects are still damaged.

**Specifics**

* OS? Windows
* Game Build? 8193.34 (and any prior)
* Distro platform? Steam
* Content overrides? None

**If needed, describe the bug**

The problem so far as I can tell appears to be isolated to resolving damage from special attacks against **EffectDamageResistance** and **EffectDamageReduction** if they have a limitation set, regardless on the rolls of the attack or if it hit. There is no feedback that this is happening in the combat log.

Some possibly related issues, as they involve Damage Resist or Special Attacks: https://github.com/Beamdog/nwn-issues/issues/104 https://github.com/Beamdog/nwn-issues/issues/190

**Comment by LoveLessDev** [comment]
Attached is a save file with an area set up for reproducing the effect. Click the pillars to apply a VFX that absorbs 1 physical damage. It breaks through AC, Concealment, Epic Dodge, etc.

[000875 - Resist Repro.zip](https://github.com/Beamdog/nwn-issues/files/8925775/000875.-.Resist.Repro.zip)

**Comment by tinygiant98** [comment]
Slated for .36.
