### ISSUE TITLE
[8193.12] Walkmesh Issue - TDT01

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#46]
**Description**

Walkmesh issue with either tile tdt01_g08_01 or tdt01_go2_01 causing creatures to climb the wall then get stuck. Saving and reloading corrects the issue as it loads the creatures back on the "ground" mesh.

![Help_Im_Stuck](https://user-images.githubusercontent.com/58920224/81303785-2ae74280-904a-11ea-9819-4f63b3c20cd3.jpg)

**Specifics**

 - Game build 8193.12
 - OS Windows
 - Steam
 - Content overrides? None

**Comment by Bill-Harper** [comment]
Neither looked stellar, but G08 was the problem. Instead of having obscuring or blocking mesh on 1 of the walls, it had grass walkmesh instead. I also fixed overlaps, which may have caused this, and threwq in G01_01 because I noticed similar problems while in the file.

**Comment by Bill-Harper** [comment]
(_Fixed in a Previous Build_) Thanks for reporting, let us know if you have any future issues!
