### ISSUE TITLE
Crash on joining party in multiplayer server

### ISSUE THREAD

**Issue by bentusi16** [Beamdog/nwn-issues#461]
**To Reproduce**

- join any party in a multiplayer server
- within 3 minutes the game crashes with a fatal exception
- reproduced repeatedly and reliably since the july 22 preview build update

**Crash Dump**
[nwmain-crash-1658535910.log](https://github.com/Beamdog/nwn-issues/files/9172810/nwmain-crash-1658535910.log)
https://www.mediafire.com/file/x109tjc41j5zkax/nwmain-crash-1658535910.dmp/file (Dmp file)

**Specifics**

 - Windows
 - Preview .35
 - Steam
 - 100% but variable time frame (always within 3 minutes)
 - playing on SWOL but reproducible on other servers. nothing in overrides folder.

**Comment by stenly87** [comment]
May be the same issue
Client Preview .35
Server .34

[nwmain-crash-1659852153.zip](https://github.com/Beamdog/nwn-issues/files/9277810/nwmain-crash-1659852153.zip)

**Comment by Finaldeath** [comment]
@bentusi16 @stenly87 can you let us know if you've had this happen on the final 35 or preview 36.

**Comment by stenly87** [comment]
> @bentusi16 @stenly87 can you let us know if you've had this happen on the final 35 or preview 36.

Thank you, it seems to be gone

**Comment by Finaldeath** [comment]
Resolved in 36 or earlier.
