### ISSUE TITLE
Invalid number of skillpoints error with class granting inteligence bonus

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#467]
**To Reproduce**

 - Run module from #466 
 - Create a new character Bard, stats doesn't matter.
 - Once in game click on bones placeable to get XP to 40.
 - Start levelling as Bard. At level 4, take 8 Lore to qualify as Red Dragon Disciple. Start levelling Dragon disciple. Abililties nor feats doesn't matter. Do not spend skillpoints (yet).
 - At level14 levelup bard or something else doesn't matter till 20, then resume levelling RDD.
 - At total level 24 and RDD level 14 start spending skillpoints. It doesn't matter where, use recommended.
 - At total level 28 and RDD level 18 you will be unable to complete level up with this error.
 ![skill_points_bug](https://user-images.githubusercontent.com/5374108/184468315-2abbfefb-feb2-438d-bad9-206a8df715ce.jpg)

**Specifics**

 - OS: linux
 - Game build: .34

**If needed, describe the bug**

Originally discovered with custom prestige class granting total of +6 intelligence at level 25. To simulate it, I modified RDD class to provide +2 intelligence at level 14 and level 18.

**Comment by Finaldeath** [comment]
Should be fixed as per fixing https://github.com/Beamdog/nwn-issues/issues/245
