### ISSUE TITLE
[8193.12] Inventory Window missing BG Colors behind Icons

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#47]
**To Reproduce**

Open the Inventory of any creature.

**Specifics**

 - Game build [8193.12] 
 - Windows 10
 - Steam (assume All Distros)

**If needed, describe the bug**

Inventory Window missing BG Colors behind Icons

![oopsie](https://user-images.githubusercontent.com/58920224/81319768-22006c00-905e-11ea-8498-b1137fc144d8.jpg)

**Comment by virusman** [comment]
Should be fixed in 8193.13. Thank you for the report.
