### ISSUE TITLE
Tile Grass Planes have wrong vertex and fragment normals

### ISSUE THREAD

**Issue by merricksdad** [Beamdog/nwn-issues#470]
**To Reproduce**

Load any area with contoured tiles (raise/lower)
Rotate any placed tile with tilegrass
In debug mode view Vertex Normals and Fragment Normals to see incorrect normal values

**Specifics**

 - OS Windows
 - Game build preview
 - Distro platform Steam
 - Content override grass shaders removed
 - Regression uncertain. Only really noticed since preview build ad875e14 - 12 Aug 2022

**If needed, describe the bug**
Primarily affects rotated tiles and sloped ground. Vertex and Fragment normals are pointed the wrong direction, causing lighting issues on slopes and rotated tiles.

[Vertex Normals]
![image](https://user-images.githubusercontent.com/699980/187680809-99be0c3a-6ea0-4df3-94bd-4aed162deda9.png)
[Fragment Normals]
![image](https://user-images.githubusercontent.com/699980/187680848-2eebbdda-f25d-491f-b9d3-3a72299c3af4.png)

**Comment by Soren217** [comment]
Could you provide a concrete setup that I can just load up and check? The simpler the better, but can download cc if needed. Thanks
