### ISSUE TITLE
VFX with lights are delayed if total area lights exceed Lightning Max Lights

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#473]
**To Reproduce**

Run module attached.  Note that I placed 6 light vfx (Shaft of Light) off to the side of the tileset.
Run with max lights > 6.  Drink a potion of a standard character like Aluvian.  There is no delay in light vfx.
Run with max lights < 6.  Drink a potion of a standard character like Aluvian.  There is a 1.5s delay in light vfx applied.

See video attached.

Note: This module was "Reset to Black" for visual on the area.  Main Lights seem to count as lights in this issue.
Note: This happens regardless if the light is off-camera or not.

The main problem with this issue is that unless you run a module with "Reset to Black" lighting, this will always happen as Main Lights count as a source light, and the delay happens regardless of whether or  not the lights are on camera or not, so pretty much any tileset of any typical size will go past 32 lights and cause delay in vfx lights being applied.  

Is it possible that only lights in camera could affect Lighting Max Lights?

**Specifics**

 - OS (Windows, Mac, Linux) - Windows
 - Game build (e.g. 8193.8, or commit hash) - .34 & 35
 - Distro platform (BDC, Steam, GOG) - Steam & BDG
 - Content overrides? (Steam Workshop? Overrides? Patch haks?)  No
 - Regression? (Build which broke it, if known) No - probably at some point during lighting rework?

[module002.zip](https://github.com/Beamdog/nwn-issues/files/9568213/module002.zip)
[bandicam 2022-09-14 12-21-30-285.zip](https://github.com/Beamdog/nwn-issues/files/9568218/bandicam.2022-09-14.12-21-30-285.zip)

**Comment by Finaldeath** [comment]
This should be fixed in an upcoming .35 preview. At least the behaviour is changed and makes it much better.

**Comment by Finaldeath** [comment]
While not completely "fixed" the behaviour has been altered to better work with most VFX that use fadinglight 0 as the main parameter.

Things using fadinglight 1 will still need some MDL fixes to be perfect.

Light amounts also increased up to a massive-game-slowingly high of 128 as well.
