### ISSUE TITLE
Spell level requirements could be coded with custom content in mind.

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#476]
**If needed, describe the bug**

Not really a bug, rather missing feature - the functions FeatRequirementsMetAfterLevelUp and ValidateCharacters are checking spell level eligibility for **spontaneous casters** with function GetSpellsKnownPerLevel which only takes into consideration level of the base class.

This check could be using function uint16_t GetNumberKnownSpells(uint8_t nMultiClass, uint8_t nSpellLevel); which would then work with custom content such as my code to grant players extra known spells when levelling a prestige class like Pale Master.

I ask for this because while I can modify this on server side, NWN client will still check eliglibility this way and thus won't offer players at level up to select any feat with minimal spell level requirements, if the levels in base class itself aren't enough.

**Comment by tinygiant98** [comment]
This is a feature request and is out of scope for this repository.  Please file feature requests on the NWNX discord server.
