### ISSUE TITLE
EffectRunScript doesn't run apply event when applied as DURATION_TYPE_EQUIPPED

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#478]
**To Reproduce**

 - prepare the OnEffect script and print the events into log/to OBJECT_SELF
 - Apply the EffectRunScript as DURATION_TYPE_EQUIPPED (requires NWNX) for example:         using this line in OnEquip: `AssignCommand(oItem,ApplyEffectToObject(DURATION_TYPE_EQUIPPED,EffectRunScript("eff_test","eff_test"),oPC));`
 - observer log, it will print removal of the effect, but not application

**Specifics**

 - any OS, latest built, overrides irrelevant, not a regression - missing functionality

**If needed, describe the bug**

Note that remove effect runs.

It would also be nice if the EQUIPPED constant would be added to core game, I use this lot when creating custom itemproperties as with this constant, the effect:
- is not destroyed when player dies
- doesn't  show icon(s) in the effect list left from portrait, but in character sheet
- is automatically removed when item is unequipped

which makes things much more convenient.

**Comment by Finaldeath** [comment]
Closing this one.

This relates to parts of the engine intentionally not exposed to scripts. It sounds more like a NWNX request then anything.

The UnyieldingEffect function will provide a similar set of functionality for people not on NWNX.
