### ISSUE TITLE
Charactersheet displays wrong AB vs. <something> if there is an attack penalty present

### ISSUE THREAD

**Issue by Cjreek** [Beamdog/nwn-issues#480]
**To Reproduce**

 - Create a new level 1 human fighter character (press recommended for everything)
 - Equip a plain longsword: Attack bonus in the character sheet is displayed as +5 (1 BAB + 3 Strength mod + 1 Weapon Focus) --> correct
 - Equip a longsword with 
   Attack Bonus vs: Goblinoid +10
   Attack Penalty: -5
 - Character sheet reports attack bonus 0 (correct) and +15 vs. Goblinoids (wrong!)
 - Should be 5 - 5 + 10 = 10. 
 - Attacking a goblin shows the combat engine using the correct value of +10.

**Specifics**

 - OS: Windows 10 Pro 19044.2486
 - Game: 87.8193.35 [b52d238e]
 - Steam

**Screenshots**

Regular Longsword:
![image](https://user-images.githubusercontent.com/10603492/214876397-25e45342-c8f8-4e72-b3c8-07426a84b2ad.png)
-5/+10 Goblinoid Longsword:
![image](https://user-images.githubusercontent.com/10603492/214876712-a03a2ae9-0818-4d99-860a-9ea36460c033.png)
![image](https://user-images.githubusercontent.com/10603492/214876805-fa80f276-2f5a-46f6-8787-bed2c616a43d.png)

Combat Log hit against a non-goblinoid:
![image](https://user-images.githubusercontent.com/10603492/214877044-1a9f30ee-86d6-4635-8c37-ac1913b88286.png)
Combat Log hit against a goblin:
![image](https://user-images.githubusercontent.com/10603492/214877220-5fbd4f54-461e-464c-9b3a-25c7d30ed838.png)

**Comment by Finaldeath** [comment]
![image](https://user-images.githubusercontent.com/6137144/214967027-c71efad9-8b40-4d39-8e13-ce8f5081648d.png)

**Comment by tinygiant98** [comment]
@Finaldeath Does this just require review or is there additional with to be done on the PR?

**Comment by Finaldeath** [comment]
Just needs the review IMO, code cleanup can be another day.
