### ISSUE TITLE
Hard-coded restrictions in character names are needed

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#482]
**If needed, describe the bug**

Players on my PW are recently creating a lot of characters that the game then client is unable to show in character list.

AFAIK, there are two causes for that: 
1) mobile version of NWN-EE allows to input special characters like ENTER (line-break) into name or proceed with an empty name
2) some special characters that Brazilians use - server will create the character with these characters in the file name, then client is unable to show it "É" is one such character I believe (lowercase).

**Comment by tinygiant98** [comment]
(1) is for mobile development and outside the scope of this repository.
Will elevate (2) for decision on inclusion.
