### ISSUE TITLE
Wrong prices of items with charges

### ISSUE THREAD

**Issue by Taro94** [Beamdog/nwn-issues#483]
**Specifics**

 - OS: All
 - Game build: All recent ones
 - Content overrides: None
 - Regression: Broke in the patch that introduced an increased item charge limit

**If needed, describe the bug**

Items with charges, like wands, are 5 times cheaper than they used to be in 1.69 due to base price being calculated from the max number of charges, which used to be 50, but is now 250. A wand of missiles with 50 charges used to cost 1000 gold, but now only costs 200 in-game, because it is charged in only 20%. This makes wands and other chargable items in all modules very underpriced.

**Comment by Finaldeath** [comment]
Suggestion from Discord so it's not lost:

"Would a MAX_CHARGES_FOR_ITEM_COST=50 ruleset.2da be an acceptable fix there? Items wouldn't cost more if they had more charges. Modules that make heavy use of the new feature could up the value"
