### ISSUE TITLE
Crash with EffectRunScript

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#489]
**To Reproduce**

 - Load attached test module with any character [repromodule31.zip](https://github.com/Beamdog/nwn-issues/files/11271211/repromodule31.zip)
 - Take scroll of Storm Vengeance from the ground.
 - Cast it on yourself and move towards any of the Werewolf clusters.
 - Game might crash when one of them dies.

**Crash Dump**

[nwserver-crash-1681893321.log](https://github.com/Beamdog/nwn-issues/files/11271171/nwserver-crash-1681893321.log)

crashed also under windows client with above test module, it didn't create crash dump or I can't find it

**Specifics**

 - OS: Linux dedicated server, Windows client
 - Build: 8193.35-37
 - Repro Rate: 100% but sometimes it takes longer
 - Content overrides? None.

**Comment by tinygiant98** [comment]
Dmp file should be created (only on windows) in the same folder as the log file you posted.

**Comment by tinygiant98** [comment]
Toolset says the attached repro module requires a hak to run.  Can you reproduce the issue in a clean/minimal module that requries no external resources?

**Comment by tinygiant98** [comment]
I found an anomaly, but don't have a full explanation for exactly why it occurs yet.  For a quick workaround until we can get a real solution on this, try changing this line in `eff_windup.nss` (INTERVAL portion):
```
ApplyEffectToObject(DURATION_TYPE_INSTANT,eDam,OBJECT_SELF);
```
to
```
DelayCommand(0.0001, ApplyEffectToObject(DURATION_TYPE_INSTANT,eDam,OBJECT_SELF));
```
I was not able to reproduce the crash after adding the delay.  I'll carry this bug report for further investigation.
