### ISSUE TITLE
[8193.12] Area tile light color picker shows blank colors

### ISSUE THREAD

**Issue by Daztek** [Beamdog/nwn-issues#49]
**To Reproduce**

 - Open the the tile properties of an area tile.

**Specifics**

- Windows 10
- Game build: 8193.12
- Distro platform: Steam

**If needed, describe the bug**

![Image](https://i.imgur.com/JKmBJ5k.png)

**Comment by virusman** [comment]
Should be fixed in 8193.13. Thank you for the report.
