### ISSUE TITLE
.35-37 crash

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#491]
**To Reproduce**

No known reproduction steps, crash happened during long run when I was not in game and players are clueless as to what might cause it. But just maybe you can deduce something from the dump so I am posting it regardless.

**Crash Dump**

[nwserver-crash-1682468561.log](https://github.com/Beamdog/nwn-issues/files/11328860/nwserver-crash-1682468561.log)

**Specifics**

 - OS: Linux
 - Game build: .35-37
 - Distro platform: dedicated server
 - Repro Rate: first time it happened, unknown cause
 - Content overrides?: server crash not client hence overrides irrelevant
 
I am using nwnx, but from the log it doesn't really seems to be nwnx-related crash, I don't hook any of the mentioned functions and if it crashes due nwnx, the dump looks differently.

I am using the new damage types functionality and not all players have development version - if it can be somehow related. I don't use NPC bubble name override, nor any of the new NWScript functions.

EDIT: I forgot to add that I allow players to rename themselves using SetName.

**Comment by Finaldeath** [comment]
We could do with a reproduction without unknown NWNX addons to trace what this might be.

**Comment by Shad000w** [comment]
The crash happened three times already. Still no known reproduction. But we observed some additional issues, maybe it is related somehow - one user reported a random player appearing in his party list with no portrait and no HP bar see image:

![image](https://user-images.githubusercontent.com/5374108/236648880-0cdc3737-1693-45c1-9a10-1febc50bfb68.png)

It was harmless bug I suppose, it didn't cause crashing, but I think you were changing something with party list so maybe this can help.

Apart from that, the crash log is identical - same functions as in above crash log. It doesn't seem to be related to scripting, each time it happened the nwserverlog1.txt had different last script running, although once it was mod_gui script (which is my OnGui event script) - I am creating a GUI when opening journal. That however happens every while so if it was reason for crash it would be happening all the time which it isn't (and this was never issue prior 35 and the scripting didn't change).

**Comment by niv** [comment]
As Jasperre said, we'd need a report for the base game, without NWNX running out of tree plugins. In other words, please confirm this happens as well without NWNX and NWNX_Patch.so preloaded. Otherwise, this is unfortunately the wrong place to address this.

**Comment by Shad000w** [comment]
Found this reported at nwnx-unified github https://github.com/nwnxee/unified/issues/1484

Will you look into it now?

**Comment by Finaldeath** [comment]
NWNX related.
