### ISSUE TITLE
Memory Leak in NWScript : RandomName method

### ISSUE THREAD

**Issue by Baaleos** [Beamdog/nwn-issues#495]
**To Reproduce**

 - Each call to RandomName seems to be allocating memory, but that memory is never disposed of even if the name created by Random name is not used or set to null.
 - I have got an example module where I do 300 calls to RandomName spread out by DelayCommand - while it is doing these 300 calls - my nwmain.exe memory usage climbs from 342mb all the way to 497mb. I first noticed this on my PW server when my civilian NPC's were 'going home' at night, and then respawning in the morning, they were setting random names on themselves which then caused my server to run out of memory within 15 hours. One day/night cycle would consume roughly 8% of my 4gb allocated memory.

**Specifics**

 - Tested on Ubuntu server and windows NWMain via test module
 - 8193.35
 - Steam + Beamdog dedicated server binaries
 - Occurs on vanilla
 - I can't be sure if this is regression from .34 to .35 or not : I seem to recall my server 'lasted' longer on .34 - making me think this might have broke in .35

**If needed, describe the bug**

This script will illustrate the issue.
Attach this to an onUse placeable.
When RandomName is called - it seems to be allocating a load of memory - possibly loading in a 2da file on the fly, but the problem is that each call to RandomName allocates the memory again and the memory is never disposed off. If you are doing a single call to RandomName - this will not bother you so much, but if you want to make procedural npc's or procedural worlds - then RandomName might be something you go to in order to get large quantities of trash npc's.

This memory leak would impact anyone trying to do that.

I first noticed this on NWN.Anvil - in C#, but using the below NSS script, I confirmed that it affects the base game too.
I've attached a demo module that recreates the issue.

void RandomNameCall(int index)
{
    string name = RandomName(NAME_FIRST_GENERIC_MALE);
    string lastname = RandomName(NAME_LAST_HUMAN);
    if(index == 300){
        AssignCommand(OBJECT_SELF,SpeakString("Finished! Please check memory usage"));
    }
}
void main()
{
    AssignCommand(OBJECT_SELF,SpeakString("Beginning mem leak test"));
    float fMod = 0.20;
    int i = 1;
    for(i = 1; i<= 300; i++){
        DelayCommand((i*fMod), RandomNameCall(i));
    }
}
[MemLeakTest.zip](https://github.com/Beamdog/nwn-issues/files/11667007/MemLeakTest.zip)

**Comment by Baaleos** [comment]
I've performed the same test on .34 compiled script and client.
The memory usage remained stable and did not climb at all during the life of the test-  suggesting this is indeed a regression introduced in .35
.34 version of the same test is attached.

[MemLeakTest34.zip](https://github.com/Beamdog/nwn-issues/files/11667102/MemLeakTest34.zip)

**Comment by Finaldeath** [comment]
Confirmed, clippy might know the cause, I had a stab at it but couldn't find anything obvious so it's a bigger picture thing :)
