### ISSUE TITLE
Screenshot key in steam causing all graphics to unload until game is restarted

### ISSUE THREAD

**Issue by wilkins1952** [Beamdog/nwn-issues#496]
**To Reproduce**

-Run the game via steam
-Attempt to take a screenshot using the steam hotkey
-The game seems to enter an unplayable state where all graphics are unloaded and the only thing rendered is the players name above them with Tab and the main fog colour and effect

**Specifics**

 - OS Windows
 - Game build .36 steam Beta
 - Distro platform Steam
 - Content overrides? All Patches modules and HAKs in .36 beta
 - Regression? Worked in .35 and prior versions 

If warranted, add videos/screenshots to showcase the issue.

![image](https://github.com/Beamdog/nwn-issues/assets/114963955/6b800cf6-3c8d-4943-af18-b2cc3027c968) (Image after screenshot has been attempted to be taken)

![image](https://github.com/Beamdog/nwn-issues/assets/114963955/3af5f90a-f4ad-4e26-ba0b-949afa11e132) (Image before screenshot has been attempted to be taken

**Comment by Soren217** [comment]
This should be fixed by now (for a while), but please reopen if you still experience the issue.
