### ISSUE TITLE
Crash when changing area transition

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#498]
**To Reproduce**

There is no realiable repro still. We were able, with coordinated efffort of 8 players, to crash it within about 30 minutes of testing following:

- players entering and leaving instanced area where someone else already is and fights

Despite over 20 crashes, I couldn't gather anything more than this. I was not able to reproduce it alone with just 2 clients where one afked in area and one teleported in and out every 6 seconds.

**Crash Dump**

log from console: [mod-20230608164601.txt](https://github.com/Beamdog/nwn-issues/files/11692389/mod-20230608164601.txt)
crash-log: [nwserver-crash-1686252725.log](https://github.com/Beamdog/nwn-issues/files/11692409/nwserver-crash-1686252725.log)

**Specifics**

 - OS: Linux dedicated server ubuntu
 - Game build: 35.40
 - Distro platform: dedicated server binary
 - Repro Rate: N/A
 - Content overrides? Server crash so irrelevant. Lot of custom content, classes, spells, feats, itemproperties.

**Additional informations:**

Same issue I already reported and you automatically dismissed: https://github.com/Beamdog/nwn-issues/issues/491
Same issue as reported here: https://github.com/nwnxee/unified/issues/1664

NOT NWNX RELATED. The crash was **reproduced in vanilla nwserver without NWNX running**.

The player who most likely crashed it stayed in loading screen - here is screenshot of his screen when the server crashed:
![loading](https://github.com/Beamdog/nwn-issues/assets/5374108/071c8cda-fa61-4096-9bba-2223e7afcd8d)

I believe the area was already valid for him, the previous crashes with NWNX running indicates that area was valid and had an ID in all cases. The other player who crashed it several times specifies that sometimes it crashes after he loaded area and then he saw everything black but his own character. Sometimes mid-loading screen as above case.

**Comment by jjchudyk** [comment]
I was there during testing. Testing under vanilla as stated and crash occured anyways.

**Comment by Liarisd** [comment]
I have similar errors, the NWN server on Linux.
[nwserver-crash-1687642713.log](https://github.com/Beamdog/nwn-issues/files/12024443/nwserver-crash-1687642713.log)

**Comment by stenly87** [comment]
[test_mod.zip](https://github.com/Beamdog/nwn-issues/files/12027495/test_mod.zip)
Vanilla mod, no custom content
Server crash 100%
1) we enter the game with the first char, we approach the entrance to the location, we exit the menu
2) we enter the game with the second char, we approach the same entrance to the location, we exit the menu
3) we go in the first char, enter the location, exit the menu (CreateArea triggered)
4) we go in the second char, we enter the location, the server goes down
https://youtu.be/kbpGMXK-61I

**Comment by Daztek** [comment]
@stenly87 Thanks for the repro, will have a look

**Comment by Liarisd** [comment]
> @Liarisd @stenly87 I think I fixed it, if you guys use NWNX, can you try the newly added tweak: `NWNX_TWEAKS_FIX_AUTOMAP_CRASH` ?
working. Thanks

**Comment by Shad000w** [comment]
> @Liarisd @stenly87 I think I fixed it, if you guys use NWNX, can you try the newly added tweak: `NWNX_TWEAKS_FIX_AUTOMAP_CRASH` ?

This doesn't work.

**Comment by Daztek** [comment]
If you have a repro that crashes for you I can have another look.
