### ISSUE TITLE
`NWSyncAdvertLUT` entries are not loaded correctly from savegame files

### ISSUE THREAD

**Issue by blacktail-deer** [Beamdog/nwn-issues#499]
Hello!

Below is a strange bug upon which I stumbled recently, but which should hopefully have a very simple fix.

**To Reproduce**

Note: One can skip steps 1 through 4 and directly load the attached savegame file [`test1.zip`](https://github.com/Beamdog/nwn-issues/files/11733927/test1.zip) instead. It only requires the community modules “1 - The Hunt Begins” and “2 - Into the Unknown” of the “A Hunt Through The Dark” campaign from the curated content repository to be downloaded beforehand.

1. Set up an NWSync module repository with at least two modules (e.g., “Chapter 1” and “Chapter 2”), and set up its `repository.json` so that each module has a `localalias` field in its version entry. (See the attached [`repository.json`](https://github.com/Beamdog/nwn-issues/files/11733920/repository.json.txt) for an example, which was directly adapted from the one from the curated content repository by adding `localalias` fields to the first two chapters of the “A Hunt Through The Dark” campaign.)
2. Start Neverwinter Nights, add the module repository to its content sources, and download the modules advertised by this repository.
3. Start a new game of, e.g., the “Chapter 1” module, and save the game as “test1”. (Attached as [`test1.zip`](https://github.com/Beamdog/nwn-issues/files/11733927/test1.zip).)
4. Using the NWScript debug tool, check that the commands `StartNewModule("Chapter 1");` and `StartNewModule("Chapter 2");` both work as expected and start the corresponding module.
5. Load savegame “test1” and save it again as “test2”. (Attached as [`test2.zip`](https://github.com/Beamdog/nwn-issues/files/11733930/test2.zip).)
6. Using the NWScript debug window, try again the commands `StartNewModule("Chapter 1");` and `StartNewModule("Chapter 2");`: one of these should fail and do nothing (the log file will show, e.g., `Failed to start new module: Chapter 2`).

Using GFFEditor to have a look at the `Module.ifo` of the “test1” and “test2” savegames, one can see that:
- In “test1” (created after starting a new game), its `NWSyncAdvertLUT` list correctly contains references to all the modules with an advertised `localalias`.
- However, in “test2” (created after loading a savegame), its `NWSyncAdvertLUT` list only contains a reference to the first module; all the other `localalias` references were lost.

**Specifics**

 - OS: tested and verified on Linux, but should affect other OSes as well
 - Game build: 87.8193.35-40
 - Distro platform: GOG
 - Content overrides? none
 - Regression? unknown

**If needed, describe the bug**

After investigating this bug, it seems that the function `NWSync::AdvertLUT::LoadFromGff()` (which is called when loading a savegame) fails to correctly load all the entries of the `NWSyncAdvertLUT` list in the savegame: only the first one is loaded (and therefore saved in the subsequent savegames). From what I could gather, this is due to an index error in the current implementation of the `NWSync::AdvertLUT::LoadFromGff()` function.

Indeed, in order to load the `NWSyncAdvertLUT` structure, this function will iterate through all the items of this list and, for each such item, it will iterate through all the items of its `Entries` list. It seems to be implemented as a double loop in the code, something like:
```c++
for (int i = 0; i < NWSyncAdvertLUT.size(); i++)
    for (int j = 0; j < NWSyncAdvertLUT[i].Entries.size(); j++)
        register_local_alias(NWSyncAdvertLUT[i].LocalAlias, NWSyncAdvertLUT[i].Entries[j]);
```

However, in the current implementation, there seems to be a slight mix-up between the index variables, and the index used for the `NWSyncAdvertLUT` list is incorrectly used to index the `Entries` list as well. Something like:
```c++
for (int i = 0; i < NWSyncAdvertLUT.size(); i++)
    for (int j = 0; j < NWSyncAdvertLUT[i].Entries.size(); j++)
        register_local_alias(NWSyncAdvertLUT[i].LocalAlias, NWSyncAdvertLUT[i].Entries[i]);
```
(Note the `Entries[i]` on the last line, instead of `Entries[j]`.)

Directly patching the `nwmain` binary so that it would use the correct index here completely fixed the bug for me, so I guess fixing the implementation of `NWSync::AdvertLUT::LoadFromGff()` along these lines should also solve the issue. I hope this report will help!

In any case, thanks a lot for all the great work on this game! :)

**Comment by Daztek** [comment]
Hi! Thank you for your super detailed report, it was indeed an index var mixup in a double for loop, it will be fixed in a future update!
