### ISSUE TITLE
[8193.12] Creature Wizard - Errant Character at Start window?

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#50]
**To Reproduce**

Start the Creature Wizard

**Specifics**

 - Game build 8193.12

**If needed, describe the bug**

There is an errant character in the middle of the 1st window when you start the Creature Wizard. I circled it in red on the screenshot.

![WhatsThis](https://user-images.githubusercontent.com/58920224/81404739-35fea900-9104-11ea-826e-30e8cd0c50be.jpg)

**Comment by pstemarie** [comment]
As you move through the steps of the Creature Wizard there are other display issues with the "-1" character showing up as well as elements of the previous window underlaying the current window.

**Comment by virusman** [comment]
Should be fixed in 8193.13. Thank you for the report.
