### ISSUE TITLE
Quickbar slots disappearing after relogging while polymorphed

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#502]
**To Reproduce**

 - Use any module with any shifter character.
 - Put some of the equipped items into first 12 quickslots.
 - Polymorph into any shape.
 - Relog.
 - Observe that the quickbar slots which had equipped items inside them are now empty.

**Specifics**

 - OS: Any OS
 - Build: Any build
 - Distro: Any distro
 - Content overrides: none
 - Regression: vanilla issue

**If needed, describe the bug**

Looks like client-side issue where client checks if the character can use the items. Nevertheless it seems that the quickslots are not completely deleted. Canceling polymorph and another relog restores the quickbar slots. Still very annoying issue which was reported by the shifter players on my server.

Screenshots showcasing the issue:

Before relog:
![quickslots_prev](https://github.com/Beamdog/nwn-issues/assets/5374108/71418b30-6183-40a8-b4db-700c798be58d)

After:
![quickslots_after](https://github.com/Beamdog/nwn-issues/assets/5374108/6c8fbcfb-2758-4b5c-a8e2-77afa728b9a7)

Also notice the messages "You cannot use that item." in combat log. Might be related to the issue.

**Comment by Finaldeath** [comment]
Some polymorph fixes are in the works this has been already noted.
