### ISSUE TITLE
Weird negative numbers that equal a positive value

### ISSUE THREAD

**Issue by Prince-Raymond** [Beamdog/nwn-issues#509]
**To Reproduce**

 Create a character designed to maximize the threat range of your character's weapon. A Weapon Master with at least 7 levels in the prestige class, a base class with a full attack bonus progression of +1/level of experience, the Improved Critical feat, and a magical melee weapon with the Keen item property that is also the weapon master's "Weapon of Choice" would be ideal.

**Specifics**

 - OS: Windows
 - Game build: v87.8193.35-40
 - Distro platform BDC
 - Content overrides? None
 - Regression? (Build which broke it, if known) Patch 1.68 

**If needed, describe the bug**

As stated by [Haze] Wolf on Discord,

"Seeing these a lot more reported by players since .35+, I do not know if it was a problem before, but mainly it's things like the 18 - 4 = 22, clearly it subtracted, but shows a plus.

I see the same thing as a DM, when I attempt to disarm a trap as a DM, it is 20 - 127 = -107, and I fail to disarm the trap every time because of it, though that might be related to me having 99 in every stat, but most other rolls work fine, like recover trap properly does a + not a -."

My description: The Critical Attack/Threat Resolution behavior can be traced all the way back to Patch 1.68 released by BioWare on August 30th, 2006. It was the same patch that added the undocumented (bullshit) -5 progression to free attacks. Patch 1.67 did not have either of these issues. I know that for a fact, and that's all I will say about it. Do with this information what you will.
https://neverwintervault.org/project/nwn1/other/patch/167-official-critical-rebuild-english
https://neverwintervault.org/project/nwn1/other/patch/168-official-bioware-168-critical-rebuild

If warranted, add videos/screenshots to showcase the issue.

Here is a screenshot of the Critical Attack/Threat Resolution behavior with combat debugging enabled. It happened during a Cleave attempt with an unarmed strike. You can see it about 1/3 down from the top of the image. One thing that still bothers me is the attack roll modifiers are subtracted (more accurately a positive modifier added to a negative one), yet the threat roll modifiers are added together despite being displayed as part of a subtraction equation. It makes one wonder which process is correct. I hope this helps.
![image](https://github.com/Beamdog/nwn-issues/assets/70658358/fc573ab9-4610-4beb-9473-b91b40e0cd00)

**Comment by Finaldeath** [comment]
I think this is just a visual bug. A save game with a character this apparently is happening to would be useful to add.

Also please make shorter bug reports. This is summarised as "threat rolls don't display properly in the chat log" haha.

**Comment by Prince-Raymond** [comment]
My apologies for lengthy report. I was only trying to make it complete to avoid any confusion or loss of information. I will try to do a better job summarizing my reports from now on. I'll get on the save game right away.

**Comment by Prince-Raymond** [comment]
@Finaldeath

Okay. After some testing with my unarmed strike-focused build, I didn't see any conflicting critical attack/threat resolution results in the combat log. However, I did notice one resolution factored a negative attack bonus which subtracted from both the attack and threat rolls. Here is a screenshot of it.
![Unarmed Crit Test](https://github.com/Beamdog/nwn-issues/assets/70658358/cfd5ba42-01bf-456c-863b-a53b220bbdf3)

Should this be happening, sir? I've tried to upload a save game for you to test this yourself, but Github is telling the file is not supported. How do I upload a save game file here? Thank you for all you do.

**Comment by Finaldeath** [comment]
Put it in a zip file.

**Comment by Prince-Raymond** [comment]
Please forgive my lack of skill. How do I do that?

**Comment by Finaldeath** [comment]
Looking at your screen shots the threat roll given there should have -7 if the attack roll is -7. It just does another attack roll. See: https://nwn.fandom.com/wiki/Threat_roll

I am not sure I see any actual bugs here.

**Comment by Prince-Raymond** [comment]
Yes sir, but should the attack roll be a negative modifier in the first place? I mean, I saw my character's BAB reach -11 during a fight while I was testing. That seems a little extreme to me. Should a base attack bonus stop being a bonus? This testing I have done is the first time I have played NWN in 6 months. Please.

**Comment by Finaldeath** [comment]
You've managed to get into a situation where you have Entangle, Flurry of Blows active, and a variety of other negative effects potentially happening to you, so yes you could easily get -7 on an attack roll.

I don't know what else to say but I can't see any issues with this particular thing.

The original report had a different issue which I do want to trace which is the attack modifier is -4 but the final roll is higher;
![image](https://github.com/Beamdog/nwn-issues/assets/6137144/137e87d2-9091-4087-814e-5999af2b9040)

Although I am suspecting this is because the Called Shot feat removes 4 while a threat roll won't know its called shot and not remove the 4 penalty from using it. Which mainly means it's more a bug that it's not accurately removing the 4 from the threat roll making critical hits more likely when using feats.

**Comment by Prince-Raymond** [comment]
I understand, sir. Thank you for bringing the circumstantial penalties to light. It makes sense given that my build's unarmed attacks are all Dex based because he has Weapon Finesse. Any situation where he loses his Dex modifier hurts his BAB. You're right about Called Shot. It should subtract 4 from both the attack and threat rolls. Again, thank you.

**Comment by Prince-Raymond** [comment]
Thought I should try testing the latest dev build through the BDC just for the hells of it. I went through the slums of Blacklake District and fought my way through a swarm of enemies with combat debugging enabled. On more than one occasion, my level 10 character did an Attack of Opportunity with a -6 BAB alone. The -2 penalty from FoB was factored in separately. The attack that followed the second AoO was done at -11 BAB. Again, these were all factored into his attack rolls separately from the -2 penalty applied by FoB. I took a screenshot of the occurrence. Here it is.
![Attack Progression Test](https://github.com/Beamdog/nwn-issues/assets/70658358/609cdbb5-7e6e-4c06-be59-24ef9dca88b7)

From what I could tell, there were no circumstantial penalties that would have robbed my character of his positive BAB. The only constant through all of this has been the -5 free attack progression. It seems to bleed into normal unarmed attacks as well. I humbly request for ticket #155 to be re-opened, and this issue be investigated if/when you feel like tracing it. Please. I have attached a game save for you to test with. Thank you for all you do.
[000005 - BAB Test.zip](https://github.com/Beamdog/nwn-issues/files/13433202/000005.-.BAB.Test.zip)
