### ISSUE TITLE
[8193.12] Toolset Crashes after Editing UTI, UTC, etc. Then Switching Area Tabs

### ISSUE THREAD

**Issue by ghost** [Beamdog/nwn-issues#51]
**To Reproduce**

1. Load two areas in the toolset - this will open 2 area tabs.
2. Edit a placed or palette instance of a resource (UTP, UTC, UTI, etc.) in one of the areas.
3. Save the module.
4. Tab to the other area.
5. Tab back to the area where you made the resource edit. The toolset crashes.

**Specifics**

 - Game build 8193.12

**If needed, describe the bug**

Here is a screenshot showing the error message:

![TS_Crash](https://user-images.githubusercontent.com/58920224/81407056-b921fe00-9108-11ea-93de-9e0e22f5d7c1.jpg)

This issue may be related to issue #21 submitted by Shadguy.

EDIT - The crash also occurs if you edit a resource (placed or palette) and then close a tab by right-clicking on it and then clicking close. The error message is the same.

**Comment by virusman** [comment]
This appears to be specific to ATI hardware. I can't reproduce this.

**Comment by pstemarie** [comment]
I was afraid of that. Is it possible to still toggle this feature off? I can't find the option in the settings for the toolset.

**Comment by virusman** [comment]
`Disable Tabs=1` in the ini file.

**Comment by pstemarie** [comment]
Disabling tabs in the INI file seems to resolve the the issue.
