### ISSUE TITLE
VFX with lights are delayed 1.5s if total area lights exceed Lighting Max Lights setting

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#520]
This is a carry-over from Discord bug reports at: https://discord.com/channels/382306806866771978/1050095169267060767/1178013505597751316

The bug was fixed with a build Soren, who said "Think I figured out what's up! It's actually just a > that should have been a >=.  Please try this exe."  He compiled a build called "nwmain_fadefix" but doesn't seem to have ever made it to release, or something else broke it.  During 35 testing, I ran nwmain_fadefix for months and it was great, spell battles all had light effects that triggered right away, it looks very cool.  It never made it to prod.  Attached exe in zip.

I've included videos showing both builds (35 and FadingLight_Fix) running same time, same environment, to show the delta and rule out concerns of overrides etc.  Its more obvious if you use something other than fireball.  I also use a mdl of cure light wounds made a bit more color.  Fadinglight set to 0. See video attached.

**To Reproduce**

Set Lighting options To "Lighting Enhanced" in settings.

Run module attached. Note that I placed over 12 light vfx (Shaft of Light) off to the side of the tileset.
Run with max lights > 8. Drink a potion of a standard character like Aluvian or pull fireball lever. There is no delay in light vfx.
Run with max lights = 8. Drink a potion of a standard character like Aluvian or pull fireball lever. There is a 1.5s delay in light vfx applied.

If you test with fireball, make sure to pull the lever and just trigger the vfx.  If you cast a spell in DM mode, the test protocol is ruined because there are spell cast animations pre-triggering.

Note: This module was "Reset to Black" for visual on the area to display the issue.

Note: The bug is compounded because tileset Main Lights seem to count as as 2 lights in this issue,which means it will basically always happen on a standard tileset with the light limit set at 32.

Note: This happens regardless if the light is off-camera or not, so apparently lighting priority is dictated on the area basis, not what is visible on camera.

Note: If you run game settings to "Lighting Enhanced" off, even with Max Lights < 6, there is not bug.  So it is a bug with Enhanced Lighting on.

****
OS: Windows 10 and 11
Game build: .35-40 (stable) and .36-6 (preview)
Distro platform: Steam
Content overrides: None (only included for testing)
Regression: N/A

[lightdelay.zip](https://github.com/Beamdog/nwn-issues/files/13476619/lightdelay.zip)
[nwmain_fadefix.zip](https://github.com/Beamdog/nwn-issues/files/13476623/nwmain_fadefix.zip)
[bandicam_2023-11-24_21-34-13-230.zip](https://github.com/Beamdog/nwn-issues/files/13476625/bandicam_2023-11-24_21-34-13-230.zip)
[bandicam_2023-02-24_17-34-11-264.zip](https://github.com/Beamdog/nwn-issues/files/13476644/bandicam_2023-02-24_17-34-11-264.zip)
[vim_heal01.zip](https://github.com/Beamdog/nwn-issues/files/13476658/vim_heal01.zip)

**Comment by Soren217** [comment]
This should be fixed in the preview 27-3 version, sorry about the wait!
