### ISSUE TITLE
Color issues with Additive rendering going haywire/overflowing

### ISSUE THREAD

**Issue by GMXanther** [Beamdog/nwn-issues#527]
**To Reproduce**

 - Use the VFX Fog located in the standard visual effects palette. 
 - As the particles stack up, you will be able to see the unintended colors.

**Specifics**

 - OS : tested on Windows
 - Game build: v88.8193.36-6 [8827a044]
 - Distro platform: Steam
 - Content overrides: Not necessary
 - Regression: Yes, compared to .35 Stable

**If needed, describe the bug**

Just adding my confirmation of this issue and an easy way to recreate it with base game content. The colors will become totally warped and cause a bright yellow haze instead of the intended misty grey fog. This issue also affects other additive blending throughout the game, whether it's custom content or not, and it can make some areas look really bad where they didn't before. Some of my custom content turns blindingly flashy white as well, presumably for similar reasons as the color can also underflow now where it couldn't before.

**Comment by Finaldeath** [comment]
Can you add a very quick reproduction module and screenshot if you've got a good comparison between 35 and 36? That'll help a lot!

**Comment by GMXanther** [comment]
![additive vfx trouble](https://github.com/Beamdog/nwn-issues/assets/135566642/49d9ac1c-7265-43f0-a398-2eeea0b631b6)

[Test Mod for Additive Fog.zip](https://github.com/Beamdog/nwn-issues/files/13521347/Test.Mod.for.Additive.Fog.zip)

**Comment by Finaldeath** [comment]
@Soren217 since this is base game placeables/effects thoughts?
