### ISSUE TITLE
[Feature Request] Add Support for OpenGL 3.0

### ISSUE THREAD

**Issue by Felipefpl** [Beamdog/nwn-issues#535]
How is it possible that the support for opengl 3.0 was removed? I mean, think of the people with bad video cards that waited for a sale (because they are poor) to buy this game after a long time. And now its latest version doesnt work because opengl 3.3 is demanded. Please, add opengl 3.0 back for those with old video cards and keep the support for opengl 3.3 for those who can benefit from it.

**Comment by niv** [comment]
This tracker is not for Feature requests, as explained in the initial README. Even so:

The minimum requirements for the game are OpenGL 3.3, as published on the store pages. We will not maintain support for OpenGL versions older than the stated minimum.

Even though OpenGL 3.0 was never officially supported: If you need to run the game on older hardware, then Steam has older builds - some of which might work for your specific setup and hardware. You can find them in the dropdown menu under game properties; but you're on your own there, I'm afraid.
