### ISSUE TITLE
Game turns into a solid color when taking a screenshot through Steam

### ISSUE THREAD

**Issue by TobiasBergstrom** [Beamdog/nwn-issues#538]
**To Reproduce**

 - Launch the game through steam, load a module.
 - Take a screenshot (Press F12)

**Specifics**

 - Windows
 - Steam Development build
 - Steam
 - No content overrides

**If needed, describe the bug**

See screenshots.

![20231206180744_1](https://github.com/Beamdog/nwn-issues/assets/12394364/5c1643f1-3880-4b08-bfe9-b033d1b34f91)
![20231206180751_1](https://github.com/Beamdog/nwn-issues/assets/12394364/d00684b2-f318-48e8-8be0-bd1f0141752d)

**Comment by magna-phantasia** [comment]
Managed to replicate this easily via Steam launch.

**Comment by McKristoffer** [comment]
Yup, same problem on Linux. Newest development build (.36-9).

**Comment by Soren217** [comment]
This should be fixed now (and has been for a while), but please reopen if you still experience the issue.
