### ISSUE TITLE
Toolset opening times extremely long, now

### ISSUE THREAD

**Issue by RobertNelsonMSUDenver** [Beamdog/nwn-issues#54]
**To Reproduce**

 - Open a large mod.

**Specifics**

 - On the newest build using the "new" toolset, version 8193.13

**If needed, describe the bug**

When a mod is opened, it hangs at 0% a very long time, before starting to load!

**Comment by virusman** [comment]
Can’t reproduce.

**Comment by HowlandoEFU** [comment]
So everyone on the EFU development team was having this issue, but when I did some actual testing it appears that the actual loading time is pretty similar but the difference is that with the new toolset the "Loading Bar" doesn't move for about 1 minute 30 seconds. So it appears that it locked up at first, but actually isn't.

So it seems it is not actually a serious bug, the unmoving loading bar is just misleading.

**Comment by Clockwerkd** [comment]
I can confirm this is occurring with my module, as well. The total progress bar does not increment. Other progress bars still increment.

**Comment by virusman** [comment]
This should be fixed in 8193.14.
