### ISSUE TITLE
Long string constants cause invalid opcode error

### ISSUE THREAD

**Issue by ID99374836576228** [Beamdog/nwn-issues#540]
**To Reproduce**

 - Create a really long string constant (the production example caused this issue was 90Kb long)
 - Compile the script
 - Launch the nwnserver
 - See the "invalid opcode" in the log
 - The VM will also fail to execute anything in the script after the designated instance of the string constant

**Specifics**

 - OS: tested on nwnserver Linux
 - Sever build: 8193.36-7 [1187c0f8]
 - Distro platform: Steam
 - Content overrides: irrelevant, reproducible without any
 - Regression: suspected that [this PR](https://github.com/niv/neverwinter.nim/pull/68) caused it

**Description**

1. Example of building the string is:

`string data = "part0" +
        " part1" +
        " part2" /*+ <...>*/;`

2. The exact string length limit after which the bug occurs is unknown (untested)

**Comment by mtijanic** [comment]
The limit is 64kb, since the underlying NCS format uses 2 bytes for CONSTS length. The compiler should know this and not const-fold if it would go over the limit.

**Comment by ID99374836576228** [comment]
Not sure if related, however if I split the string in two equal segments (each becomes 45Kb size), I get a different error:

```Tag: , ERROR: IP OUT OF CODE SEGMENT```

the behavior after that is the same, i.e. none of the instructions following the faulty code invocation are executed.

**Comment by mtijanic** [comment]
Thanks. It interprets the string contents as binary ncs instructions, so any error is possible. The bug is understood and will be fixed as soon as I get a chance to test it out.

**Comment by mtijanic** [comment]
Will be fixed in next build. Also fixed in standalone compiler: https://github.com/niv/neverwinter.nim/pull/102
