### ISSUE TITLE
36-7 regression. AoE events scripts dont apply effect Spell ID. 

### ISSUE THREAD

**Issue by ud4ever** [Beamdog/nwn-issues#543]
**To Reproduce**

Effects applied in AoE events has spellId = -1. What's causing the effect applied in OnEnter script doesnt remove in OnExit script etc. It can be fixed using SetEffectSpellId. To reproduce cast any AoE spell with OnEnter/OnExit events. Default Grease for example. Slow effect will not be removed on exit from AoE and will stack infinitely.

**Specifics**

 - OS - Windows
 - Game build 8193.36-7
 - Distro platform (Steam)
 - Regression? Dont tested all 36-x builds, but 35.xx and earlier was ok.

**Comment by Liarisd** [comment]
I confirm the regression. I cast a Grease spell and the slowdown did not go away.
