### ISSUE TITLE
Client crash on bad door 2da refs - area fails to load

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#548]
**To Reproduce**

Reported/described by various folks in Discord: https://discord.com/channels/255017439371329537/467392331188928513/1182940177723838495

Some very knowledgeable folks commented, though it's a new issue to me.  Discord excerpts:

Maiyannah
 — 
Today at 1:01 AM
I have one very specific area that hangs on the load that I'm trying to figure out.  The area verifies okay.  Removing all the placeables doesn't fix the hang.  It's using a tileset and tiles from those tilesets that work in many other areas.  I'm at a loss at why it'd hang.  Any idea what it might be, or how to diagnose it?

sknymick
 — 
Today at 6:15 AM
I had this happen to players in 2 areas due to doors from CTP. 

Zwerkules
 — 
Today at 6:59 AM
It's most likely a door problem.
Tileset doors.
Maybe you have several tilesets and didn't merge the doortypes.2da. If a tileset references a door that isn't defined in doortypes.2da the area will not complete loading.

Matthew (Txpple)
 — 
Today at 7:23 AM
Does it have doors?  If the doorid in the set file doesn't match up with door types 2da properly and you try and load with that mismatched door, the area will do a hard lock freeze on load 
Oh haha yep what Z said

**Crash Dump**

- Not available as of yet

**Specifics**

 - Unknown

**Comment by Txpple** [comment]
This crash can be reproduced if you have a tileset .set file reference to a TileDoor with a line that doesnt exist in doortypes.2da.  

To reproduce:

1 - Edit TTR01 set file and change line 2542 ([TILE75DOOR0] from Type=1, a valid reference to line in doortypes.2da, to a nonexistant line.  Here I edited it to Type=7000, a line which does not exist in doortypes.2da.

2 - The toolset will not place a door if you place the relevant tile ("Features=>Wall 1 Gate w/Road"), but will still operate and not crash.  

3 - Run client.  NWN Client will freeze on area load, requiring a taskmgr end task.

Windows 11
Steam
Happens on Preview 36-6 and current stable 35-40

Use attached ttr01.set and module for quick repro.

[ttr01.zip](https://github.com/Beamdog/nwn-issues/files/13625799/ttr01.zip)

**Comment by shadguy** [comment]
Addressed by PR#3672.
