### ISSUE TITLE
NuiGetBind() returns unexpected json type

### ISSUE THREAD

**Issue by LaputianBird** [Beamdog/nwn-issues#554]
**To Reproduce**

 - Run the following chunk in the NWScript console and check the resulting message.

```C
#include "nw_inc_nui"

void main()
{
    object oPC = GetFirstPC();
    int nToken = NuiCreate(
        oPC,
        NuiWindow(
            NuiGroup(
                NuiLabel(
                    NuiBind("label_bind"),
                    JsonInt(NUI_HALIGN_CENTER),
                    JsonInt(NUI_VALIGN_MIDDLE)
                )
            ),
            JsonString("Test window"),
            NuiRect(-1.0f, -1.0f, 400.0f, 200.0f),
            JSON_FALSE,
            JSON_FALSE,
            JSON_TRUE,
            JSON_FALSE,
            JSON_TRUE
        ),
        "test_window"
    );

    SendMessageToPC(
        oPC,
        "Type of the json value returned by NuiGetBind() when the bind is unset:\n"
        + "    expected: 0 (JSON_TYPE_NULL)\n"
        + "    current: " + IntToString(
            JsonGetType(NuiGetBind(oPC, nToken, "label_bind"))
        )
    );
}
```
 

**Specifics**

 - Game build 8193.36-8

**Description**

By the function description, the expected returned value would be JSON_NULL. 
Returning an empty string instead creates the issue that the case of an un-initialized/unset bind and the case of a bind legitimately initialized to an empty string are not discriminated.

**Comment by tinygiant98** [comment]
Also occurs in .35.  Looks like the return value for a bind that doesn't exist is `""`, which is automatically translated by nholmann to json-type-string as an empty string.  Should be an easy fix, just needs some quick testing.
