### ISSUE TITLE
Toolset prompts to save new modules with an overwrite of latest open module 

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#57]
If you create a net new module and go to save after you work on it, it prompts to save over your most recently modified module, not the new module.  Inattentive users may inadvertently overwrite existing modules with new.  This is new after .13's changes in tracking most recent module.

**To Reproduce**

1 - Open an existing exit module in toolset, edit and save and exit.
2 - Open toolset.  Create new module.  Name it something.
3 - Do edits and save the new module.  It will prompt you to save the module, but will prepopulate the textbox/form with your latest existing module from step 1 above, and not the new name you provided in step 2. User is asked if it sure it wants to overwrite, but inattentive users may click through and overwrite the existing .mod.

- The old behavior in .12 was to prompt save with the name you specified when you created the module.

**Specifics**

8193.13
Windows 
BDC

**Comment by virusman** [comment]
Fixed sometime in June.
