### ISSUE TITLE
Error in classes.2da

### ISSUE THREAD

**Issue by BhaalM** [Beamdog/nwn-issues#570]
In the case of Shadowdancer prestige class (ID 27) , SpellcastingAbil is set to **** instead of DEX, affecting the DC of, for example, the "Shadow daze" class feat.

**Comment by Finaldeath** [comment]
I was looking at the code, it might be good to fallback Spellcasting Ability to the base Primary Ability (which itself does correctly go back to Strength as a default if not set, but all classes have it set). Then at least it'll deal with edge cases with feat-spells.

Would this be sensible? Then it means no random 2da data edits needed and fixes some potential bugs elsewhere people won't realise are happening. Can maybe log a error log entry when it's used too.
