### ISSUE TITLE
Feature: SpawnEncounter

### ISSUE THREAD

**Issue by julien-lecomte** [Beamdog/nwn-issues#572]
As discussed on discord, this a feature request for a function such as `SpawnEncounter(object oEncounter, int nCRLevel)`

I had looked into nwnx to create such a function, but it seems it's not possible.

Other alternatives to spawn the encounter are hacky: such as creating an invisible creature and having it move onto the encounter area.

**Comment by mtijanic** [comment]
From https://github.com/Beamdog/nwn-issues/blob/master/README.md :
> 2. **DO NOT REQUEST FEATURES HERE.** This is only for bugs in the game. **Feature requests will be closed without comment.**

(yes, I'm aware that adding this comment is violating that rule too)

I saw some related discussion on discord, so if someone said something like "file a feature request on github" they meant on NWNX: https://github.com/nwnxee/unified/issues
