### ISSUE TITLE
Hard freezes after consistent number of save loads on Linux

### ISSUE THREAD

**Issue by kotarf** [Beamdog/nwn-issues#579]
**To Reproduce**

 - Download the Hunt through the Dark Chapter 1 community module directly via the launcher.
 - Download and install the HD Models compiled hak from nwnvault.
 - Cycle through the 4 provided saves in sequence, ie load save 1 then 2 then 3 then 4 then 1...
 - Observe a hard freeze on the loading screen after the some number of save loads; the game client must receive the kill signal to exit.

**Specifics**

 - Linux CachyOS with kernel 6.7.5-2, Mesa 23.3.5-arch1.2
 - Preview 8193.37-1
 - Steam
 - HD models pack compiled
 - Regression in build 36 (latest release to date)

**If needed, describe the bug**
After repeatedly loading a save (or comparably by transitioning between areas), the game client will eventually hard freeze and require a kill signal. No populated crash log will be produced.

This is consistently reproducible and is not random; on my system exactly 15 save loads produce the freeze each time.

[saves_nwn_freeze_20240217.tar.gz](https://github.com/Beamdog/nwn-issues/files/14320523/saves_nwn_freeze_20240217.tar.gz)
![Screenshot_117](https://github.com/Beamdog/nwn-issues/assets/1068434/cc3c5a89-98b2-40da-988d-8d13ab9cb257)

**Comment by ReachPW** [comment]
Similar issue running on my laptop connected to a server.  Tried to run under gdb : 

36-11 (steam)

```bash
$ cat databuild.txt 
r1284
Sun Feb 11 06:56:37 MST 2024
```

```bash
$ cat bin/linux-x86/build.txt 
6fc1316d648cd54f158608ec26cfe0759e1e8418
Sun Feb 11 06:44:20 MST 2024
```


Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz
Linux gears2 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

```
00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)
	Subsystem: Lenovo 4th Gen Core Processor Integrated Graphics Controller
	Kernel driver in use: i915
	Kernel modules: i915
--
01:00.0 VGA compatible controller: NVIDIA Corporation GK107GLM [Quadro K1100M] (rev a1)
	Subsystem: Lenovo GK107GLM [Quadro K1100M]
	Kernel modules: nvidia
01:00.1 Audio device: NVIDIA Corporation GK107 HDMI Audio Controller (rev a1)
```

started with : `gdb -ex run --args ./nwmain-linux -userDirectory /home/jimmy/nwn/NeverwinterNights.3 +connect nwndev1:5146 +password xxxxxx`

It doesn't crash or generate a crash log or write to logs/ for some reason.

```
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff79aae8f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff795bfb2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7946472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007fffee49e18f in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#5  0x00007fffef4d85e2 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#6  0x00007fffeea2a49f in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#7  0x00007fffeea242fa in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#8  0x00007fffee4be243 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#9  0x00007fffee50bf97 in ?? () from /usr/lib/x86_64-linux-gnu/dri/crocus_dri.so
#10 0x00007ffff79a9134 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#11 0x00007ffff7a297dc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) generate-core-file
```

I also have core file generated, but github won't let me upload.
