### ISSUE TITLE
WASD-movement issues

### ISSUE THREAD

**Issue by NeverwinterMike** [Beamdog/nwn-issues#580]
**To Reproduce**

 - Use WASD on your keyboard to move around, intermittently movement will become choppy/laggy.

**Specifics**

 - OS (Windows)
 - Game build [88.8193.36-11]
 - Distro platform Steam
 - Content overrides? (Overrides? Patch haks?)
 - Regression? [88.8193.36-11]

**If needed, describe the bug**

We've had several reports from players on our server having issues using WASD to move on the new patch [88.8193.36-11]. Movement using WASD intermittently becomes choppy, as if you're experiencing lag, but you can move around just fine using mouse clicks.

If warranted, add videos/screenshots to showcase the issue.
https://www.youtube.com/watch?v=S0czkUIVZ_8

**Comment by Shad000w** [comment]
My players also reported this.

**Comment by mtijanic** [comment]
This is fixed (reverted) in 8193.36-12 which is currently the development build (can opt into it on the Betas tab on steam). Will come to stable soon enough.
