### ISSUE TITLE
SetObjectTextBubbleOverride - Inventory update not on DM client

### ISSUE THREAD

**Issue by LoveLessDev** [Beamdog/nwn-issues#583]
**To Reproduce**

 - Use DM Client
 - Use SetObjectTextBubbleOverride on an item
 - Pick it up and it's bubble override doesnt work
 - Same process works for player client

**Specifics**

 - Windows
 - 8193.36
 - Steam distribution

**If needed, describe the bug**

> SetObjectTextBubbleOverride() now works for items in inventories.

New feature that was added in 8193.36, appears to not update for the DM client users, but works just fine for players. It's not partial functionality, the feature does not appear to work at all for their inventories. Still operates correctly for objects in the area, this is limited to inside inventories.

**Comment by Daztek** [comment]
I can't seem to repro this?

**Comment by Daztek** [comment]
@LoveLessDev Is it working for you now? If not, can you attach a repro mod with the exact steps to take to reproduce it?

**Comment by LoveLessDev** [comment]
Erroneous report submitted on behalf of another.

Tested it myself today and it works fine. I'll reopen if I can get a repro for their issue.
