### ISSUE TITLE
Strength Spell not lasting 1hour/lv as it should

### ISSUE THREAD

**Issue by Imtherealthing** [Beamdog/nwn-issues#586]
**To Reproduce**

 - Try using the strength spell cast by wizard. See if it lasts as long as the 1 hour/level as it claims. The duration is much much shorter for some weird reason. I cast as a 10th Level Wizard and it lasted like 2 to 3 minutes. See if you get that same issue.

**Specifics**

 - OS (Windows 11)
 - Game build (current patch for NWN:EE)
 - Distro platform (GOG)
 - Content overrides? (Nope)
 - Regression? (Not sure

**If needed, describe the bug**

See above

**Comment by Daztek** [comment]
Please read the guidelines here: https://github.com/Beamdog/nwn-issues

4. **DO NOT REPORT SCRIPT, CAMPAIGN, OR PREMIUM MODULE BUGS HERE**. We only deal with the engine and engine data files here. **Reports for script or module issues will be closed without comment.**

**Comment by Imtherealthing** [comment]
Sorry...I thought the Strength spell was the original spell from the NWN:EE. I don't understand why you got so mad using caps. I genuinely think this spell issue was/is. This is my third time using this bug report thing.

**Comment by mtijanic** [comment]
> Sorry...I thought the Strength spell was the original spell from the NWN:EE. I don't understand why you got so mad using caps. I genuinely think this spell issue was/is. This is my third time using this bug report thing.

Daz didn't get mad, they just quoted from the front page of this tracker, which you should read in full: https://github.com/Beamdog/nwn-issues

Specifically, "Script bugs" refers to things like spells, feats, and similar. These are outside of the scope of the game patches and are better suited for one of the many community mod projects which rebalance the game.
