### ISSUE TITLE
Metamagic Level 7 and 8 spells not showing up on radial with specific caster type

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#589]
**To Reproduce**

- Create or modify a caster class in classes.2da. Set MemorizedSpells and SpellbookRestricted to 0 (made possible with the latest patch). Other columns can be whatever.
- Create a character with that class, get Extend Spell or another metamagic feat.
- Level the character up to 20.
- Access the Extend Spell radial menu, extended level 7 and 8 spells will not show up in the metamagic list. However, they show up in the spellbook and can be quickslotted.

**Specifics**

 - OS (Windows)
 - Game build (e.g. 8193.36.11)
 - Distro platform (Steam)
 - Content overrides? (Haks, but is a UI issue)
 - Regression? (No, bug with new feature)

Level 7 and 8 spells don't show up in the metamagic radials even if the character is high enough level to cast them for casters that don't memorize spells and aren't spellbook restricted. They do show up in the spellbook and can be cast when slid from the spellbook to the radial menu but not from the radial.

![image](https://github.com/Beamdog/nwn-issues/assets/51026560/657b5e3e-59be-42f8-855e-10fd59fd30fd)

**Comment by Finaldeath** [comment]
If you've got a save game + appropriate 2da file(s) to easily reproduce this it'll help a lot.

**Comment by FrogsOfDoom** [comment]
> If you've got a save game + appropriate 2da file(s) to easily reproduce this it'll help a lot.

Here's a saved module. No hak, just an overriden classes.2da where I changed SpellbookRestricted from 1 to 0 for the sorcerer class.
[Bug report - Metamagic.zip](https://github.com/Beamdog/nwn-issues/files/14454884/Bug.report.-.Metamagic.zip)

Let me know if more info's needed to repro it.

**Comment by Finaldeath** [comment]
Thanks for the repo save I've tracked down the issue much appreciated.

**Comment by Finaldeath** [comment]
Fixed in preview. If you can test that'd be good.
