### ISSUE TITLE
Toolset not storing .bic files  (makes it very difficult to force module to use a specific character, which is a new feature)

### ISSUE THREAD

**Issue by Paphjort** [Beamdog/nwn-issues#595]
**To Reproduce**

  - Load any module
 -  open temp0 directory in nwn/modules
 - copy any .bic character from /localvault to /temp0
 - save module. 

-close module and open module again. 
- .bic is now gone from temp0. 

**Specifics**

 - toolset : vts80 
 -  game: 88.8193.36-12

**If needed, describe the bug**

While trying to force my module to use a specific character (a feature introduced in .35 I believe) I found out that I could not make .bic file stay in the .mod (while using temp0 directory). When saving the mod in toolset, it would not save the .bic inside.

Temporary workaround: While building a mod, put the .bic in development/override and for module release put .bic inside the mod using nwhak.exe or similar (but the .bic could maybe get deleted once again if the mod is open again in toolset.)

Clippy suggested it was a toolset problem with toolset not persisting .bic files and asked me to report it. 

/Paphjort

**Comment by Finaldeath** [comment]
Will be in 37.
