### ISSUE TITLE
Since -36.12 the toolset script editor crashes very very often (CTD)

### ISSUE THREAD

**Issue by julien-lecomte** [Beamdog/nwn-issues#596]
**To Reproduce**

Basically anything can make the toolset crash now. Opening a file, searching for a string, etc. 

The toolset script editor was all I needed and did it's job fine for my use. With the multiple CTDs every 10 minutes, it has basically become useless.

**Specifics**

Use through Wine, via Steam Proton: Added toolset binary to Steam as individual app, then checked the box for it to start with proton.

**Comment by Finaldeath** [comment]
I cannot reproduce on Windows and WINE/Proton is unsupported so this is being closed. It's hard enough tracing toolset bugs on native Windows, tracing anything on an unknown module on an unknown version (you did not follow the submission template) and on an unsupported platform is not going to happen.

I'd strongly suggest if your module is large using VSCode to edit your scripts by setting it as the external editor in the toolset options.

**Comment by julien-lecomte** [comment]
Sorry for the lack of following guidelines. I see you've closed this as not planned, and that's OK, but I'll still give more context, and what I believe is happening.

**To Reproduce**

Simple actions, more often in the script editor, can make the toolset crash to desktop. I've encountered this trying to open script files, closing them, or editing a placeable. Yes, it's totally random, and I have found no way to reproduce.

I can provide the module and haks if needed, and if we can believe it's tied to the module.

**Specifics**

 - Happened on 8193.36-12 and preview 8193.37-2.
 - Running with Steam + Proton.

**If needed, describe the bug**

What I believe: before we used to get an error message (nullpointer derefence if I recall) with only one option to continue. We just had to click a couple of times and could continue to work as if nothing happened. Could it be possible that we no longer have this message and now have a real CTD instead?

I'm unaware of a special debug mode or of logs for the toolset, but I would activate them if possible.

I don't mind too much if this stays unresolved, I can still use the toolset throughout the randomness of crashes. I totally understand this setup is unsupported and not worth the effort.

**Comment by Finaldeath** [comment]
I already said Proton or WINE is entirely unsupported. The toolset sometimes barely works on Windows. 

We might be more willing to look at this if it was on Windows and easily reproduceable. You have alternatives though: run Windows or use the external script editor option.
