### ISSUE TITLE
Access Violation when opening a specific Area in a module after updating to 0.36

### ISSUE THREAD

**Issue by FinalHeaven** [Beamdog/nwn-issues#598]
**To Reproduce**

 - Load attached module
 - Open North of the Reach - Stormhaven - Riverport Area (made with Medieval City 2 tileset)
 - Toolset crashes after 5-10 seconds

**Specifics**

 - Game build 88.8139.36
 

**If needed, describe the bug**

Exactly as described in the Reproduce section.  The module is only 4 Areas, running cep 2.70, and the only custom hak contains only armor models from the nwvault.

The module has not been launched for just over a month, pre 0.36, but did work then.

The file tfa01.res was removed from cep2_add_tiles3.hak the last time the module was opened when I learned it caused issues with NWSync.  However, reverting this change does not stop the issue.

The area functions fine in-game, the game does not crash.
[Echoes of War 0_1_12.zip](https://github.com/Beamdog/nwn-issues/files/14455298/Echoes.of.War.0_1_12.zip)

**Comment by virusman** [comment]
@FinalHeaven What's the custom hak with armor models? This module cannot be used for repro without all haks present.

**Comment by FinalHeaven** [comment]
@virusman My apologies I thought I had combined it with the zip in the first post.  Here is the link: https://drive.google.com/file/d/1_tWchmekFaEveO7ngqXlyYfuegmkrn2n/view?usp=sharing

**Comment by Finaldeath** [comment]
Got a similar thing I think repeatable using Dungeons and my textures/shader. Not sure what it is. 

![image](https://github.com/Beamdog/nwn-issues/assets/6137144/9e366548-a43d-4b65-84d3-31cd969bca37)

File with override and module: https://www.dropbox.com/scl/fi/4hs61166d1sw5p6m07ixp/37-dungeon-crashing.zip?rlkey=3frfwvgu5ho3k29lmysi0wuoe&dl=0

All the module is, is a blank Dungeon area 32x32, I place some ground then the "Features" top to bottom it seems to consistently crash.

Might actually be related to animations, or some other thing. There are 3 models included in the override folder which are merely compiled versions of the ASCII MDL files included in the game files.

**Comment by Finaldeath** [comment]
Also @FinalHeaven I've reproduced this crash as you say 5 - 10 seconds. Tested on the latest preview version of the toolset.

![image](https://github.com/Beamdog/nwn-issues/assets/6137144/4db4ee79-181d-435f-a312-1f96594a22bf)


It might be I could create a dungeon area in the same way but my one contains more custom content.

I'll test the area import.

**Comment by Finaldeath** [comment]
[37 Test Med City Toolset Crash.zip](https://github.com/Beamdog/nwn-issues/files/14466538/37.Test.Med.City.Toolset.Crash.zip)

Reproduced just with the ERF. @virusman here is a simple version of that area imported into a otherwise blank module. It crashing after that consistent amount of time is odd. There are some animated things (smockstacks) but otherwise all base game content in my tests. No hakpack content involved.

**Comment by FinalHeaven** [comment]
@Finaldeath Yep, that is the exact Access Violation I get, right down to the same numbers.  I have not had a chance to test it on .35 yet as I'm out of town until tomorrow.

I'm not sure it's relevant but the only other thing I'd say is that all of the areas except one in that module use the same Medieval City 2 tileset, but only the one listed causes the error.

**Comment by virusman** [comment]
@Finaldeath I can't repro this crash on my Mac with this module, running either on Wine or Parallels.

**Comment by Finaldeath** [comment]
How odd. If anything I'd thought those would crash even more.

A frustrating thing to investigate for sure. I wonder if you made a debug build would that log anything worthwhile or have at least some symbol names or something? Currently the error message just repeats and no there's no "real crash" or dump.

**Comment by virusman** [comment]
FWIW I'm running the latest preview, 37-2, maybe it's already fixed? I see the original report is for 36.

**Comment by Finaldeath** [comment]
I think I ran it through 37 but I'll try later and see if anyone else can test 37 too

**Comment by Finaldeath** [comment]
Yeah ran it on 37-2 same crashes.

**Comment by virusman** [comment]
Then it's probably related to hardware, which GPU and OS are you using?

**Comment by Finaldeath** [comment]
Same as previous; Intel i9, 3080 GTX, Windows 11.

**Comment by FinalHeaven** [comment]
I'll throw mine in here as well: 

Intel i7-13700k
RTX 4070
Windows 11

I did actually have an NVIDIA driver update that I installed the day I had this issue, though it also was crashing before I did that.  I couldn't tell you have many driver updated I've had since the last time I updated the module but the card itself hasn't changed from the last time the module worked.

**Comment by FinalHeaven** [comment]
One of the people that devs with me has tried to open the area on both .35 and .36 and they do not get the error.

They're on a much older NVIDIA card, a GTX 1060.
