### ISSUE TITLE
[8193.14 Preview] TNO Palette Missing Text + Ref to Custom TLK

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#60]
**Description**

Looks like the TNO Palette has a missing line and is referencing a custom TLK - probably the TLK used for Tyrants.

![Uh-Oh](https://user-images.githubusercontent.com/58920224/82663022-e7b9d180-9bfc-11ea-9c83-890562583f3b.jpg)

**Specifics**

 - Game build = 8193.14 Preview
 - OS = Windows 10
 - Distro platform = Steam
 - No overrides

**Comment by Bill-Harper** [comment]
This one should have been fixed in the last preview build.
