### ISSUE TITLE
[8193.14 Preview] Tile Selector Malfunctioning 

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#61]
**To Reproduce**

  - Load any area in the toolset.
  - Go into "Tile Selector" mode, the tile selector either ghosts or is replaced by a paint brush, or doesn't appear at all 

**Specifics**

 - Game build - 8193.14 Preview

![TileSelector](https://user-images.githubusercontent.com/58920224/82738253-56ce1d80-9d04-11ea-8f44-a508ff964f80.jpg)

**Comment by pstemarie** [comment]
Hopefully this isn't an AMD issue.

**Comment by virusman** [comment]
Does this only happen in .14 preview?

**Comment by pstemarie** [comment]
Yes, it was working fine in .13 Stable. It has also now extended into the highlighting of anything that is selected and the selector is invisible. All that shows is a paintbrush now. The tilebox was appearing sometimes, but not anymore.

**Comment by shadguy** [comment]
The usual "red tile grid" lines also seem to be missing from the toolset when doing tile work.  They're helpful when building layouts.  Do you think that may be related, or should I file separately?  I'm looking at the crypt tileset (standard BW).

-Dave

**Comment by pstemarie** [comment]
Just discovered by accident that if you toggle shadows on/off the selectors for eveything come back along with the tile grid.
