### ISSUE TITLE
[37-2] : dismissing a summons does not display unsummon graphic

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#610]
**To Reproduce**

- Create a base module from scratch, create an area.
- Load up Aluvian Darkstar
- On enter, use summon creature and summon a badger.
- Right click radial on the badger and dismiss it.
- No unsummon graphics appears

Expected behavior: summon graphics appears

**Specifics**

 - OS Windows
 - Game build: preview 37-2
 - Steam
 - No
 - Regression? Yes.  37-2.

**Comment by Finaldeath** [comment]
Thanks, found the issue.

**Comment by Txpple** [comment]
Tested and fixed in 37-3.
