### ISSUE TITLE
[37-2] vPos uniform is providing world vert values, not object vert values

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#611]
It seems that in 37-2 vPos is pushing world vertex values to the vertex shader, and per documentation and all prior versions, it should be providing object vertex data.   Something broke here.

See attached shaders and mdl file.  The mdl file is a square that has the top two verts at a height of 1 and the bottoms at a height of zero, giving a range of 0 at bottom of the object to 1 at top for the verts.  The shaders for the repro take vPos.Z in the vs and push the z value to the fs to color the square as a gradiant from black to white (0,0,0 to 1,1,1).  If it goes over 1, it will color it red.

**To Reproduce**
 - Load vPos_Repro in 36-12.  
 - Note the gradiants on the squares are as should be black to white per the vs and fs data taking the object vert locations.
 - Load vPos_Repro in 37-2
 - Note the gradiants on the squares the passed vertex height value is now using world position vert locations, and anything with a vert above 1.0 is set to red indicating it went out of range.

**Specifics**

 - OS Windows
 - Game build 37-2
 - Steam
 - Content overrides? Yes to show the bug.
 - Regression? Yes in 37-2.
 
[vPosbug.zip](https://github.com/Beamdog/nwn-issues/files/14653321/vPosbug.zip)

<img width="1063" alt="36-12 vPosObjectHeight" src="https://github.com/Beamdog/nwn-issues/assets/62627607/922e12d7-d4f2-43d3-b5d6-4444611efce3">
<img width="1145" alt="37-2 vPosWorldHeight" src="https://github.com/Beamdog/nwn-issues/assets/62627607/c92c4b0f-6d18-4214-9c5a-7687d3cf3441">

**Comment by Soren217** [comment]
As discussed bilaterally, this is a delibarate change, but we will be exposing new uniforms that will allow you to overcome any issues the change may have imposed.

**Comment by Soren217** [comment]
As discussed bilaterally, the new bounding box uniforms should allow overcoming the issue caused by this change.
