### ISSUE TITLE
NWN crash

### ISSUE THREAD

**Issue by Tigrero87** [Beamdog/nwn-issues#623]
**To Reproduce**

 - When launch the game from Steam, the game crashes. After the crash appears a window that says to go on this site and open an issue. So in the attachment i put the dmp file and log file.
 

**Crash Dump**

- Windows: Attach the generated .log AND .dmp
[nwmain-crash-1714320620.dmp](https://github.com/Beamdog/nwn-issues/files/15142783/nwmain-crash-1714320620.dmp)
[nwmain-crash-1714320620.log](https://github.com/Beamdog/nwn-issues/files/15142784/nwmain-crash-1714320620.log)

**Specifics**

 - OS Windows 11
 - Game build r1284 - Mon Feb 26 09:14:59 MST 2024
- Distro platform Steam

**Comment by Finaldeath** [comment]
This appears to be trying to use the built-in Windows drivers for a generic GPU, not a proper GPU;

```
GL_RENDERER = 'GDI Generic'
GL_VENDOR = 'Microsoft Corporation'
```

This is being closed since the main issue here is probably you need to update your drivers.
