### ISSUE TITLE
Saving Throws Universal and Will on same item doesn't stack.

### ISSUE THREAD

**Issue by Shad000w** [Beamdog/nwn-issues#625]
**To Reproduce**

[repromodule39.zip](https://github.com/Beamdog/nwn-issues/files/15224422/repromodule39.zip)
with yours matching the same pattern.
 - Enter attached module with any character.
 - Open chest and grab cloak with bonus +6 to universal saves and will saves (second tab).
 - Equip the cloak.
 - Observe character sheet cloak grants only +6 to all saves, you can also click on level it makes a will save throw to verify it is not just character sheet issue.

Expected: cloak should grant +12 to will and +6 to fort and reflex.

**Specifics**

 - OS: any
 - Game build: any
 - Distro platform: irrelevant
 - Content overrides? irrelevant
 - Regression? no, vanilla nwn issue

**If needed, describe the bug**

It seems that the two different saving throws bonus properties have a stacking limit as if it was the very same property with same subtype like two strength bonuses on same item. But I don't think it makes sense in this case. These are obviously two different subtypes.

I didn't test with other subtypes like vs mind-affecting and reflex/fort, but I suspect it will not stack either.

Screenshot showing the issue:
![savebug](https://github.com/Beamdog/nwn-issues/assets/5374108/417a90bc-c784-4aa5-a917-f87b8821f505)

**Comment by Finaldeath** [comment]
This is intentional and thus not a bug. Like AC or attack bonuses versus a specific race, it just checks all the properties and gets the highest applicable one.
