### ISSUE TITLE
Game crashes before startup

### ISSUE THREAD

**Issue by swab148** [Beamdog/nwn-issues#640]
### OS

Windows

### Game version

36-13

### Describe the crash

Literally just click the big green PLAY button on Steam; it doesn't work at all. This is from a brand new Windows 11 install.

### Custom content or overrides used

Game crashes as soon as I press the play button on Steam. I get a blank white window where the game should launch, and an error message in front of it, and that's all. No custom content, just the stock Neverwinter Nights: Enhanced Edition from Steam.
[nwmain-crash-1719001565.dmp](https://github.com/user-attachments/files/15933565/nwmain-crash-1719001565.dmp)
[nwmain-crash-1719001565.log](https://github.com/user-attachments/files/15933567/nwmain-crash-1719001565.log)
[nwmain-crash-1719002212.dmp](https://github.com/user-attachments/files/15933568/nwmain-crash-1719002212.dmp)
[nwmain-crash-1719002212.log](https://github.com/user-attachments/files/15933569/nwmain-crash-1719002212.log)

**Comment by Daztek** [comment]
Did you install/update your graphics drivers? The log file says it's using Window's default driver which it uses when it has no other choice.

**Comment by swab148** [comment]
Didn't even think about that, I'm usually a Linux user so the drivers are just in the kernel lol. Thanks!
