### ISSUE TITLE
NuiFindWindow does not clear on reloading a save game.

### ISSUE THREAD

**Issue by Philos-Harak** [Beamdog/nwn-issues#647]
### Describe the bug

When using NuiFindWindow to get a windows ID it will persist through a reload while still in the game.

To reproduce:
Run the module NUI Issue.mod. When you load into the game a button will appear in the center of the screen after 6 seconds. 
Save the game and then reload the game. Since the window ID persists the button will never reappear in the center of the screen. 

[NUI Issue.zip](https://github.com/user-attachments/files/16490138/NUI.Issue.zip)

### Custom content or overrides used

No custom content.

### Game version

37-5

### First seen on game version

37-5 but I'd imagine this is on all versions.

### OS

Windows

### Distribution

Steam

**Comment by Kamiryn123** [comment]
Reported it last year: https://discord.com/channels/382306806866771978/1103311690273136711
