### ISSUE TITLE
[37-6 preview] toolset crash - loading area placeables

### ISSUE THREAD

**Issue by Txpple** [Beamdog/nwn-issues#648]
**To Reproduce**

- Open attached/linked repro.mod.  Be sure to place repro.hak in your hak folder.
- Be on stable v36 to confirm it works on stable.  Zoom out of the area view to view whole area.  No crashes.
- Update to preview 37-6.  Open module again.  Zoom out when viewing area.  Crashes every time with memory address errors.

**Specifics**

 - Game build (37-6)
 - Regression? Yes. Preview.

**If needed, describe the bug**

Basically as above.  I recognize that I use custom content and probably push the toolset to its 32bit limits, but it works fine on stable, and crashes every time on preview.  So something has to be different/not working in preview.  Thanks everyone.

Mod file
[REPRO.zip](https://github.com/user-attachments/files/16568842/REPRO.zip)

Hak link (larger than 25mb)
https://drive.google.com/file/d/1S2aan3XUXToX8Mc4dqf0R7-xkAVP2N6u/view?usp=sharing

**Comment by shadguy** [comment]
I'm getting access violations/memory errors on stable v36 with both beamdog/steam launchers (shouldn't matter).  I'm running on a pretty decent Winbox these days, only a couple years old.  I'm not sure what to tell you on this.  I dig the foliage /shader stuff though when I load up and walk around looking for anything notable.  :)

**Comment by Txpple** [comment]
Hmm ok.  Weird "it works on my PC" for 36.  I'll rustle up a few others to see if it's the same.  Thanks for taking a look and I'll see if there is anything I can narrow down other than probably "it's too much". Thanks again!

**Comment by Txpple** [comment]
Tried it on 2 other windows 11 machines, clean installs, works on 36 but not 37.  Not sure what else to report.  Thanks and I'll keep looking if there's something else I can find.

**Comment by Daztek** [comment]
Also crashes for me on both 36 and 37

**Comment by Txpple** [comment]
Ok thanks.  If I shrink resize the area a bit, no crash on either for me, so I'm gonna chalk it to cthulu and close this...that is guys
