### ISSUE TITLE
Music changing functions don't work

### ISSUE THREAD

**Issue by Taro94** [Beamdog/nwn-issues#650]
### Describe the bug

[ddrepro.mod.zip](https://github.com/user-attachments/files/16648922/ddrepro.mod.zip)
1. Start the module.
2. Go to the right corridor, you will enter a trigger firing up a script that calls MusicBackgroundStop. The music will not stop on the current preview (37-6), but will stop on development (36-13).
3. Go to the left corridor, you will enter a trigger firing up a script that calls MusicBackgroundStop and MusicBattlePlay. The music will not change on the current preview, but will change on development.
4. Go back to the starting position and to the wall, you will enter a trigger firing up a script that calls MusicBattlePlay and MusicBackgroundStop. The music will not change on the current preview, but will change on development.

### Custom content or overrides used

None

### Game version

37-6

### First seen on game version

37-6, bug not present on 36-13

### OS

Linux

### Distribution

Steam

**Comment by Daztek** [comment]
Known issue, fixed next build

**Comment by Daztek** [comment]
Fixed in 8193.37-7
