### ISSUE TITLE
.37 regression: area Fog weird artifacts

### ISSUE THREAD

**Issue by alfa050moonshaes** [Beamdog/nwn-issues#655]
### Describe the bug

In .37, area fog looks very strange, with visual artifacts - shadowy outlines of object meshes that are in the fog. See attached screenshot. In .36 the bug is not present.
![v37 bug screenshot](https://github.com/user-attachments/assets/5464f0c3-7c56-4039-8992-e6e3758e4833)

Update: note that it seems difficult to create a reliable repro for this. Not sure why. It looks to me like different fog colours/fog settings, different times of the day, may cause it sometimes not to show up or to only show up within a limited range of distances from the camera. Am trying to produce a reliable repro.

### Game version

.37

### First seen on game version

.37

### OS

Windows

### Distribution

Steam

**Comment by Txpple** [comment]
From posts in discord: https://discord.com/channels/382306806866771978/995637334919893082/1279934769320431729

yea I've seen this too, still kinda trying to figure out the repro.  i'm pretty sure it is SSAO ; back when it was originally put in it did this too, i vaguely recall symphony reported it, and then there was a fix to work out the fog depth problem which you can see the fix put in the SSAO shader file.

The files below show the repro with SSAO on, and then off on 37.  You don't get the AO punching thru fog in .36.
![Screenshot 2024-09-01 183807](https://github.com/user-attachments/assets/e4964ade-4a4b-4e20-8088-64496570d788)
![Screenshot 2024-09-01 183653](https://github.com/user-attachments/assets/d71c8e49-2275-4a74-9ca8-305edf65456d)

If you see it again, try turning AO on and off (like here fixes it).  What is really weird though is that I can make it work in multiplayer running local server over wsl, but if i load the game single player it seems fine.  Still trying to play with repros.

Note: El Grillo confirms he sees the same, where the issue happens in multiplayer running on a server, but not single player.
