### ISSUE TITLE
Potential .37 regression: Skybox shaders using moduleTimeIntoTransition do not seem to get the correct value from the variable

### ISSUE THREAD

**Issue by SpacePontif** [Beamdog/nwn-issues#657]
### Describe the bug

In .37, using custom skybox shaders with `moduleTimeIntoTransition` do not update correctly with the time of day. 

36-13 client logging onto 37-7 server: skybox correctly turns to day during daytime, and back to night at night.

37-7 client logging onto 37-7 server: skybox is eternally nightime.

See [1280242331156615189](https://discord.com/channels/382306806866771978/995637334919893082/1280241026753233018) on Discord for more details

### Custom content or overrides used

Two custom shader files: fst_sky_moon.shd and inc_clouds.shd

[skyshaders.zip](https://github.com/user-attachments/files/16840790/skyshaders.zip)

### Game version

37-7

### First seen on game version

37-7

### OS

Windows

### Distribution

Steam

**Comment by Finaldeath** [comment]
Should be fixed now @SpacePontif can you check?

**Comment by SpacePontif** [comment]
Seems fixed on 37-8!

**Comment by Finaldeath** [comment]
Great thanks, just this one was missed being closed.
