### ISSUE TITLE
AOE Targeting Issue

### ISSUE THREAD

**Issue by TomRotfl** [Beamdog/nwn-issues#66]
**To Reproduce**

- Have a caster moving around in an area casting spells against moving enemies
- On some spots (seems to be random AND related to some tilesets), AOE spells wont find a target to hit, even if it's right in front of you or stands in the middle of the AOE effect

**Specifics**

- OS - Client: Windows - Server: Linux Ubuntu 18.04 using Docker
- Game build: 8193.13 (i know about this issue since EE, never seen it on 1.69 old nwn)
- Steam
- No Haks, no custom spell scripts or 2da

Have a caster moving around in one area trying to cast AOE spells at enemies. Some AOE spells won't be able to find a target when casted on specific spots, even if targets are right in the middle or even if you have directly targeted an enemy. 
It seems to happen more frequently while the target is on small tilesets like pre-build bridges and similar, but it happens on almost any other tileset as well as far as i could see.
It seems to never happen on chessboard tileset, i couldn't reproduce it there.
Seems related to TARGET locations only, regardless of caster location.
Also works for players standing in a "bad" location, NPCs won't be able to cast AOE spells at them.

I attach a video with subtitles, i hope it is clear enough.

Video [HERE](https://mega.nz/file/qBR2ACoJ#qRNriMMzCbSeBSLRGdissfs8sv4CWRyT1AomHPRy3iY)

**Comment by TomRotfl** [comment]
I can confirm the bug is still a thing on 8193.20, any chance someone can give a look at this? @niv 

It is very frustrating for players playing a caster class. 

I initially thought it was happening only on areas imported from a .erf file, but i found out it also happens on other areas from my PW that have always been there. If it can help, i noticed it happens a LOT more in areas that i create "live" with CreateArea when i instance a specific group of areas (i.e., for dungeons), or perhaps it is just a coincidence and players notice it a lot more while into an instanced dungeon since they really need those spells to fire properly to survive. 

Or it can only be related to some specific tilesets, or even deeper in the engine. I really can't say. But this is definitely a thing.

I can help with further debugging at any time if needed. I can give info or other examples as well.
For what i can say, there is no reason for me to believe this is caused by something in my PW only. It might be related to Multiplayer only though, since i haven't heard of any report from Single Player games. Maybe network related.

**Comment by Finaldeath** [comment]
Would be worth having a test area with a simple lever to have an NPC cast a spell from a set spot to a set location that fails - I strongly suspect this is to do with line of sight checks and some weird geometry checks, which @Soren217 would tend to be the one looking at I think. I personally haven't seen this happen in my limited testing but could expect it would, Line of Sight in this game is weeeirrddd (1M above the ground exactly, to objects locations but 1M above the ground).

Fixes? Not much, LOS code is necessary to stop things going around corners or through doors...

**Comment by TomRotfl** [comment]
This was solved in a recent release, don't remember which one though
