### ISSUE TITLE
Just tried to open the game

### ISSUE THREAD

**Issue by negris** [Beamdog/nwn-issues#663]
### OS

Windows

### Game version

14061032

### Describe the crash

Just tried to open the game... via steam.

![image](https://github.com/user-attachments/assets/375748ca-e350-4c8b-8c76-8f1a376d9257)

[nwmain-crash-1725540264.dmp](https://github.com/user-attachments/files/16893735/nwmain-crash-1725540264.dmp)
[nwmain-crash-1725540264.log](https://github.com/user-attachments/files/16893736/nwmain-crash-1725540264.log)

**Comment by Finaldeath** [comment]
It looks like the games data is not loading correctly (the main bif files). Can you try revalidating the files in steam, and disabling any AV if you have it enabled.

**Comment by negris** [comment]
> ng

I'll try and then return here for feedback...

**Comment by negris** [comment]
IT'S ALIVE!!!!   TNKS!!!!! @Finaldeath
