### ISSUE TITLE
.36 & .37 regression; glowing visual artifacts in some situations (NVidia users only)

### ISSUE THREAD

**Issue by alfa050moonshaes** [Beamdog/nwn-issues#669]
### Describe the bug

These visual artifacts were introduced in .36 and remain in latest .37 build. The issue presents in the same way as a similar previously-fixed regression - details of that regression in this discord thread: https://discord.com/channels/382306806866771978/1163835555239436429/1163835555239436429
That previous regression was fixed in build ## [88.8193.36-5] - 2023-11-20.

Both that previous regression, and this current bug, only present for users with NVidia GPU's; AMD gpu users are unaffected.

The current regression presents on certain meshes including meshes packaged with the base game - screenshot here of tile tcn01_t14_01 by way of example: 
![imagedsfhs](https://github.com/user-attachments/assets/37e0ae83-6477-48d8-a922-8c5f0e0772dd)

It can be reproduced (only on a machine with an NVidia gpu) by using Soren's city override textures & MDLs, available here: https://neverwintervault.org/project/nwnee/images/texture/nwnee-advanced-texture-maps-showcase
Here is a module to test the Soren's override pack with. Look at the end edge of the sloped tile roof of the 2x1 house tile group to see the artifact. Repro module:  [testmodgraphicsbug.zip](https://github.com/user-attachments/files/17213129/testmodgraphicsbug.zip)

The bug seems to only affect MDLs that were compiled in previous versions of the game - see e.g. if you use Soren's city override textures, without also using the MDLs he packed with the textures, then the artifact doesn't appear on the current base game versions of those models.
The bug also may depend somehow on texture size/compression; I have observed it occurring on some of TXpple's older statue placeables where textures were original 2k, and I had downscaled them to 1k. See this discord thread with Txpple, myself and Jasperre for more info: https://discord.com/channels/382306806866771978/1279940389154979893/1279947346519789598 

Note that I have tested fairly extensively and have found that the bug does not present in version .35. It was introduced in .36 it seems.

### Custom content or overrides used

Soren's city override (see description text above)

### Game version

.37-11, .36

### First seen on game version

.36[unknown which sub version]

### OS

Windows

### Distribution

Steam

**Comment by Soren217** [comment]
Been digging into this and it is essentially due to an issue with the old EE model compiler that were causing errors. Any idea how widespread of an issue this is? We can add in some exception in the shaders but it'll be bandaid.

**Comment by alfa050moonshaes** [comment]
> Been digging into this and it is essentially due to an issue with the old EE model compiler that were causing errors. Any idea how widespread of an issue this is? We can add in some exception in the shaders but it'll be bandaid.

Thanks so much.
Re: how widespread it is, am not certain but I don't think it's likely to be widespread. In addition to the example given in the OP above (two of the base game tile meshes in tcn01), we have also experienced it quite severely on a bunch of Txpple's placeables that are about 1.5 to 2yrs old. But, we have NOT seen much more of it on the rest of the tcn01 tile models, for example (and, I have PBR'd basically all of that tileset so I think we would have seen it). 
Obviously it only seems to apply where PBR textures are used, so to that extent also I think it should be relatively limited in scope. 
By way of another example, the NWIC placeables DON'T seem to be affected, even though they are PBR'd and they must have been compiled ages ago. So, more evidence for it being hopefully limited.
Hopefully that means a band-aid type fix would be more than sufficient?

**Comment by Soren217** [comment]
The bandaid solution would work, but I'm less fond of it because it entails doing some extra processing of all vertex data in the game for the sake of just these models. 

There ideal here would be to re-compile these models (or not have them compiled at all), which would be preferable for other reasons too (the compiler has improved a lot). But I'm unsure if it's feasible to get around whatever other content with issues there is available out there.

**Comment by Dafena** [comment]
> The bandaid solution would work, but I'm less fond of it because it entails doing some extra processing of all vertex data in the game for the sake of just these models.
> 
> There ideal here would be to re-compile these models (or not have them compiled at all), which would be preferable for other reasons too (the compiler has improved a lot). But I'm unsure if it's feasible to get around whatever other content with issues there is available out there.

Taking into consideration the amount of content that has been compiled with the old one, the sources probably not existing anymore and the lack of knowledge of how to decompile files, I'd say the bandaid should be done even if there's some performance loss.

**Comment by alfa050moonshaes** [comment]
> > The bandaid solution would work, but I'm less fond of it because it entails doing some extra processing of all vertex data in the game for the sake of just these models.
> > There ideal here would be to re-compile these models (or not have them compiled at all), which would be preferable for other reasons too (the compiler has improved a lot). But I'm unsure if it's feasible to get around whatever other content with issues there is available out there.
> 
> Taking into consideration the amount of content that has been compiled with the old one, the sources probably not existing anymore and the lack of knowledge of how to decompile files, I'd say the bandaid should be done even if there's some performance loss.

Have you seen the issue on any other old content, OOI? I haven't really done much testing so I really have no idea how widespread it could be TBH, except that of all our PBR'd tileset stuff the only examples of the issue that I've seen thus far have been the ones in the example mod in the OP.

**Comment by Dafena** [comment]
> > > The bandaid solution would work, but I'm less fond of it because it entails doing some extra processing of all vertex data in the game for the sake of just these models.
> > > There ideal here would be to re-compile these models (or not have them compiled at all), which would be preferable for other reasons too (the compiler has improved a lot). But I'm unsure if it's feasible to get around whatever other content with issues there is available out there.
> > 
> > 
> > Taking into consideration the amount of content that has been compiled with the old one, the sources probably not existing anymore and the lack of knowledge of how to decompile files, I'd say the bandaid should be done even if there's some performance loss.
> 
> Have you seen the issue on any other old content, OOI? I haven't really done much testing so I really have no idea how widespread it could be TBH, except that of all our PBR'd tileset stuff the only examples of the issue that I've seen thus far have been the ones in the example mod in the OP.

Yes, if you try to fancymap any of the old CEP or other content, it can break, and even if it isn't fancymapped, the HDR+Bloom can break them. It's a hit or miss situation and with the amount of content out there it's impossible to pin it down.

**Comment by alfa050moonshaes** [comment]
Wonder if the band-aid could check compile date of MDL first (is that even data the compiled MDLs contain??) and only apply the corrections where you got both an old compile date + an MTR calling PBR textures... to try to lighten the load?

**Comment by Finaldeath** [comment]
Uncompiled and compiled MDLs don't really have any data on the version of compiler used (or date, or whatever).

**Comment by Soren217** [comment]
@Dafena are you positive that this still happens in the most recent preiew with the content you mentioned? The issue discussed here exclusively affects a select number of models that were compiled with the EE compiler and prior to version ~35

So if you experience issues with other things, that's something I need to investigate. But some issues were already solved so please check with the latest version first. Thanks!
