### ISSUE TITLE
[8193.14] Placeable "Boat, TNO 1" Crashing Toolset

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#67]
**To Reproduce**

 - Open a module in the toolset. 
 - Open the properties of any placeable.
 - Select "Boat, TNO 1" from the appearance drop down.
 - Model is selected then Toolset freezes, forcing you to CTRL+ALT+DELETE to close it.

**Specifics**

 - Game build 8193.14
 - Win 10
 - Steam

**If needed, describe the bug**

![Image1](https://user-images.githubusercontent.com/58920224/82820072-82b9e200-9e6f-11ea-99de-1499ac4b11f1.jpg)

**Comment by pstemarie** [comment]
This might actually be a model issue.

**Comment by pstemarie** [comment]
I fixed the model by compiling it with the ingame compiler. It no longer crashes the toolset.

[dag_tno_boat1.zip](https://github.com/Beamdog/nwn-issues/files/4677612/dag_tno_boat1.zip)

**Comment by Bill-Harper** [comment]
Thanks for the fixed file, but I ended up repairing this as part of #71 (had same issues, on this and other tiles). As a side note, I've noticed weird issues on this set between compiling and decompiling them. Sometimes just compiling or decompiling can make a difference between working and not working (i.e. in either direction). I suspect animmesh as the culprit, but I can't 100% confirm it.

**Comment by Bill-Harper** [comment]
(_Fixed in a Previous Build_) Thanks for reporting, let us know if you have any future issues!
