### ISSUE TITLE
NuiGetNthBind(): bWatched parameter is ignored

### ISSUE THREAD

**Issue by Kamiryn123** [Beamdog/nwn-issues#685]
### Describe the bug

The third parameter bWatched of NuiGetNthBind() is ignored. NuiGetNthBind() will always return all binds.

For example use the following code to get all the watched binds of the specified nui window:

```
object oPC = ...
int nToken = ...
string sBind;
int nNth=-1;
while ( (sBind=NuiGetNthBind(oPC, nToken, TRUE, ++nNth)) !="") SendMessageToPC(oPC, sBind);
```

According to its description the code should print only the watched binds but it prints all binds. Changing the parameter to FALSE does not change anything.

### Game version

36-13

### OS

Windows

### Distribution

Steam

**Comment by tinygiant98** [comment]
Planned for .38.
