### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by finp** [Beamdog/nwn-issues#687]
### OS

Windows

### Game version

NWN:EE 

### Describe the crash

Crashes during start up.
[nwmain-crash-1731629897.dmp](https://github.com/user-attachments/files/17759861/nwmain-crash-1731629897.dmp)
[nwmain-crash-1731629897.log](https://github.com/user-attachments/files/17759867/nwmain-crash-1731629897.log)

**Comment by tinygiant98** [comment]
This isn't much info, but the game crashed when trying to compile a shader.  Have you done any shader work recently, or are you only using stock shaders?  If you have custom shaders, check their validity.

**Comment by finp** [comment]
Only stock.

**Comment by tinygiant98** [comment]
Ok, is this very consistent, or just a one-off?  Also, which exact version are you running?

**Comment by Daztek** [comment]
What is your graphics card? Your pc is using a default graphics driver which means you have a very old gpu that isn't supported or you forgot to update your drivers after a reformat. If it's the latter try updating your graphics driver

**Comment by finp** [comment]
Solved.  It was a failed graphics driver.

**Comment by Daztek** [comment]
Good to hear! Closing
