### ISSUE TITLE
Cannot load any saved game

### ISSUE THREAD

**Issue by vladu2131** [Beamdog/nwn-issues#691]
### OS

Windows

### Game version

1.88

### Describe the crash

[nwmain-crash-1732657519.dmp](https://github.com/user-attachments/files/17926238/nwmain-crash-1732657519.dmp)
[nwmain-crash-1732657519.log](https://github.com/user-attachments/files/17926239/nwmain-crash-1732657519.log)

### Custom content or overrides used

This happens on all saved games. As soon as I try to load a game I cannot even select a game to load, it just crashes. Sometimes it keeps trying to open up the game over and over and I have to use the task manager to kill the process.

**Comment by Finaldeath** [comment]
Can you provide an example save game and note what hakpacks it'll need.

**Comment by vladu2131** [comment]
This happens on Crimson Tides of Tethyr and Eye of the Beholder, both community modules. Not sure where to find the haks that those use.

[Uploading Crimson.zip…]()

**Comment by vladu2131** [comment]
Actually, so I never get to the screen where I select a module but those two are the latest modules that I have run.

[Eye of the Beholder.zip](https://github.com/user-attachments/files/17926395/Eye.of.the.Beholder.zip)

Here are the zipped files for eye of beholder.

**Comment by Finaldeath** [comment]
If you're on steam can you try the latest beta? I can't seem to reproduce the crash on that version.

Also can you remove any files in your `\My Documents\Neverwinter Nights\override` folder (rename the folder)

**Comment by vladu2131** [comment]
Is that the "Latest Development Build"? How do I update to that and for the other players will they have to do that as well if that gets it working?

**Comment by Finaldeath** [comment]
See here: [https://developer.valvesoftware.com/wiki/Betas](https://developer.valvesoftware.com/wiki/Betas#For_the_Beta_version_of_the_game)

It should be other people can still join your multiplayer game if you're hosting.

**Comment by vladu2131** [comment]
Loading the development version fixed the problem!

**Comment by Finaldeath** [comment]
From the log it looks like a rare crash loading player stats that was fixed.

**Comment by vladu2131** [comment]
Thanks for the fast response!
