### ISSUE TITLE
assets get erroneously evicted after module reload

### ISSUE THREAD

**Issue by niv** [Beamdog/nwn-issues#7]
**Repro**

* Run Aielund saga savegame with companions.
* Save, load.
* Companion portraits should disappear.

**Repro**

* Make new Arelith character
* Choose wizard and select custom Arelith Spells (Chromatic Orb)
* Enter game, Exit Game, Re-Enter game
* View custom spell icon in quickbar/spellbook.

Regression introduced in Beamdog/nwn@4ee78e6

**Comment by DMSymphony** [comment]
Symptom of beamdog/nwn#1935
