### ISSUE TITLE
[8193.14 preview] Medieval Rural 2 trm02.set feedback - trm02.set -SQRT DOMAIN errors

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#72]
**To Reproduce**

 - Load or Create an area in the toolset using Medieval Rural 2 tileset
 - Click on Tile Groups -> Water -> Docked Boat (1x2)
 - *or* Click on Tile Features -> Water -> Boat 2
 - Toolset produces "sqrt: DOMAIN error

**Specifics**

 - Game build 8193.14 - May 29th release
 - Windows 10)
 - Steam
 - Content overrides? (None)

**If needed, describe the bug**

Two tile palette options produce a SQRT domain error when clicked.

![nwnee_preview_module003_medieval_rural2_boat2_sqrt_error](https://user-images.githubusercontent.com/38797333/83343221-f5d2b680-a2bc-11ea-9a4b-60dc88f32cf5.JPG)
![nwnee_preview_module003_medieval_rural2_docked_boat_sqrt_error](https://user-images.githubusercontent.com/38797333/83343222-f66b4d00-a2bc-11ea-9d25-de4b27b342d6.JPG)

**Comment by pstemarie** [comment]
Its caused by bad compiling on the models. They need to be decompiled and then recompiled with the in-game compiler. The placeable mode dag_tno_boat1 has the same issue.

**Comment by Bill-Harper** [comment]
I went back to the SVN source files and the error wasn't there. Re-compiling them did not make it return.

**Comment by Bill-Harper** [comment]
I also fixed the placeable boat from source, re-compiled it (successfully), and created a standard blueprint for it.
