### ISSUE TITLE
[8193.14 preview] Medieval Rural 2 / trm02.set has no loadscreens by default

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#73]
**To Reproduce**

 - Load or create an area using the Medieval Rural 2 Tileset
 - Edit Area Properties -> Advanced ->Loading Screen
 - There are no options.

Builders who don't catch this, leave it on Random, and don't assign a loadscreen from another tileset will likely greet players with a random loadscreen from a random tileset. 

Side Note: A number of your DoD campaign-specific loadscreens are not associated with any tileset.    Likely intentional.

**Specifics**

 - Game build 8193.14 - May 29th release
 - Windows 10)
 - Steam
 - Content overrides? (None)

**If needed, describe the bug**

Medieval Rural 2 has no loadscreens available.  Please add some.

**Comment by Bill-Harper** [comment]
This is something that I will have to get with Zwerkules on. Naturally I could make some, but it's his work and I wouldn't want to make creative decisions for him without his input.

**Comment by Bill-Harper** [comment]
The DoD loadscreens were intentionally that way, assigned per-area in the mod (same w/ Tyrants loadscreens), and were only included as a bonus/easter egg. That said, the majority of Daggerford is using TNO01 exteriors but I'm not sure we'd want to flood that set with all of them?

**Comment by shadguy** [comment]
Sounds great, thank you!

**Comment by shadguy** [comment]
I vaguely recall someone else raising this in Discord at some point.  Anyway, in 8193.17, there are now two loadscreens available to choose from.  

Issue closed.

-Dave
