### ISSUE TITLE
[8193.14 preview] Sea Ships - Rural - minimap inconsistency

### ISSUE THREAD

**Issue by shadguy** [Beamdog/nwn-issues#74]
**Description**

Minimaps are inconsistent for the Rural terrain in the Sea Ships tileset.

**To Reproduce**

 - Make or Edit an Area using the new Sea Ships tileset.  
 - Use the Rural Terrain. (City/Castle/Tropical seem okay!)
 - Places some boats etc 
 - Load the game in DMClient, check out your minimap.

**Specifics**

 - Game build 8193.14 - May 29th release
 - Windows 10)
 - Steam
 - Content overrides? (None)

**Description**

The water color looks pretty brown, except where there's boats.  Then it looks blue.  Might be fixable with a single minimap texture update.  Screenshot attached.

![nwnee_preview_module003_Rural_minimap_issue](https://user-images.githubusercontent.com/38797333/83343860-9d53e700-a2c5-11ea-8a45-134c505aca0e.JPG)

**Comment by Bill-Harper** [comment]
![water3_new](https://user-images.githubusercontent.com/53191846/83882935-c8e53000-a710-11ea-911c-f84284d92814.png)

It's not perfect, but better and hopefully close enough? I was able to just fix the blank water icon; to make it better I'd have to redo every icon in the set with a formal render on all---not the NWMax tool shortcut.

**Comment by shadguy** [comment]
Better is better.  :)   It looks like your minimap is overtop a boatl the lower right section, over water, looks much improved!
