### ISSUE TITLE
[8193.14 preview] Forest Tileset - Side Log 1 - SQRT: domain error

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#76]
Getting a SQRT: domain error when adding a Side Log 1 (Feature) in the Forest tileset in the toolset. Using vanilla NwN, no haks, overrides, workshops, new module with one area.

**Comment by FrogsOfDoom** [comment]
FYI: This issue is still present in the latest preview version.

**Comment by Bill-Harper** [comment]
I managed to track these down at last; it was bushes on two tiles throwing the error (they supersized when Reset X-Form was applied).
