### ISSUE TITLE
[8193.14 preview] - Tile texture issues (Forest tileset)

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#77]
The following Road tile's color isn't the same as the regular Forest forest floor:

![image](https://user-images.githubusercontent.com/51026560/83952158-cfed6a80-a804-11ea-8e1e-87bf6f745731.png)

Trees generated around the Pit tiles are white rather than green, they look like the Early Winter Tileset trees:

![image](https://user-images.githubusercontent.com/51026560/83952167-e398d100-a804-11ea-9c4c-020d6ff381ab.png)

**Comment by Bill-Harper** [comment]
Thanks for the reports! I was able to track down the tree issue, and I gave the old (ttf01_treefol02) texture a cleanup and resize to 512x512 while at it. But I haven't found the road tile yet. Could I please ask you for tile name? If you have it open in the toolset, just highlight the tile and the name will appear in the bottom left corner.

**Comment by FrogsOfDoom** [comment]
Discolored road tile is: ttf01_g05_04

Also, tile: ttf01_g01_01 generates a white spot on the minimap in-game; haven't tested yet other road parts, I just generated it to test the previous tile:
![image](https://user-images.githubusercontent.com/51026560/84215055-27086f00-aa93-11ea-9540-078364dcfee6.png)

And not sure if the changes you made to trees made it in this preview version but they're still showing up as white in-game, at least on tile tttf01_c01_02.
![image](https://user-images.githubusercontent.com/51026560/84215085-3d162f80-aa93-11ea-9739-a364c37a16d9.png)

**Comment by Bill-Harper** [comment]
Thanks for the tile names! I'll get them fixed up. And sorry, I had no idea there was another build coming so soon. If we do another this weekend, the fixes will be there.

**Comment by FrogsOfDoom** [comment]
FYI: Both issues still occur in the latest version of the development patch.

**Comment by Bill-Harper** [comment]
I think this should take care of them all? Plus new dirt texture on the Road End tile (ttf01_floor03), which allows for the more blended look you see on the overlay dirt.

![ttf01_c01_02_treefix](https://user-images.githubusercontent.com/53191846/88090285-59f65600-cb5b-11ea-8e33-8d91f0c3b8d3.png)

![ttf01_g04_05_dirtfix](https://user-images.githubusercontent.com/53191846/88090295-5e227380-cb5b-11ea-8492-4cd10a49a437.png)

![ttf01_g01_01_minimap](https://user-images.githubusercontent.com/53191846/88090303-624e9100-cb5b-11ea-9f48-2c45719d605b.png)

**Comment by FrogsOfDoom** [comment]
Both now function properly. Thanks!
