### ISSUE TITLE
[8193.14 preview] Terrain rendering issues

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#78]
Sometimes creating new areas in the toolset doesn't render the "tiles" themselves, making them look blank. This can occur to existing or new tilesets. I'm not sure at this point what may cause it but here's an example of this happening:

![image](https://user-images.githubusercontent.com/51026560/83952301-f65fd580-a805-11ea-835e-6eb489041622.png)

**Comment by FrogsOfDoom** [comment]
FYI, this still occurs in .15.

**Comment by virusman** [comment]
@FrogsOfDoom Unfortunately there is not enough information in the ticket to reproduce this. Especially if it only happens sometimes.

**Comment by FrogsOfDoom** [comment]
Here are two screencaps of it occurring, the Medieval Rural 2 is a shorter version, just shows missing blade grass textures, the other is the step by step. This consistently happens whenever I create a second area in the toolset. As you will see, placing a few road tiles in a specific order shows the terrain normally but changing them back hides it again. Let me know if you need more information (system, graphic card, etc.)
[Video.zip](https://github.com/Beamdog/nwn-issues/files/4773876/Video.zip)

**Comment by FrogsOfDoom** [comment]
This is now fixed, at least in my toolset.
