### ISSUE TITLE
[8193.14 preview] Missing tlk/ref entry in Creatures palette

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#79]
Missing tlk or reference entry in Creatures Palette -> Animals -> Birds, results in a blank line.

![image](https://user-images.githubusercontent.com/51026560/83953157-fbc01e80-a80b-11ea-8717-8b4b9aaa1498.png)

**Specifics**

 - Game build (8193.14)
 - OS (Windows 10)
 - Distro platform (Steam)
 - Content overrides? (None)

**Comment by Bill-Harper** [comment]
Just an empty reference that got added in by mistake when mass-editing the ITP file. Should be good in next patch.

**Comment by FrogsOfDoom** [comment]
This is now fixed.
