### ISSUE TITLE
[8193.14 preview] ambientmusic.2da - Numbering problem

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#80]
Minor but in ambientmusic.2da, Daggerford music lines are misnumbered; rather than being 81 to 98, should be 120 to 137:

![image](https://user-images.githubusercontent.com/51026560/83953447-81dd6480-a80e-11ea-995d-e92bdb21f650.png)

**Comment by Bill-Harper** [comment]
Oops! (Sorted for next patch). We still have the TLK entries (or support for a local string instead) to solve.

**Comment by FrogsOfDoom** [comment]
The 2da numbering issue is now fixed. Thanks.
