### ISSUE TITLE
Castle Exterior Rural Tileset Cave Entrance Door Mesh Issue

### ISSUE THREAD

**Issue by Clockwerkd** [Beamdog/nwn-issues#90]
**Description**

The Castle Exterior, Rural Tileset cave entrance door mesh does not conform to the cave opening but rather expands beyond the opening confines in the shape of a square plane

**To Reproduce**

 - Place an instance of a cave entrance in an area within the Castle Exterior, Rural tileset.

**Specifics**

 - Game Build: 8193.13
 - OS: Windows 10
 - Distro Platform: BDC

**Comment by Bill-Harper** [comment]
![tno_cave_entrance](https://user-images.githubusercontent.com/53191846/84930877-f1b9dd80-b09f-11ea-9904-95dd696ae9f7.png)

This is working as intended in the current 8193.14 premier patch

**Comment by Anatida** [comment]
I have duplicated the OPs issue while trying to fix my own.

**Description of My issue**
If using any doortypes.2da in a hak, including the default/vanilla 2da, the TNO tileset does not use the appropriate cave door appearance.

**To Reproduce**
Include the default doortypes.2da in a hak. Associate the hak with the module. Place the Grass/Cave Entrance in any area.

Game Build: 8193.13
OS: Windows 10
Distro Platform: Steam

![image](https://user-images.githubusercontent.com/50813811/86178369-d9a97b80-baed-11ea-90da-904c2f795b9f.png)

**To Reproduce the OP's issue**
In trying to fix my issue with the cave door, I added a new entry into the doortypes.2da to use the cave entry (ttr_udoor_06) door specifically for the TNO tileset - as previously the TNO01.set file called for row 57. Which works if you do not have a doortypes.2da in a hak file.
![image](https://user-images.githubusercontent.com/50813811/86178959-f85c4200-baee-11ea-83d7-dbfa3216877d.png)

I realize this falls under a 'hak problem'. However, if we can't even use the default doortypes.2da in a hak without it breaking the tileset, then that is a tileset and default 2da issue.

Fixing this issue required adding a line to the doortypes.2da that is specific for tileset TNO01, and editing the .Set file to call the appropriate line, as well as changing the Zaxis orientation of the door. The door does still not fit exactly into the cave entrance, but is better than it was.
![image](https://user-images.githubusercontent.com/50813811/86179445-e4651000-baef-11ea-9965-e7c7660c29c8.png)
![image](https://user-images.githubusercontent.com/50813811/86179463-ec24b480-baef-11ea-9f23-9353444ee86a.png)
![image](https://user-images.githubusercontent.com/50813811/86179682-5fc6c180-baf0-11ea-9958-cf0aaa99fc1e.png)

**Comment by Bill-Harper** [comment]
What does your doortypes.2da have at entry #240? The base 2DA has tn_sdoor_31, a new door which is aligned for both TNO01 and this cave entry in the SET file. As the stock 2DA has different lines than yours at 242 and 243, (new entries 240-243 since 1.69) I suspect this entry may also be not the same?

**Comment by Bill-Harper** [comment]
![tn_sdoor_31_toolset](https://user-images.githubusercontent.com/53191846/88179743-5665dc00-cbfa-11ea-991e-9398729492b6.png) 

 Here is a shot from the upcoming release, with toolset display restored. I think we're good to go on this one; please check your 2DA's versus the latest build, especially lines 240-243 (reserved space was used).
