### ISSUE TITLE
tnp_patch_d03 & tnp_patch_g03 - too low

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#93]
These two models are too low, so they disappear/clip when placed on the ground; would need a z-axis adjustment.

tnp_patch_g03: "Ground - Grass Patch 3"
tnp_patch_d03: "Ground - Dirt Patch 3"

**Comment by Bill-Harper** [comment]
(_Fixed in a Previous Build_) Thanks for reporting, let us know if you have any future issues!
