### ISSUE TITLE
[Preview 8193.14 - 6/9 Commit] Toolset Will Not Create New Areas & Other Issues

### ISSUE THREAD

**Issue by pstemarie** [Beamdog/nwn-issues#96]
**To Reproduce**

 - Open or create a module in the toolset.
 - Try to create an area. 
 - Toolset crashes.

**Specifics**

 - 8193.14 Preview (Released 6/9)

**If needed, describe the bug**

![NewModule](https://user-images.githubusercontent.com/58920224/84249053-44abf780-aad8-11ea-8a71-b82707391c1f.jpg)

Other issues include (you'll see the pattern here is shadows)...

1. Areas made with custom tilesets that have shadows disabled in the models not rendering properly until you click on a tile to place. 
2. If you click on an object to place the tileset stops rendering again.
3. Tile/Object Selector doesn't render unless you toggle on/off shadows.

**Comment by Soren217** [comment]
Thanks for reporting this. We have focused a fair bit on getting the toolset running for all with the preview build and should soon have resolved all the crashing issues.

**Comment by pstemarie** [comment]
Great! I really like where the toolset is headed and I look forward to being able to use the preview build again.
