### ISSUE TITLE
Favorite Enemy: Ooze missing

### ISSUE THREAD

**Issue by FrogsOfDoom** [Beamdog/nwn-issues#97]
Not a new bug but there's no Favorite Enemy (Ooze). When the Ooze racial type was added, I think around 1.69, they forgot to add Favorite Enemy for it.

**Comment by Stratovarius667** [comment]
> Not a new bug but there's no Favorite Enemy (Ooze). When the Ooze racial type was added, I think around 1.69, they forgot to add Favorite Enemy for it.

Will second this, although it is a minor issue.

**Comment by Finaldeath** [comment]
FavouredEnemyFeat column added to racialtypes.2da allows custom content to fix this for Ooze and other races. No plans to add a new feat to the game to cover it however.
