### ISSUE TITLE
ActionUseFeat, ActionCastSpellAtObject, ActionCastSpellAtLocation Issues

### ISSUE THREAD

**Issue by Finaldeath** [Beamdog/nwn-issues#98]
**To Reproduce**

 - Give an NPC a feat or spell from the below description
 - Run a simple script to ActionUseFeat/ActionCastSpellAtTarget/ActionCastSpellAtLocation on self or a target such as the PC. Checking with GetHasSpell() or GetHasFeat() can show it doesn't get used at all (not even decrementing the use of it).
 - Spell fails, with no action taking place, it just drops/never tries the action.

**Specifics**

 - OS Windows
 - Game build 80.8193.14 [cfbb70df]
 - Distro platform Steam
 - Content overrides? None

**If needed, describe the bug**

ActionUseFeat() - This somewhat rarely works with feats linked to spells.2da (example of working: FEAT_TURN_UNDEAD). Examples of not working: FEAT_EPIC_SPELL_HELLBALL, FEAT_HARPER_SLEEP, FEAT_EPIC_SPELL_DRAGON_KNIGHT. I am pretty sure all hardcoded usable combat feats work. The spell-like ones mainly bug out - even ones usually castable on a target. Self-targeting ones tend to work or single target buffs cast on self - need to test if FEAT_HARPER_EAGLES_SPLENDOR works on others.

There is also no way to make use of "sub-feats" properly again just standing there doing nothing (numbers are kind of faked using spells.2da I think see: http://www.alandfaraway.info/node/813 ) but you can pass them in, but the action fails. eg; Wild Shape passing in FeatID number 66060288 - Brown Bear variant - it fails the action and stands there. Notably the huge feat ID appears valid to GetHasFeat(). You can use the basic "Wild Shape" feat, but the game detects as "oops you can't do this" and sends a random ID to the spell script/GetSpellId() - hardcoded probably?

Relatedly you can't choose what Called Shot you use either (and no idea how you would be able to given no IDs for the sub feat choice in nwscript.nss).

Note there is no ActionUseFeatAtLocation() for some feats that could benefit from it/may be necessary if the spells.2da TargetType doesn't allow a creature target.

ActionCastSpellAtTarget/AtLocation - This fails and the spells don't perform any actions in the below cases. You can bypass this by bCheat, which isn't a great idea (messes up level and DC, and have to rely on DecrementRemainingSpellUses()).
 - Child spells such as Shadow variants (SHADOW_CONJURATION_ACID_ARROW for instance, even when GetHasSpell() works with it). Some polymorph sub-dial spells seems to work since they're cast on yourself, so even more weird.
 - Spontaneous spells (eg CURE_CRITICAL_WOUNDS on a cleric class spell) - when the spell is otherwise not memorised so it's forced to be spontaenous. In these cases GetHasSpell() is valid for it, but it fails and they stand there.

PS: I'm Jasperre on discord. Edit: Updated with more testing. Apologies.

**Comment by pF-arQon** [comment]
re FEAT_EPIC_SPELL_HELLBALL, my recollection is that the bug is rooted in GetCasterLevel bugging out and returning a CL of 0 if cast by an *N*PC.

(We have comments in the source there that skip the usual PreCast checks as a result, since our PreCast causes anything with an invalid CL to just be aborted. I don't remember if the BW code does the same thing or if that part's just us, but maybe it'll help).

**Comment by Finaldeath** [comment]
That might be the case but is unrelated to the actions themselves just not firing, or firing the wrong outcome.

**Comment by shadguy** [comment]
I'm attaching a repro case.  We have a widget in game to help auto buffing, and it doesn't work with Domain spells.  The repro case shows a cleric with Cat's Grace as a Domain spell, and we cannot automate the casting of the spell.  The demo mod also shows that Cure Light Wounds cannot be spontaneously automated.  

I've attached the demo mod as well as a save game with a cleric already setup to show the above issues.

Repro steps:
1) Load the savegame
2) Observe the player's quickbar - there are 4 spells hotkeyed in sequence, from Cat's Grace->Bull's Strength->Bless->Cure Light Wounds
3) Observe 4 switches in front of you labelled with each spell name
4) Try pulling each switch.
a) Cat's Grace is correctly recognized as available by GetHasSpell, but we cannot automate casting of it by pulling the switch
b) Bull's Str and Bless with both be cast by the player character when she pulled the appropriate switch
c) Cure Light Wounds is not memorized, but is available spontaneously to clerics.  Pulling the Wure Light Wounds switch cannot, however, automate casting of the spell on oneself.

Fixing this should fix our PW in-game spell buff sequencer, which uses only vanilla API (no nwnx).

-Dave


[Demo_Domain_ActionCastSpellAtObjectl.zip](https://github.com/Beamdog/nwn-issues/files/6057467/Demo_Domain_ActionCastSpellAtObjectl.zip)
[000002 - Demo_Domain_ActionCastSpel.zip](https://github.com/Beamdog/nwn-issues/files/6057471/000002.-.Demo_Domain_ActionCastSpel.zip)

**Comment by Daztek** [comment]
@shadguy I looked into this a bit... casting domain spells does work, but you have to pass the correct domain level to ActionCastSpell(). Cat's Grace is from the War Domain and if you look in domains.2da you'll see it's given at the second spell level, which is what you need to supply to ActionCastSpell()

Spontaneous casting does not seem to be supported tho.

**Comment by shadguy** [comment]
Daz, thanks for spending some time to look at this.  I've made a note on my to do list to circle back on this with your suggestion in mind.
-Dave

**Comment by Finaldeath** [comment]
This is fixed in a future 36 by adding additional parameters to ActionCastSpell
